"""Generated by scripts/generate_colors.py. Do not edit by hand."""

from __future__ import annotations

from typing import TypeAlias


class TikzColor:
    """An xcolor-compatible TikZ color expression."""

    def __init__(self, color_spec: str) -> None:
        if color_spec == "":
            raise ValueError("color_spec must not be empty")
        self.color_spec = color_spec

    @staticmethod
    def _normalize_percent(percent: float) -> str:
        if not isinstance(percent, (int, float)):
            raise TypeError("percent must be an int or float")
        numeric = float(percent)
        if numeric < 0:
            raise ValueError("percent must be non-negative")
        if isinstance(percent, int):
            value = numeric
        elif numeric <= 1:
            value = numeric * 100
        else:
            value = numeric
        if value > 100:
            raise ValueError("percent must be between 0 and 1, or between 0 and 100")
        if value.is_integer():
            return str(int(value))
        return str(value)

    @staticmethod
    def _coerce(other: str | TikzColor) -> str:
        if isinstance(other, TikzColor):
            return other.color_spec
        return other

    def mix(
        self, other: str | TikzColor | None = None, percent: float = 0.5
    ) -> TikzColor:
        """Build an xcolor mix like ``red!50`` or ``red!50!blue``."""
        pct = self._normalize_percent(percent)
        if other is None:
            return TikzColor(f"{self.color_spec}!{pct}")
        return TikzColor(f"{self.color_spec}!{pct}!{self._coerce(other)}")

    def complement(self) -> TikzColor:
        """Return the xcolor complementary-expression form."""
        return TikzColor(f"-{self.color_spec}")

    def to_tikz(self) -> str:
        """Return the raw xcolor expression."""
        return self.color_spec

    def __neg__(self) -> TikzColor:
        return self.complement()

    def __str__(self) -> str:
        return self.color_spec

    def __repr__(self) -> str:
        return f"TikzColor({self.color_spec!r})"

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, TikzColor):
            return NotImplemented
        return self.color_spec == other.color_spec

    def __hash__(self) -> int:
        return hash(self.color_spec)


ColorInput: TypeAlias = str | TikzColor

black: TikzColor = TikzColor("black")
blue: TikzColor = TikzColor("blue")
brown: TikzColor = TikzColor("brown")
cyan: TikzColor = TikzColor("cyan")
darkgray: TikzColor = TikzColor("darkgray")
gray: TikzColor = TikzColor("gray")
green: TikzColor = TikzColor("green")
lightgray: TikzColor = TikzColor("lightgray")
lime: TikzColor = TikzColor("lime")
magenta: TikzColor = TikzColor("magenta")
olive: TikzColor = TikzColor("olive")
orange: TikzColor = TikzColor("orange")
pink: TikzColor = TikzColor("pink")
purple: TikzColor = TikzColor("purple")
red: TikzColor = TikzColor("red")
teal: TikzColor = TikzColor("teal")
violet: TikzColor = TikzColor("violet")
white: TikzColor = TikzColor("white")
yellow: TikzColor = TikzColor("yellow")
Apricot: TikzColor = TikzColor("Apricot")
apricot: TikzColor = TikzColor("Apricot")
Aquamarine: TikzColor = TikzColor("Aquamarine")
aquamarine: TikzColor = TikzColor("Aquamarine")
Bittersweet: TikzColor = TikzColor("Bittersweet")
bittersweet: TikzColor = TikzColor("Bittersweet")
Black: TikzColor = TikzColor("Black")
Blue: TikzColor = TikzColor("Blue")
BlueGreen: TikzColor = TikzColor("BlueGreen")
blue_green: TikzColor = TikzColor("BlueGreen")
BlueViolet: TikzColor = TikzColor("BlueViolet")
blue_violet: TikzColor = TikzColor("BlueViolet")
BrickRed: TikzColor = TikzColor("BrickRed")
brick_red: TikzColor = TikzColor("BrickRed")
Brown: TikzColor = TikzColor("Brown")
BurntOrange: TikzColor = TikzColor("BurntOrange")
burnt_orange: TikzColor = TikzColor("BurntOrange")
CadetBlue: TikzColor = TikzColor("CadetBlue")
cadet_blue: TikzColor = TikzColor("CadetBlue")
CarnationPink: TikzColor = TikzColor("CarnationPink")
carnation_pink: TikzColor = TikzColor("CarnationPink")
Cerulean: TikzColor = TikzColor("Cerulean")
cerulean: TikzColor = TikzColor("Cerulean")
CornflowerBlue: TikzColor = TikzColor("CornflowerBlue")
cornflower_blue: TikzColor = TikzColor("CornflowerBlue")
Cyan: TikzColor = TikzColor("Cyan")
Dandelion: TikzColor = TikzColor("Dandelion")
dandelion: TikzColor = TikzColor("Dandelion")
DarkOrchid: TikzColor = TikzColor("DarkOrchid")
dark_orchid: TikzColor = TikzColor("DarkOrchid")
Emerald: TikzColor = TikzColor("Emerald")
emerald: TikzColor = TikzColor("Emerald")
ForestGreen: TikzColor = TikzColor("ForestGreen")
forest_green: TikzColor = TikzColor("ForestGreen")
Fuchsia: TikzColor = TikzColor("Fuchsia")
fuchsia: TikzColor = TikzColor("Fuchsia")
Goldenrod: TikzColor = TikzColor("Goldenrod")
goldenrod: TikzColor = TikzColor("Goldenrod")
Gray: TikzColor = TikzColor("Gray")
Green: TikzColor = TikzColor("Green")
GreenYellow: TikzColor = TikzColor("GreenYellow")
green_yellow: TikzColor = TikzColor("GreenYellow")
JungleGreen: TikzColor = TikzColor("JungleGreen")
jungle_green: TikzColor = TikzColor("JungleGreen")
Lavender: TikzColor = TikzColor("Lavender")
lavender: TikzColor = TikzColor("Lavender")
LimeGreen: TikzColor = TikzColor("LimeGreen")
lime_green: TikzColor = TikzColor("LimeGreen")
Magenta: TikzColor = TikzColor("Magenta")
Mahogany: TikzColor = TikzColor("Mahogany")
mahogany: TikzColor = TikzColor("Mahogany")
Maroon: TikzColor = TikzColor("Maroon")
maroon: TikzColor = TikzColor("Maroon")
Melon: TikzColor = TikzColor("Melon")
melon: TikzColor = TikzColor("Melon")
MidnightBlue: TikzColor = TikzColor("MidnightBlue")
midnight_blue: TikzColor = TikzColor("MidnightBlue")
Mulberry: TikzColor = TikzColor("Mulberry")
mulberry: TikzColor = TikzColor("Mulberry")
NavyBlue: TikzColor = TikzColor("NavyBlue")
navy_blue: TikzColor = TikzColor("NavyBlue")
OliveGreen: TikzColor = TikzColor("OliveGreen")
olive_green: TikzColor = TikzColor("OliveGreen")
Orange: TikzColor = TikzColor("Orange")
OrangeRed: TikzColor = TikzColor("OrangeRed")
orange_red: TikzColor = TikzColor("OrangeRed")
Orchid: TikzColor = TikzColor("Orchid")
orchid: TikzColor = TikzColor("Orchid")
Peach: TikzColor = TikzColor("Peach")
peach: TikzColor = TikzColor("Peach")
Periwinkle: TikzColor = TikzColor("Periwinkle")
periwinkle: TikzColor = TikzColor("Periwinkle")
PineGreen: TikzColor = TikzColor("PineGreen")
pine_green: TikzColor = TikzColor("PineGreen")
Plum: TikzColor = TikzColor("Plum")
plum: TikzColor = TikzColor("Plum")
ProcessBlue: TikzColor = TikzColor("ProcessBlue")
process_blue: TikzColor = TikzColor("ProcessBlue")
Purple: TikzColor = TikzColor("Purple")
RawSienna: TikzColor = TikzColor("RawSienna")
raw_sienna: TikzColor = TikzColor("RawSienna")
Red: TikzColor = TikzColor("Red")
RedOrange: TikzColor = TikzColor("RedOrange")
red_orange: TikzColor = TikzColor("RedOrange")
RedViolet: TikzColor = TikzColor("RedViolet")
red_violet: TikzColor = TikzColor("RedViolet")
Rhodamine: TikzColor = TikzColor("Rhodamine")
rhodamine: TikzColor = TikzColor("Rhodamine")
RoyalBlue: TikzColor = TikzColor("RoyalBlue")
royal_blue: TikzColor = TikzColor("RoyalBlue")
RoyalPurple: TikzColor = TikzColor("RoyalPurple")
royal_purple: TikzColor = TikzColor("RoyalPurple")
RubineRed: TikzColor = TikzColor("RubineRed")
rubine_red: TikzColor = TikzColor("RubineRed")
Salmon: TikzColor = TikzColor("Salmon")
salmon: TikzColor = TikzColor("Salmon")
SeaGreen: TikzColor = TikzColor("SeaGreen")
sea_green: TikzColor = TikzColor("SeaGreen")
Sepia: TikzColor = TikzColor("Sepia")
sepia: TikzColor = TikzColor("Sepia")
SkyBlue: TikzColor = TikzColor("SkyBlue")
sky_blue: TikzColor = TikzColor("SkyBlue")
SpringGreen: TikzColor = TikzColor("SpringGreen")
spring_green: TikzColor = TikzColor("SpringGreen")
Tan: TikzColor = TikzColor("Tan")
tan: TikzColor = TikzColor("Tan")
TealBlue: TikzColor = TikzColor("TealBlue")
teal_blue: TikzColor = TikzColor("TealBlue")
Thistle: TikzColor = TikzColor("Thistle")
thistle: TikzColor = TikzColor("Thistle")
Turquoise: TikzColor = TikzColor("Turquoise")
turquoise: TikzColor = TikzColor("Turquoise")
Violet: TikzColor = TikzColor("Violet")
VioletRed: TikzColor = TikzColor("VioletRed")
violet_red: TikzColor = TikzColor("VioletRed")
White: TikzColor = TikzColor("White")
WildStrawberry: TikzColor = TikzColor("WildStrawberry")
wild_strawberry: TikzColor = TikzColor("WildStrawberry")
Yellow: TikzColor = TikzColor("Yellow")
YellowGreen: TikzColor = TikzColor("YellowGreen")
yellow_green: TikzColor = TikzColor("YellowGreen")
YellowOrange: TikzColor = TikzColor("YellowOrange")
yellow_orange: TikzColor = TikzColor("YellowOrange")
AliceBlue: TikzColor = TikzColor("AliceBlue")
alice_blue: TikzColor = TikzColor("AliceBlue")
AntiqueWhite: TikzColor = TikzColor("AntiqueWhite")
antique_white: TikzColor = TikzColor("AntiqueWhite")
Aqua: TikzColor = TikzColor("Aqua")
aqua: TikzColor = TikzColor("Aqua")
Azure: TikzColor = TikzColor("Azure")
azure: TikzColor = TikzColor("Azure")
Beige: TikzColor = TikzColor("Beige")
beige: TikzColor = TikzColor("Beige")
Bisque: TikzColor = TikzColor("Bisque")
bisque: TikzColor = TikzColor("Bisque")
BlanchedAlmond: TikzColor = TikzColor("BlanchedAlmond")
blanched_almond: TikzColor = TikzColor("BlanchedAlmond")
BurlyWood: TikzColor = TikzColor("BurlyWood")
burly_wood: TikzColor = TikzColor("BurlyWood")
Chartreuse: TikzColor = TikzColor("Chartreuse")
chartreuse: TikzColor = TikzColor("Chartreuse")
Chocolate: TikzColor = TikzColor("Chocolate")
chocolate: TikzColor = TikzColor("Chocolate")
Coral: TikzColor = TikzColor("Coral")
coral: TikzColor = TikzColor("Coral")
Cornsilk: TikzColor = TikzColor("Cornsilk")
cornsilk: TikzColor = TikzColor("Cornsilk")
Crimson: TikzColor = TikzColor("Crimson")
crimson: TikzColor = TikzColor("Crimson")
DarkBlue: TikzColor = TikzColor("DarkBlue")
dark_blue: TikzColor = TikzColor("DarkBlue")
DarkCyan: TikzColor = TikzColor("DarkCyan")
dark_cyan: TikzColor = TikzColor("DarkCyan")
DarkGoldenrod: TikzColor = TikzColor("DarkGoldenrod")
dark_goldenrod: TikzColor = TikzColor("DarkGoldenrod")
DarkGray: TikzColor = TikzColor("DarkGray")
dark_gray: TikzColor = TikzColor("DarkGray")
DarkGreen: TikzColor = TikzColor("DarkGreen")
dark_green: TikzColor = TikzColor("DarkGreen")
DarkGrey: TikzColor = TikzColor("DarkGrey")
dark_grey: TikzColor = TikzColor("DarkGrey")
DarkKhaki: TikzColor = TikzColor("DarkKhaki")
dark_khaki: TikzColor = TikzColor("DarkKhaki")
DarkMagenta: TikzColor = TikzColor("DarkMagenta")
dark_magenta: TikzColor = TikzColor("DarkMagenta")
DarkOliveGreen: TikzColor = TikzColor("DarkOliveGreen")
dark_olive_green: TikzColor = TikzColor("DarkOliveGreen")
DarkOrange: TikzColor = TikzColor("DarkOrange")
dark_orange: TikzColor = TikzColor("DarkOrange")
DarkRed: TikzColor = TikzColor("DarkRed")
dark_red: TikzColor = TikzColor("DarkRed")
DarkSalmon: TikzColor = TikzColor("DarkSalmon")
dark_salmon: TikzColor = TikzColor("DarkSalmon")
DarkSeaGreen: TikzColor = TikzColor("DarkSeaGreen")
dark_sea_green: TikzColor = TikzColor("DarkSeaGreen")
DarkSlateBlue: TikzColor = TikzColor("DarkSlateBlue")
dark_slate_blue: TikzColor = TikzColor("DarkSlateBlue")
DarkSlateGray: TikzColor = TikzColor("DarkSlateGray")
dark_slate_gray: TikzColor = TikzColor("DarkSlateGray")
DarkSlateGrey: TikzColor = TikzColor("DarkSlateGrey")
dark_slate_grey: TikzColor = TikzColor("DarkSlateGrey")
DarkTurquoise: TikzColor = TikzColor("DarkTurquoise")
dark_turquoise: TikzColor = TikzColor("DarkTurquoise")
DarkViolet: TikzColor = TikzColor("DarkViolet")
dark_violet: TikzColor = TikzColor("DarkViolet")
DeepPink: TikzColor = TikzColor("DeepPink")
deep_pink: TikzColor = TikzColor("DeepPink")
DeepSkyBlue: TikzColor = TikzColor("DeepSkyBlue")
deep_sky_blue: TikzColor = TikzColor("DeepSkyBlue")
DimGray: TikzColor = TikzColor("DimGray")
dim_gray: TikzColor = TikzColor("DimGray")
DimGrey: TikzColor = TikzColor("DimGrey")
dim_grey: TikzColor = TikzColor("DimGrey")
DodgerBlue: TikzColor = TikzColor("DodgerBlue")
dodger_blue: TikzColor = TikzColor("DodgerBlue")
FireBrick: TikzColor = TikzColor("FireBrick")
fire_brick: TikzColor = TikzColor("FireBrick")
FloralWhite: TikzColor = TikzColor("FloralWhite")
floral_white: TikzColor = TikzColor("FloralWhite")
Gainsboro: TikzColor = TikzColor("Gainsboro")
gainsboro: TikzColor = TikzColor("Gainsboro")
GhostWhite: TikzColor = TikzColor("GhostWhite")
ghost_white: TikzColor = TikzColor("GhostWhite")
Gold: TikzColor = TikzColor("Gold")
gold: TikzColor = TikzColor("Gold")
Grey: TikzColor = TikzColor("Grey")
grey: TikzColor = TikzColor("Grey")
Honeydew: TikzColor = TikzColor("Honeydew")
honeydew: TikzColor = TikzColor("Honeydew")
HotPink: TikzColor = TikzColor("HotPink")
hot_pink: TikzColor = TikzColor("HotPink")
IndianRed: TikzColor = TikzColor("IndianRed")
indian_red: TikzColor = TikzColor("IndianRed")
Indigo: TikzColor = TikzColor("Indigo")
indigo: TikzColor = TikzColor("Indigo")
Ivory: TikzColor = TikzColor("Ivory")
ivory: TikzColor = TikzColor("Ivory")
Khaki: TikzColor = TikzColor("Khaki")
khaki: TikzColor = TikzColor("Khaki")
LavenderBlush: TikzColor = TikzColor("LavenderBlush")
lavender_blush: TikzColor = TikzColor("LavenderBlush")
LawnGreen: TikzColor = TikzColor("LawnGreen")
lawn_green: TikzColor = TikzColor("LawnGreen")
LemonChiffon: TikzColor = TikzColor("LemonChiffon")
lemon_chiffon: TikzColor = TikzColor("LemonChiffon")
LightBlue: TikzColor = TikzColor("LightBlue")
light_blue: TikzColor = TikzColor("LightBlue")
LightCoral: TikzColor = TikzColor("LightCoral")
light_coral: TikzColor = TikzColor("LightCoral")
LightCyan: TikzColor = TikzColor("LightCyan")
light_cyan: TikzColor = TikzColor("LightCyan")
LightGoldenrod: TikzColor = TikzColor("LightGoldenrod")
light_goldenrod: TikzColor = TikzColor("LightGoldenrod")
LightGoldenrodYellow: TikzColor = TikzColor("LightGoldenrodYellow")
light_goldenrod_yellow: TikzColor = TikzColor("LightGoldenrodYellow")
LightGray: TikzColor = TikzColor("LightGray")
light_gray: TikzColor = TikzColor("LightGray")
LightGreen: TikzColor = TikzColor("LightGreen")
light_green: TikzColor = TikzColor("LightGreen")
LightGrey: TikzColor = TikzColor("LightGrey")
light_grey: TikzColor = TikzColor("LightGrey")
LightPink: TikzColor = TikzColor("LightPink")
light_pink: TikzColor = TikzColor("LightPink")
LightSalmon: TikzColor = TikzColor("LightSalmon")
light_salmon: TikzColor = TikzColor("LightSalmon")
LightSeaGreen: TikzColor = TikzColor("LightSeaGreen")
light_sea_green: TikzColor = TikzColor("LightSeaGreen")
LightSkyBlue: TikzColor = TikzColor("LightSkyBlue")
light_sky_blue: TikzColor = TikzColor("LightSkyBlue")
LightSlateBlue: TikzColor = TikzColor("LightSlateBlue")
light_slate_blue: TikzColor = TikzColor("LightSlateBlue")
LightSlateGray: TikzColor = TikzColor("LightSlateGray")
light_slate_gray: TikzColor = TikzColor("LightSlateGray")
LightSlateGrey: TikzColor = TikzColor("LightSlateGrey")
light_slate_grey: TikzColor = TikzColor("LightSlateGrey")
LightSteelBlue: TikzColor = TikzColor("LightSteelBlue")
light_steel_blue: TikzColor = TikzColor("LightSteelBlue")
LightYellow: TikzColor = TikzColor("LightYellow")
light_yellow: TikzColor = TikzColor("LightYellow")
Lime: TikzColor = TikzColor("Lime")
Linen: TikzColor = TikzColor("Linen")
linen: TikzColor = TikzColor("Linen")
MediumAquamarine: TikzColor = TikzColor("MediumAquamarine")
medium_aquamarine: TikzColor = TikzColor("MediumAquamarine")
MediumBlue: TikzColor = TikzColor("MediumBlue")
medium_blue: TikzColor = TikzColor("MediumBlue")
MediumOrchid: TikzColor = TikzColor("MediumOrchid")
medium_orchid: TikzColor = TikzColor("MediumOrchid")
MediumPurple: TikzColor = TikzColor("MediumPurple")
medium_purple: TikzColor = TikzColor("MediumPurple")
MediumSeaGreen: TikzColor = TikzColor("MediumSeaGreen")
medium_sea_green: TikzColor = TikzColor("MediumSeaGreen")
MediumSlateBlue: TikzColor = TikzColor("MediumSlateBlue")
medium_slate_blue: TikzColor = TikzColor("MediumSlateBlue")
MediumSpringGreen: TikzColor = TikzColor("MediumSpringGreen")
medium_spring_green: TikzColor = TikzColor("MediumSpringGreen")
MediumTurquoise: TikzColor = TikzColor("MediumTurquoise")
medium_turquoise: TikzColor = TikzColor("MediumTurquoise")
MediumVioletRed: TikzColor = TikzColor("MediumVioletRed")
medium_violet_red: TikzColor = TikzColor("MediumVioletRed")
MintCream: TikzColor = TikzColor("MintCream")
mint_cream: TikzColor = TikzColor("MintCream")
MistyRose: TikzColor = TikzColor("MistyRose")
misty_rose: TikzColor = TikzColor("MistyRose")
Moccasin: TikzColor = TikzColor("Moccasin")
moccasin: TikzColor = TikzColor("Moccasin")
NavajoWhite: TikzColor = TikzColor("NavajoWhite")
navajo_white: TikzColor = TikzColor("NavajoWhite")
Navy: TikzColor = TikzColor("Navy")
navy: TikzColor = TikzColor("Navy")
OldLace: TikzColor = TikzColor("OldLace")
old_lace: TikzColor = TikzColor("OldLace")
Olive: TikzColor = TikzColor("Olive")
OliveDrab: TikzColor = TikzColor("OliveDrab")
olive_drab: TikzColor = TikzColor("OliveDrab")
PaleGoldenrod: TikzColor = TikzColor("PaleGoldenrod")
pale_goldenrod: TikzColor = TikzColor("PaleGoldenrod")
PaleGreen: TikzColor = TikzColor("PaleGreen")
pale_green: TikzColor = TikzColor("PaleGreen")
PaleTurquoise: TikzColor = TikzColor("PaleTurquoise")
pale_turquoise: TikzColor = TikzColor("PaleTurquoise")
PaleVioletRed: TikzColor = TikzColor("PaleVioletRed")
pale_violet_red: TikzColor = TikzColor("PaleVioletRed")
PapayaWhip: TikzColor = TikzColor("PapayaWhip")
papaya_whip: TikzColor = TikzColor("PapayaWhip")
PeachPuff: TikzColor = TikzColor("PeachPuff")
peach_puff: TikzColor = TikzColor("PeachPuff")
Peru: TikzColor = TikzColor("Peru")
peru: TikzColor = TikzColor("Peru")
Pink: TikzColor = TikzColor("Pink")
PowderBlue: TikzColor = TikzColor("PowderBlue")
powder_blue: TikzColor = TikzColor("PowderBlue")
RosyBrown: TikzColor = TikzColor("RosyBrown")
rosy_brown: TikzColor = TikzColor("RosyBrown")
SaddleBrown: TikzColor = TikzColor("SaddleBrown")
saddle_brown: TikzColor = TikzColor("SaddleBrown")
SandyBrown: TikzColor = TikzColor("SandyBrown")
sandy_brown: TikzColor = TikzColor("SandyBrown")
Seashell: TikzColor = TikzColor("Seashell")
seashell: TikzColor = TikzColor("Seashell")
Sienna: TikzColor = TikzColor("Sienna")
sienna: TikzColor = TikzColor("Sienna")
Silver: TikzColor = TikzColor("Silver")
silver: TikzColor = TikzColor("Silver")
SlateBlue: TikzColor = TikzColor("SlateBlue")
slate_blue: TikzColor = TikzColor("SlateBlue")
SlateGray: TikzColor = TikzColor("SlateGray")
slate_gray: TikzColor = TikzColor("SlateGray")
SlateGrey: TikzColor = TikzColor("SlateGrey")
slate_grey: TikzColor = TikzColor("SlateGrey")
Snow: TikzColor = TikzColor("Snow")
snow: TikzColor = TikzColor("Snow")
SteelBlue: TikzColor = TikzColor("SteelBlue")
steel_blue: TikzColor = TikzColor("SteelBlue")
Teal: TikzColor = TikzColor("Teal")
Tomato: TikzColor = TikzColor("Tomato")
tomato: TikzColor = TikzColor("Tomato")
Wheat: TikzColor = TikzColor("Wheat")
wheat: TikzColor = TikzColor("Wheat")
WhiteSmoke: TikzColor = TikzColor("WhiteSmoke")
white_smoke: TikzColor = TikzColor("WhiteSmoke")
AntiqueWhite1: TikzColor = TikzColor("AntiqueWhite1")
antique_white1: TikzColor = TikzColor("AntiqueWhite1")
AntiqueWhite2: TikzColor = TikzColor("AntiqueWhite2")
antique_white2: TikzColor = TikzColor("AntiqueWhite2")
AntiqueWhite3: TikzColor = TikzColor("AntiqueWhite3")
antique_white3: TikzColor = TikzColor("AntiqueWhite3")
AntiqueWhite4: TikzColor = TikzColor("AntiqueWhite4")
antique_white4: TikzColor = TikzColor("AntiqueWhite4")
Aquamarine1: TikzColor = TikzColor("Aquamarine1")
aquamarine1: TikzColor = TikzColor("Aquamarine1")
Aquamarine2: TikzColor = TikzColor("Aquamarine2")
aquamarine2: TikzColor = TikzColor("Aquamarine2")
Aquamarine3: TikzColor = TikzColor("Aquamarine3")
aquamarine3: TikzColor = TikzColor("Aquamarine3")
Aquamarine4: TikzColor = TikzColor("Aquamarine4")
aquamarine4: TikzColor = TikzColor("Aquamarine4")
Azure1: TikzColor = TikzColor("Azure1")
azure1: TikzColor = TikzColor("Azure1")
Azure2: TikzColor = TikzColor("Azure2")
azure2: TikzColor = TikzColor("Azure2")
Azure3: TikzColor = TikzColor("Azure3")
azure3: TikzColor = TikzColor("Azure3")
Azure4: TikzColor = TikzColor("Azure4")
azure4: TikzColor = TikzColor("Azure4")
Bisque1: TikzColor = TikzColor("Bisque1")
bisque1: TikzColor = TikzColor("Bisque1")
Bisque2: TikzColor = TikzColor("Bisque2")
bisque2: TikzColor = TikzColor("Bisque2")
Bisque3: TikzColor = TikzColor("Bisque3")
bisque3: TikzColor = TikzColor("Bisque3")
Bisque4: TikzColor = TikzColor("Bisque4")
bisque4: TikzColor = TikzColor("Bisque4")
Blue1: TikzColor = TikzColor("Blue1")
blue1: TikzColor = TikzColor("Blue1")
Blue2: TikzColor = TikzColor("Blue2")
blue2: TikzColor = TikzColor("Blue2")
Blue3: TikzColor = TikzColor("Blue3")
blue3: TikzColor = TikzColor("Blue3")
Blue4: TikzColor = TikzColor("Blue4")
blue4: TikzColor = TikzColor("Blue4")
Brown1: TikzColor = TikzColor("Brown1")
brown1: TikzColor = TikzColor("Brown1")
Brown2: TikzColor = TikzColor("Brown2")
brown2: TikzColor = TikzColor("Brown2")
Brown3: TikzColor = TikzColor("Brown3")
brown3: TikzColor = TikzColor("Brown3")
Brown4: TikzColor = TikzColor("Brown4")
brown4: TikzColor = TikzColor("Brown4")
Burlywood1: TikzColor = TikzColor("Burlywood1")
burlywood1: TikzColor = TikzColor("Burlywood1")
Burlywood2: TikzColor = TikzColor("Burlywood2")
burlywood2: TikzColor = TikzColor("Burlywood2")
Burlywood3: TikzColor = TikzColor("Burlywood3")
burlywood3: TikzColor = TikzColor("Burlywood3")
Burlywood4: TikzColor = TikzColor("Burlywood4")
burlywood4: TikzColor = TikzColor("Burlywood4")
CadetBlue1: TikzColor = TikzColor("CadetBlue1")
cadet_blue1: TikzColor = TikzColor("CadetBlue1")
CadetBlue2: TikzColor = TikzColor("CadetBlue2")
cadet_blue2: TikzColor = TikzColor("CadetBlue2")
CadetBlue3: TikzColor = TikzColor("CadetBlue3")
cadet_blue3: TikzColor = TikzColor("CadetBlue3")
CadetBlue4: TikzColor = TikzColor("CadetBlue4")
cadet_blue4: TikzColor = TikzColor("CadetBlue4")
Chartreuse1: TikzColor = TikzColor("Chartreuse1")
chartreuse1: TikzColor = TikzColor("Chartreuse1")
Chartreuse2: TikzColor = TikzColor("Chartreuse2")
chartreuse2: TikzColor = TikzColor("Chartreuse2")
Chartreuse3: TikzColor = TikzColor("Chartreuse3")
chartreuse3: TikzColor = TikzColor("Chartreuse3")
Chartreuse4: TikzColor = TikzColor("Chartreuse4")
chartreuse4: TikzColor = TikzColor("Chartreuse4")
Chocolate1: TikzColor = TikzColor("Chocolate1")
chocolate1: TikzColor = TikzColor("Chocolate1")
Chocolate2: TikzColor = TikzColor("Chocolate2")
chocolate2: TikzColor = TikzColor("Chocolate2")
Chocolate3: TikzColor = TikzColor("Chocolate3")
chocolate3: TikzColor = TikzColor("Chocolate3")
Chocolate4: TikzColor = TikzColor("Chocolate4")
chocolate4: TikzColor = TikzColor("Chocolate4")
Coral1: TikzColor = TikzColor("Coral1")
coral1: TikzColor = TikzColor("Coral1")
Coral2: TikzColor = TikzColor("Coral2")
coral2: TikzColor = TikzColor("Coral2")
Coral3: TikzColor = TikzColor("Coral3")
coral3: TikzColor = TikzColor("Coral3")
Coral4: TikzColor = TikzColor("Coral4")
coral4: TikzColor = TikzColor("Coral4")
Cornsilk1: TikzColor = TikzColor("Cornsilk1")
cornsilk1: TikzColor = TikzColor("Cornsilk1")
Cornsilk2: TikzColor = TikzColor("Cornsilk2")
cornsilk2: TikzColor = TikzColor("Cornsilk2")
Cornsilk3: TikzColor = TikzColor("Cornsilk3")
cornsilk3: TikzColor = TikzColor("Cornsilk3")
Cornsilk4: TikzColor = TikzColor("Cornsilk4")
cornsilk4: TikzColor = TikzColor("Cornsilk4")
Cyan1: TikzColor = TikzColor("Cyan1")
cyan1: TikzColor = TikzColor("Cyan1")
Cyan2: TikzColor = TikzColor("Cyan2")
cyan2: TikzColor = TikzColor("Cyan2")
Cyan3: TikzColor = TikzColor("Cyan3")
cyan3: TikzColor = TikzColor("Cyan3")
Cyan4: TikzColor = TikzColor("Cyan4")
cyan4: TikzColor = TikzColor("Cyan4")
DarkGoldenrod1: TikzColor = TikzColor("DarkGoldenrod1")
dark_goldenrod1: TikzColor = TikzColor("DarkGoldenrod1")
DarkGoldenrod2: TikzColor = TikzColor("DarkGoldenrod2")
dark_goldenrod2: TikzColor = TikzColor("DarkGoldenrod2")
DarkGoldenrod3: TikzColor = TikzColor("DarkGoldenrod3")
dark_goldenrod3: TikzColor = TikzColor("DarkGoldenrod3")
DarkGoldenrod4: TikzColor = TikzColor("DarkGoldenrod4")
dark_goldenrod4: TikzColor = TikzColor("DarkGoldenrod4")
DarkOliveGreen1: TikzColor = TikzColor("DarkOliveGreen1")
dark_olive_green1: TikzColor = TikzColor("DarkOliveGreen1")
DarkOliveGreen2: TikzColor = TikzColor("DarkOliveGreen2")
dark_olive_green2: TikzColor = TikzColor("DarkOliveGreen2")
DarkOliveGreen3: TikzColor = TikzColor("DarkOliveGreen3")
dark_olive_green3: TikzColor = TikzColor("DarkOliveGreen3")
DarkOliveGreen4: TikzColor = TikzColor("DarkOliveGreen4")
dark_olive_green4: TikzColor = TikzColor("DarkOliveGreen4")
DarkOrange1: TikzColor = TikzColor("DarkOrange1")
dark_orange1: TikzColor = TikzColor("DarkOrange1")
DarkOrange2: TikzColor = TikzColor("DarkOrange2")
dark_orange2: TikzColor = TikzColor("DarkOrange2")
DarkOrange3: TikzColor = TikzColor("DarkOrange3")
dark_orange3: TikzColor = TikzColor("DarkOrange3")
DarkOrange4: TikzColor = TikzColor("DarkOrange4")
dark_orange4: TikzColor = TikzColor("DarkOrange4")
DarkOrchid1: TikzColor = TikzColor("DarkOrchid1")
dark_orchid1: TikzColor = TikzColor("DarkOrchid1")
DarkOrchid2: TikzColor = TikzColor("DarkOrchid2")
dark_orchid2: TikzColor = TikzColor("DarkOrchid2")
DarkOrchid3: TikzColor = TikzColor("DarkOrchid3")
dark_orchid3: TikzColor = TikzColor("DarkOrchid3")
DarkOrchid4: TikzColor = TikzColor("DarkOrchid4")
dark_orchid4: TikzColor = TikzColor("DarkOrchid4")
DarkSeaGreen1: TikzColor = TikzColor("DarkSeaGreen1")
dark_sea_green1: TikzColor = TikzColor("DarkSeaGreen1")
DarkSeaGreen2: TikzColor = TikzColor("DarkSeaGreen2")
dark_sea_green2: TikzColor = TikzColor("DarkSeaGreen2")
DarkSeaGreen3: TikzColor = TikzColor("DarkSeaGreen3")
dark_sea_green3: TikzColor = TikzColor("DarkSeaGreen3")
DarkSeaGreen4: TikzColor = TikzColor("DarkSeaGreen4")
dark_sea_green4: TikzColor = TikzColor("DarkSeaGreen4")
DarkSlateGray1: TikzColor = TikzColor("DarkSlateGray1")
dark_slate_gray1: TikzColor = TikzColor("DarkSlateGray1")
DarkSlateGray2: TikzColor = TikzColor("DarkSlateGray2")
dark_slate_gray2: TikzColor = TikzColor("DarkSlateGray2")
DarkSlateGray3: TikzColor = TikzColor("DarkSlateGray3")
dark_slate_gray3: TikzColor = TikzColor("DarkSlateGray3")
DarkSlateGray4: TikzColor = TikzColor("DarkSlateGray4")
dark_slate_gray4: TikzColor = TikzColor("DarkSlateGray4")
DeepPink1: TikzColor = TikzColor("DeepPink1")
deep_pink1: TikzColor = TikzColor("DeepPink1")
DeepPink2: TikzColor = TikzColor("DeepPink2")
deep_pink2: TikzColor = TikzColor("DeepPink2")
DeepPink3: TikzColor = TikzColor("DeepPink3")
deep_pink3: TikzColor = TikzColor("DeepPink3")
DeepPink4: TikzColor = TikzColor("DeepPink4")
deep_pink4: TikzColor = TikzColor("DeepPink4")
DeepSkyBlue1: TikzColor = TikzColor("DeepSkyBlue1")
deep_sky_blue1: TikzColor = TikzColor("DeepSkyBlue1")
DeepSkyBlue2: TikzColor = TikzColor("DeepSkyBlue2")
deep_sky_blue2: TikzColor = TikzColor("DeepSkyBlue2")
DeepSkyBlue3: TikzColor = TikzColor("DeepSkyBlue3")
deep_sky_blue3: TikzColor = TikzColor("DeepSkyBlue3")
DeepSkyBlue4: TikzColor = TikzColor("DeepSkyBlue4")
deep_sky_blue4: TikzColor = TikzColor("DeepSkyBlue4")
DodgerBlue1: TikzColor = TikzColor("DodgerBlue1")
dodger_blue1: TikzColor = TikzColor("DodgerBlue1")
DodgerBlue2: TikzColor = TikzColor("DodgerBlue2")
dodger_blue2: TikzColor = TikzColor("DodgerBlue2")
DodgerBlue3: TikzColor = TikzColor("DodgerBlue3")
dodger_blue3: TikzColor = TikzColor("DodgerBlue3")
DodgerBlue4: TikzColor = TikzColor("DodgerBlue4")
dodger_blue4: TikzColor = TikzColor("DodgerBlue4")
Firebrick1: TikzColor = TikzColor("Firebrick1")
firebrick1: TikzColor = TikzColor("Firebrick1")
Firebrick2: TikzColor = TikzColor("Firebrick2")
firebrick2: TikzColor = TikzColor("Firebrick2")
Firebrick3: TikzColor = TikzColor("Firebrick3")
firebrick3: TikzColor = TikzColor("Firebrick3")
Firebrick4: TikzColor = TikzColor("Firebrick4")
firebrick4: TikzColor = TikzColor("Firebrick4")
Gold1: TikzColor = TikzColor("Gold1")
gold1: TikzColor = TikzColor("Gold1")
Gold2: TikzColor = TikzColor("Gold2")
gold2: TikzColor = TikzColor("Gold2")
Gold3: TikzColor = TikzColor("Gold3")
gold3: TikzColor = TikzColor("Gold3")
Gold4: TikzColor = TikzColor("Gold4")
gold4: TikzColor = TikzColor("Gold4")
Goldenrod1: TikzColor = TikzColor("Goldenrod1")
goldenrod1: TikzColor = TikzColor("Goldenrod1")
Goldenrod2: TikzColor = TikzColor("Goldenrod2")
goldenrod2: TikzColor = TikzColor("Goldenrod2")
Goldenrod3: TikzColor = TikzColor("Goldenrod3")
goldenrod3: TikzColor = TikzColor("Goldenrod3")
Goldenrod4: TikzColor = TikzColor("Goldenrod4")
goldenrod4: TikzColor = TikzColor("Goldenrod4")
Green1: TikzColor = TikzColor("Green1")
green1: TikzColor = TikzColor("Green1")
Green2: TikzColor = TikzColor("Green2")
green2: TikzColor = TikzColor("Green2")
Green3: TikzColor = TikzColor("Green3")
green3: TikzColor = TikzColor("Green3")
Green4: TikzColor = TikzColor("Green4")
green4: TikzColor = TikzColor("Green4")
Honeydew1: TikzColor = TikzColor("Honeydew1")
honeydew1: TikzColor = TikzColor("Honeydew1")
Honeydew2: TikzColor = TikzColor("Honeydew2")
honeydew2: TikzColor = TikzColor("Honeydew2")
Honeydew3: TikzColor = TikzColor("Honeydew3")
honeydew3: TikzColor = TikzColor("Honeydew3")
Honeydew4: TikzColor = TikzColor("Honeydew4")
honeydew4: TikzColor = TikzColor("Honeydew4")
HotPink1: TikzColor = TikzColor("HotPink1")
hot_pink1: TikzColor = TikzColor("HotPink1")
HotPink2: TikzColor = TikzColor("HotPink2")
hot_pink2: TikzColor = TikzColor("HotPink2")
HotPink3: TikzColor = TikzColor("HotPink3")
hot_pink3: TikzColor = TikzColor("HotPink3")
HotPink4: TikzColor = TikzColor("HotPink4")
hot_pink4: TikzColor = TikzColor("HotPink4")
IndianRed1: TikzColor = TikzColor("IndianRed1")
indian_red1: TikzColor = TikzColor("IndianRed1")
IndianRed2: TikzColor = TikzColor("IndianRed2")
indian_red2: TikzColor = TikzColor("IndianRed2")
IndianRed3: TikzColor = TikzColor("IndianRed3")
indian_red3: TikzColor = TikzColor("IndianRed3")
IndianRed4: TikzColor = TikzColor("IndianRed4")
indian_red4: TikzColor = TikzColor("IndianRed4")
Ivory1: TikzColor = TikzColor("Ivory1")
ivory1: TikzColor = TikzColor("Ivory1")
Ivory2: TikzColor = TikzColor("Ivory2")
ivory2: TikzColor = TikzColor("Ivory2")
Ivory3: TikzColor = TikzColor("Ivory3")
ivory3: TikzColor = TikzColor("Ivory3")
Ivory4: TikzColor = TikzColor("Ivory4")
ivory4: TikzColor = TikzColor("Ivory4")
Khaki1: TikzColor = TikzColor("Khaki1")
khaki1: TikzColor = TikzColor("Khaki1")
Khaki2: TikzColor = TikzColor("Khaki2")
khaki2: TikzColor = TikzColor("Khaki2")
Khaki3: TikzColor = TikzColor("Khaki3")
khaki3: TikzColor = TikzColor("Khaki3")
Khaki4: TikzColor = TikzColor("Khaki4")
khaki4: TikzColor = TikzColor("Khaki4")
LavenderBlush1: TikzColor = TikzColor("LavenderBlush1")
lavender_blush1: TikzColor = TikzColor("LavenderBlush1")
LavenderBlush2: TikzColor = TikzColor("LavenderBlush2")
lavender_blush2: TikzColor = TikzColor("LavenderBlush2")
LavenderBlush3: TikzColor = TikzColor("LavenderBlush3")
lavender_blush3: TikzColor = TikzColor("LavenderBlush3")
LavenderBlush4: TikzColor = TikzColor("LavenderBlush4")
lavender_blush4: TikzColor = TikzColor("LavenderBlush4")
LemonChiffon1: TikzColor = TikzColor("LemonChiffon1")
lemon_chiffon1: TikzColor = TikzColor("LemonChiffon1")
LemonChiffon2: TikzColor = TikzColor("LemonChiffon2")
lemon_chiffon2: TikzColor = TikzColor("LemonChiffon2")
LemonChiffon3: TikzColor = TikzColor("LemonChiffon3")
lemon_chiffon3: TikzColor = TikzColor("LemonChiffon3")
LemonChiffon4: TikzColor = TikzColor("LemonChiffon4")
lemon_chiffon4: TikzColor = TikzColor("LemonChiffon4")
LightBlue1: TikzColor = TikzColor("LightBlue1")
light_blue1: TikzColor = TikzColor("LightBlue1")
LightBlue2: TikzColor = TikzColor("LightBlue2")
light_blue2: TikzColor = TikzColor("LightBlue2")
LightBlue3: TikzColor = TikzColor("LightBlue3")
light_blue3: TikzColor = TikzColor("LightBlue3")
LightBlue4: TikzColor = TikzColor("LightBlue4")
light_blue4: TikzColor = TikzColor("LightBlue4")
LightCyan1: TikzColor = TikzColor("LightCyan1")
light_cyan1: TikzColor = TikzColor("LightCyan1")
LightCyan2: TikzColor = TikzColor("LightCyan2")
light_cyan2: TikzColor = TikzColor("LightCyan2")
LightCyan3: TikzColor = TikzColor("LightCyan3")
light_cyan3: TikzColor = TikzColor("LightCyan3")
LightCyan4: TikzColor = TikzColor("LightCyan4")
light_cyan4: TikzColor = TikzColor("LightCyan4")
LightGoldenrod1: TikzColor = TikzColor("LightGoldenrod1")
light_goldenrod1: TikzColor = TikzColor("LightGoldenrod1")
LightGoldenrod2: TikzColor = TikzColor("LightGoldenrod2")
light_goldenrod2: TikzColor = TikzColor("LightGoldenrod2")
LightGoldenrod3: TikzColor = TikzColor("LightGoldenrod3")
light_goldenrod3: TikzColor = TikzColor("LightGoldenrod3")
LightGoldenrod4: TikzColor = TikzColor("LightGoldenrod4")
light_goldenrod4: TikzColor = TikzColor("LightGoldenrod4")
LightPink1: TikzColor = TikzColor("LightPink1")
light_pink1: TikzColor = TikzColor("LightPink1")
LightPink2: TikzColor = TikzColor("LightPink2")
light_pink2: TikzColor = TikzColor("LightPink2")
LightPink3: TikzColor = TikzColor("LightPink3")
light_pink3: TikzColor = TikzColor("LightPink3")
LightPink4: TikzColor = TikzColor("LightPink4")
light_pink4: TikzColor = TikzColor("LightPink4")
LightSalmon1: TikzColor = TikzColor("LightSalmon1")
light_salmon1: TikzColor = TikzColor("LightSalmon1")
LightSalmon2: TikzColor = TikzColor("LightSalmon2")
light_salmon2: TikzColor = TikzColor("LightSalmon2")
LightSalmon3: TikzColor = TikzColor("LightSalmon3")
light_salmon3: TikzColor = TikzColor("LightSalmon3")
LightSalmon4: TikzColor = TikzColor("LightSalmon4")
light_salmon4: TikzColor = TikzColor("LightSalmon4")
LightSkyBlue1: TikzColor = TikzColor("LightSkyBlue1")
light_sky_blue1: TikzColor = TikzColor("LightSkyBlue1")
LightSkyBlue2: TikzColor = TikzColor("LightSkyBlue2")
light_sky_blue2: TikzColor = TikzColor("LightSkyBlue2")
LightSkyBlue3: TikzColor = TikzColor("LightSkyBlue3")
light_sky_blue3: TikzColor = TikzColor("LightSkyBlue3")
LightSkyBlue4: TikzColor = TikzColor("LightSkyBlue4")
light_sky_blue4: TikzColor = TikzColor("LightSkyBlue4")
LightSteelBlue1: TikzColor = TikzColor("LightSteelBlue1")
light_steel_blue1: TikzColor = TikzColor("LightSteelBlue1")
LightSteelBlue2: TikzColor = TikzColor("LightSteelBlue2")
light_steel_blue2: TikzColor = TikzColor("LightSteelBlue2")
LightSteelBlue3: TikzColor = TikzColor("LightSteelBlue3")
light_steel_blue3: TikzColor = TikzColor("LightSteelBlue3")
LightSteelBlue4: TikzColor = TikzColor("LightSteelBlue4")
light_steel_blue4: TikzColor = TikzColor("LightSteelBlue4")
LightYellow1: TikzColor = TikzColor("LightYellow1")
light_yellow1: TikzColor = TikzColor("LightYellow1")
LightYellow2: TikzColor = TikzColor("LightYellow2")
light_yellow2: TikzColor = TikzColor("LightYellow2")
LightYellow3: TikzColor = TikzColor("LightYellow3")
light_yellow3: TikzColor = TikzColor("LightYellow3")
LightYellow4: TikzColor = TikzColor("LightYellow4")
light_yellow4: TikzColor = TikzColor("LightYellow4")
Magenta1: TikzColor = TikzColor("Magenta1")
magenta1: TikzColor = TikzColor("Magenta1")
Magenta2: TikzColor = TikzColor("Magenta2")
magenta2: TikzColor = TikzColor("Magenta2")
Magenta3: TikzColor = TikzColor("Magenta3")
magenta3: TikzColor = TikzColor("Magenta3")
Magenta4: TikzColor = TikzColor("Magenta4")
magenta4: TikzColor = TikzColor("Magenta4")
Maroon1: TikzColor = TikzColor("Maroon1")
maroon1: TikzColor = TikzColor("Maroon1")
Maroon2: TikzColor = TikzColor("Maroon2")
maroon2: TikzColor = TikzColor("Maroon2")
Maroon3: TikzColor = TikzColor("Maroon3")
maroon3: TikzColor = TikzColor("Maroon3")
Maroon4: TikzColor = TikzColor("Maroon4")
maroon4: TikzColor = TikzColor("Maroon4")
MediumOrchid1: TikzColor = TikzColor("MediumOrchid1")
medium_orchid1: TikzColor = TikzColor("MediumOrchid1")
MediumOrchid2: TikzColor = TikzColor("MediumOrchid2")
medium_orchid2: TikzColor = TikzColor("MediumOrchid2")
MediumOrchid3: TikzColor = TikzColor("MediumOrchid3")
medium_orchid3: TikzColor = TikzColor("MediumOrchid3")
MediumOrchid4: TikzColor = TikzColor("MediumOrchid4")
medium_orchid4: TikzColor = TikzColor("MediumOrchid4")
MediumPurple1: TikzColor = TikzColor("MediumPurple1")
medium_purple1: TikzColor = TikzColor("MediumPurple1")
MediumPurple2: TikzColor = TikzColor("MediumPurple2")
medium_purple2: TikzColor = TikzColor("MediumPurple2")
MediumPurple3: TikzColor = TikzColor("MediumPurple3")
medium_purple3: TikzColor = TikzColor("MediumPurple3")
MediumPurple4: TikzColor = TikzColor("MediumPurple4")
medium_purple4: TikzColor = TikzColor("MediumPurple4")
MistyRose1: TikzColor = TikzColor("MistyRose1")
misty_rose1: TikzColor = TikzColor("MistyRose1")
MistyRose2: TikzColor = TikzColor("MistyRose2")
misty_rose2: TikzColor = TikzColor("MistyRose2")
MistyRose3: TikzColor = TikzColor("MistyRose3")
misty_rose3: TikzColor = TikzColor("MistyRose3")
MistyRose4: TikzColor = TikzColor("MistyRose4")
misty_rose4: TikzColor = TikzColor("MistyRose4")
NavajoWhite1: TikzColor = TikzColor("NavajoWhite1")
navajo_white1: TikzColor = TikzColor("NavajoWhite1")
NavajoWhite2: TikzColor = TikzColor("NavajoWhite2")
navajo_white2: TikzColor = TikzColor("NavajoWhite2")
NavajoWhite3: TikzColor = TikzColor("NavajoWhite3")
navajo_white3: TikzColor = TikzColor("NavajoWhite3")
NavajoWhite4: TikzColor = TikzColor("NavajoWhite4")
navajo_white4: TikzColor = TikzColor("NavajoWhite4")
OliveDrab1: TikzColor = TikzColor("OliveDrab1")
olive_drab1: TikzColor = TikzColor("OliveDrab1")
OliveDrab2: TikzColor = TikzColor("OliveDrab2")
olive_drab2: TikzColor = TikzColor("OliveDrab2")
OliveDrab3: TikzColor = TikzColor("OliveDrab3")
olive_drab3: TikzColor = TikzColor("OliveDrab3")
OliveDrab4: TikzColor = TikzColor("OliveDrab4")
olive_drab4: TikzColor = TikzColor("OliveDrab4")
Orange1: TikzColor = TikzColor("Orange1")
orange1: TikzColor = TikzColor("Orange1")
Orange2: TikzColor = TikzColor("Orange2")
orange2: TikzColor = TikzColor("Orange2")
Orange3: TikzColor = TikzColor("Orange3")
orange3: TikzColor = TikzColor("Orange3")
Orange4: TikzColor = TikzColor("Orange4")
orange4: TikzColor = TikzColor("Orange4")
OrangeRed1: TikzColor = TikzColor("OrangeRed1")
orange_red1: TikzColor = TikzColor("OrangeRed1")
OrangeRed2: TikzColor = TikzColor("OrangeRed2")
orange_red2: TikzColor = TikzColor("OrangeRed2")
OrangeRed3: TikzColor = TikzColor("OrangeRed3")
orange_red3: TikzColor = TikzColor("OrangeRed3")
OrangeRed4: TikzColor = TikzColor("OrangeRed4")
orange_red4: TikzColor = TikzColor("OrangeRed4")
Orchid1: TikzColor = TikzColor("Orchid1")
orchid1: TikzColor = TikzColor("Orchid1")
Orchid2: TikzColor = TikzColor("Orchid2")
orchid2: TikzColor = TikzColor("Orchid2")
Orchid3: TikzColor = TikzColor("Orchid3")
orchid3: TikzColor = TikzColor("Orchid3")
Orchid4: TikzColor = TikzColor("Orchid4")
orchid4: TikzColor = TikzColor("Orchid4")
PaleGreen1: TikzColor = TikzColor("PaleGreen1")
pale_green1: TikzColor = TikzColor("PaleGreen1")
PaleGreen2: TikzColor = TikzColor("PaleGreen2")
pale_green2: TikzColor = TikzColor("PaleGreen2")
PaleGreen3: TikzColor = TikzColor("PaleGreen3")
pale_green3: TikzColor = TikzColor("PaleGreen3")
PaleGreen4: TikzColor = TikzColor("PaleGreen4")
pale_green4: TikzColor = TikzColor("PaleGreen4")
PaleTurquoise1: TikzColor = TikzColor("PaleTurquoise1")
pale_turquoise1: TikzColor = TikzColor("PaleTurquoise1")
PaleTurquoise2: TikzColor = TikzColor("PaleTurquoise2")
pale_turquoise2: TikzColor = TikzColor("PaleTurquoise2")
PaleTurquoise3: TikzColor = TikzColor("PaleTurquoise3")
pale_turquoise3: TikzColor = TikzColor("PaleTurquoise3")
PaleTurquoise4: TikzColor = TikzColor("PaleTurquoise4")
pale_turquoise4: TikzColor = TikzColor("PaleTurquoise4")
PaleVioletRed1: TikzColor = TikzColor("PaleVioletRed1")
pale_violet_red1: TikzColor = TikzColor("PaleVioletRed1")
PaleVioletRed2: TikzColor = TikzColor("PaleVioletRed2")
pale_violet_red2: TikzColor = TikzColor("PaleVioletRed2")
PaleVioletRed3: TikzColor = TikzColor("PaleVioletRed3")
pale_violet_red3: TikzColor = TikzColor("PaleVioletRed3")
PaleVioletRed4: TikzColor = TikzColor("PaleVioletRed4")
pale_violet_red4: TikzColor = TikzColor("PaleVioletRed4")
PeachPuff1: TikzColor = TikzColor("PeachPuff1")
peach_puff1: TikzColor = TikzColor("PeachPuff1")
PeachPuff2: TikzColor = TikzColor("PeachPuff2")
peach_puff2: TikzColor = TikzColor("PeachPuff2")
PeachPuff3: TikzColor = TikzColor("PeachPuff3")
peach_puff3: TikzColor = TikzColor("PeachPuff3")
PeachPuff4: TikzColor = TikzColor("PeachPuff4")
peach_puff4: TikzColor = TikzColor("PeachPuff4")
Pink1: TikzColor = TikzColor("Pink1")
pink1: TikzColor = TikzColor("Pink1")
Pink2: TikzColor = TikzColor("Pink2")
pink2: TikzColor = TikzColor("Pink2")
Pink3: TikzColor = TikzColor("Pink3")
pink3: TikzColor = TikzColor("Pink3")
Pink4: TikzColor = TikzColor("Pink4")
pink4: TikzColor = TikzColor("Pink4")
Plum1: TikzColor = TikzColor("Plum1")
plum1: TikzColor = TikzColor("Plum1")
Plum2: TikzColor = TikzColor("Plum2")
plum2: TikzColor = TikzColor("Plum2")
Plum3: TikzColor = TikzColor("Plum3")
plum3: TikzColor = TikzColor("Plum3")
Plum4: TikzColor = TikzColor("Plum4")
plum4: TikzColor = TikzColor("Plum4")
Purple1: TikzColor = TikzColor("Purple1")
purple1: TikzColor = TikzColor("Purple1")
Purple2: TikzColor = TikzColor("Purple2")
purple2: TikzColor = TikzColor("Purple2")
Purple3: TikzColor = TikzColor("Purple3")
purple3: TikzColor = TikzColor("Purple3")
Purple4: TikzColor = TikzColor("Purple4")
purple4: TikzColor = TikzColor("Purple4")
Red1: TikzColor = TikzColor("Red1")
red1: TikzColor = TikzColor("Red1")
Red2: TikzColor = TikzColor("Red2")
red2: TikzColor = TikzColor("Red2")
Red3: TikzColor = TikzColor("Red3")
red3: TikzColor = TikzColor("Red3")
Red4: TikzColor = TikzColor("Red4")
red4: TikzColor = TikzColor("Red4")
RosyBrown1: TikzColor = TikzColor("RosyBrown1")
rosy_brown1: TikzColor = TikzColor("RosyBrown1")
RosyBrown2: TikzColor = TikzColor("RosyBrown2")
rosy_brown2: TikzColor = TikzColor("RosyBrown2")
RosyBrown3: TikzColor = TikzColor("RosyBrown3")
rosy_brown3: TikzColor = TikzColor("RosyBrown3")
RosyBrown4: TikzColor = TikzColor("RosyBrown4")
rosy_brown4: TikzColor = TikzColor("RosyBrown4")
RoyalBlue1: TikzColor = TikzColor("RoyalBlue1")
royal_blue1: TikzColor = TikzColor("RoyalBlue1")
RoyalBlue2: TikzColor = TikzColor("RoyalBlue2")
royal_blue2: TikzColor = TikzColor("RoyalBlue2")
RoyalBlue3: TikzColor = TikzColor("RoyalBlue3")
royal_blue3: TikzColor = TikzColor("RoyalBlue3")
RoyalBlue4: TikzColor = TikzColor("RoyalBlue4")
royal_blue4: TikzColor = TikzColor("RoyalBlue4")
Salmon1: TikzColor = TikzColor("Salmon1")
salmon1: TikzColor = TikzColor("Salmon1")
Salmon2: TikzColor = TikzColor("Salmon2")
salmon2: TikzColor = TikzColor("Salmon2")
Salmon3: TikzColor = TikzColor("Salmon3")
salmon3: TikzColor = TikzColor("Salmon3")
Salmon4: TikzColor = TikzColor("Salmon4")
salmon4: TikzColor = TikzColor("Salmon4")
SeaGreen1: TikzColor = TikzColor("SeaGreen1")
sea_green1: TikzColor = TikzColor("SeaGreen1")
SeaGreen2: TikzColor = TikzColor("SeaGreen2")
sea_green2: TikzColor = TikzColor("SeaGreen2")
SeaGreen3: TikzColor = TikzColor("SeaGreen3")
sea_green3: TikzColor = TikzColor("SeaGreen3")
SeaGreen4: TikzColor = TikzColor("SeaGreen4")
sea_green4: TikzColor = TikzColor("SeaGreen4")
Seashell1: TikzColor = TikzColor("Seashell1")
seashell1: TikzColor = TikzColor("Seashell1")
Seashell2: TikzColor = TikzColor("Seashell2")
seashell2: TikzColor = TikzColor("Seashell2")
Seashell3: TikzColor = TikzColor("Seashell3")
seashell3: TikzColor = TikzColor("Seashell3")
Seashell4: TikzColor = TikzColor("Seashell4")
seashell4: TikzColor = TikzColor("Seashell4")
Sienna1: TikzColor = TikzColor("Sienna1")
sienna1: TikzColor = TikzColor("Sienna1")
Sienna2: TikzColor = TikzColor("Sienna2")
sienna2: TikzColor = TikzColor("Sienna2")
Sienna3: TikzColor = TikzColor("Sienna3")
sienna3: TikzColor = TikzColor("Sienna3")
Sienna4: TikzColor = TikzColor("Sienna4")
sienna4: TikzColor = TikzColor("Sienna4")
SkyBlue1: TikzColor = TikzColor("SkyBlue1")
sky_blue1: TikzColor = TikzColor("SkyBlue1")
SkyBlue2: TikzColor = TikzColor("SkyBlue2")
sky_blue2: TikzColor = TikzColor("SkyBlue2")
SkyBlue3: TikzColor = TikzColor("SkyBlue3")
sky_blue3: TikzColor = TikzColor("SkyBlue3")
SkyBlue4: TikzColor = TikzColor("SkyBlue4")
sky_blue4: TikzColor = TikzColor("SkyBlue4")
SlateBlue1: TikzColor = TikzColor("SlateBlue1")
slate_blue1: TikzColor = TikzColor("SlateBlue1")
SlateBlue2: TikzColor = TikzColor("SlateBlue2")
slate_blue2: TikzColor = TikzColor("SlateBlue2")
SlateBlue3: TikzColor = TikzColor("SlateBlue3")
slate_blue3: TikzColor = TikzColor("SlateBlue3")
SlateBlue4: TikzColor = TikzColor("SlateBlue4")
slate_blue4: TikzColor = TikzColor("SlateBlue4")
SlateGray1: TikzColor = TikzColor("SlateGray1")
slate_gray1: TikzColor = TikzColor("SlateGray1")
SlateGray2: TikzColor = TikzColor("SlateGray2")
slate_gray2: TikzColor = TikzColor("SlateGray2")
SlateGray3: TikzColor = TikzColor("SlateGray3")
slate_gray3: TikzColor = TikzColor("SlateGray3")
SlateGray4: TikzColor = TikzColor("SlateGray4")
slate_gray4: TikzColor = TikzColor("SlateGray4")
Snow1: TikzColor = TikzColor("Snow1")
snow1: TikzColor = TikzColor("Snow1")
Snow2: TikzColor = TikzColor("Snow2")
snow2: TikzColor = TikzColor("Snow2")
Snow3: TikzColor = TikzColor("Snow3")
snow3: TikzColor = TikzColor("Snow3")
Snow4: TikzColor = TikzColor("Snow4")
snow4: TikzColor = TikzColor("Snow4")
SpringGreen1: TikzColor = TikzColor("SpringGreen1")
spring_green1: TikzColor = TikzColor("SpringGreen1")
SpringGreen2: TikzColor = TikzColor("SpringGreen2")
spring_green2: TikzColor = TikzColor("SpringGreen2")
SpringGreen3: TikzColor = TikzColor("SpringGreen3")
spring_green3: TikzColor = TikzColor("SpringGreen3")
SpringGreen4: TikzColor = TikzColor("SpringGreen4")
spring_green4: TikzColor = TikzColor("SpringGreen4")
SteelBlue1: TikzColor = TikzColor("SteelBlue1")
steel_blue1: TikzColor = TikzColor("SteelBlue1")
SteelBlue2: TikzColor = TikzColor("SteelBlue2")
steel_blue2: TikzColor = TikzColor("SteelBlue2")
SteelBlue3: TikzColor = TikzColor("SteelBlue3")
steel_blue3: TikzColor = TikzColor("SteelBlue3")
SteelBlue4: TikzColor = TikzColor("SteelBlue4")
steel_blue4: TikzColor = TikzColor("SteelBlue4")
Tan1: TikzColor = TikzColor("Tan1")
tan1: TikzColor = TikzColor("Tan1")
Tan2: TikzColor = TikzColor("Tan2")
tan2: TikzColor = TikzColor("Tan2")
Tan3: TikzColor = TikzColor("Tan3")
tan3: TikzColor = TikzColor("Tan3")
Tan4: TikzColor = TikzColor("Tan4")
tan4: TikzColor = TikzColor("Tan4")
Thistle1: TikzColor = TikzColor("Thistle1")
thistle1: TikzColor = TikzColor("Thistle1")
Thistle2: TikzColor = TikzColor("Thistle2")
thistle2: TikzColor = TikzColor("Thistle2")
Thistle3: TikzColor = TikzColor("Thistle3")
thistle3: TikzColor = TikzColor("Thistle3")
Thistle4: TikzColor = TikzColor("Thistle4")
thistle4: TikzColor = TikzColor("Thistle4")
Tomato1: TikzColor = TikzColor("Tomato1")
tomato1: TikzColor = TikzColor("Tomato1")
Tomato2: TikzColor = TikzColor("Tomato2")
tomato2: TikzColor = TikzColor("Tomato2")
Tomato3: TikzColor = TikzColor("Tomato3")
tomato3: TikzColor = TikzColor("Tomato3")
Tomato4: TikzColor = TikzColor("Tomato4")
tomato4: TikzColor = TikzColor("Tomato4")
Turquoise1: TikzColor = TikzColor("Turquoise1")
turquoise1: TikzColor = TikzColor("Turquoise1")
Turquoise2: TikzColor = TikzColor("Turquoise2")
turquoise2: TikzColor = TikzColor("Turquoise2")
Turquoise3: TikzColor = TikzColor("Turquoise3")
turquoise3: TikzColor = TikzColor("Turquoise3")
Turquoise4: TikzColor = TikzColor("Turquoise4")
turquoise4: TikzColor = TikzColor("Turquoise4")
VioletRed1: TikzColor = TikzColor("VioletRed1")
violet_red1: TikzColor = TikzColor("VioletRed1")
VioletRed2: TikzColor = TikzColor("VioletRed2")
violet_red2: TikzColor = TikzColor("VioletRed2")
VioletRed3: TikzColor = TikzColor("VioletRed3")
violet_red3: TikzColor = TikzColor("VioletRed3")
VioletRed4: TikzColor = TikzColor("VioletRed4")
violet_red4: TikzColor = TikzColor("VioletRed4")
Wheat1: TikzColor = TikzColor("Wheat1")
wheat1: TikzColor = TikzColor("Wheat1")
Wheat2: TikzColor = TikzColor("Wheat2")
wheat2: TikzColor = TikzColor("Wheat2")
Wheat3: TikzColor = TikzColor("Wheat3")
wheat3: TikzColor = TikzColor("Wheat3")
Wheat4: TikzColor = TikzColor("Wheat4")
wheat4: TikzColor = TikzColor("Wheat4")
Yellow1: TikzColor = TikzColor("Yellow1")
yellow1: TikzColor = TikzColor("Yellow1")
Yellow2: TikzColor = TikzColor("Yellow2")
yellow2: TikzColor = TikzColor("Yellow2")
Yellow3: TikzColor = TikzColor("Yellow3")
yellow3: TikzColor = TikzColor("Yellow3")
Yellow4: TikzColor = TikzColor("Yellow4")
yellow4: TikzColor = TikzColor("Yellow4")
Gray0: TikzColor = TikzColor("Gray0")
gray0: TikzColor = TikzColor("Gray0")
Green0: TikzColor = TikzColor("Green0")
green0: TikzColor = TikzColor("Green0")
Grey0: TikzColor = TikzColor("Grey0")
grey0: TikzColor = TikzColor("Grey0")
Maroon0: TikzColor = TikzColor("Maroon0")
maroon0: TikzColor = TikzColor("Maroon0")
Purple0: TikzColor = TikzColor("Purple0")
purple0: TikzColor = TikzColor("Purple0")

__all__ = [
    "AliceBlue",
    "AntiqueWhite",
    "AntiqueWhite1",
    "AntiqueWhite2",
    "AntiqueWhite3",
    "AntiqueWhite4",
    "Apricot",
    "Aqua",
    "Aquamarine",
    "Aquamarine1",
    "Aquamarine2",
    "Aquamarine3",
    "Aquamarine4",
    "Azure",
    "Azure1",
    "Azure2",
    "Azure3",
    "Azure4",
    "Beige",
    "Bisque",
    "Bisque1",
    "Bisque2",
    "Bisque3",
    "Bisque4",
    "Bittersweet",
    "Black",
    "BlanchedAlmond",
    "Blue",
    "Blue1",
    "Blue2",
    "Blue3",
    "Blue4",
    "BlueGreen",
    "BlueViolet",
    "BrickRed",
    "Brown",
    "Brown1",
    "Brown2",
    "Brown3",
    "Brown4",
    "BurlyWood",
    "Burlywood1",
    "Burlywood2",
    "Burlywood3",
    "Burlywood4",
    "BurntOrange",
    "CadetBlue",
    "CadetBlue1",
    "CadetBlue2",
    "CadetBlue3",
    "CadetBlue4",
    "CarnationPink",
    "Cerulean",
    "Chartreuse",
    "Chartreuse1",
    "Chartreuse2",
    "Chartreuse3",
    "Chartreuse4",
    "Chocolate",
    "Chocolate1",
    "Chocolate2",
    "Chocolate3",
    "Chocolate4",
    "ColorInput",
    "Coral",
    "Coral1",
    "Coral2",
    "Coral3",
    "Coral4",
    "CornflowerBlue",
    "Cornsilk",
    "Cornsilk1",
    "Cornsilk2",
    "Cornsilk3",
    "Cornsilk4",
    "Crimson",
    "Cyan",
    "Cyan1",
    "Cyan2",
    "Cyan3",
    "Cyan4",
    "Dandelion",
    "DarkBlue",
    "DarkCyan",
    "DarkGoldenrod",
    "DarkGoldenrod1",
    "DarkGoldenrod2",
    "DarkGoldenrod3",
    "DarkGoldenrod4",
    "DarkGray",
    "DarkGreen",
    "DarkGrey",
    "DarkKhaki",
    "DarkMagenta",
    "DarkOliveGreen",
    "DarkOliveGreen1",
    "DarkOliveGreen2",
    "DarkOliveGreen3",
    "DarkOliveGreen4",
    "DarkOrange",
    "DarkOrange1",
    "DarkOrange2",
    "DarkOrange3",
    "DarkOrange4",
    "DarkOrchid",
    "DarkOrchid1",
    "DarkOrchid2",
    "DarkOrchid3",
    "DarkOrchid4",
    "DarkRed",
    "DarkSalmon",
    "DarkSeaGreen",
    "DarkSeaGreen1",
    "DarkSeaGreen2",
    "DarkSeaGreen3",
    "DarkSeaGreen4",
    "DarkSlateBlue",
    "DarkSlateGray",
    "DarkSlateGray1",
    "DarkSlateGray2",
    "DarkSlateGray3",
    "DarkSlateGray4",
    "DarkSlateGrey",
    "DarkTurquoise",
    "DarkViolet",
    "DeepPink",
    "DeepPink1",
    "DeepPink2",
    "DeepPink3",
    "DeepPink4",
    "DeepSkyBlue",
    "DeepSkyBlue1",
    "DeepSkyBlue2",
    "DeepSkyBlue3",
    "DeepSkyBlue4",
    "DimGray",
    "DimGrey",
    "DodgerBlue",
    "DodgerBlue1",
    "DodgerBlue2",
    "DodgerBlue3",
    "DodgerBlue4",
    "Emerald",
    "FireBrick",
    "Firebrick1",
    "Firebrick2",
    "Firebrick3",
    "Firebrick4",
    "FloralWhite",
    "ForestGreen",
    "Fuchsia",
    "Gainsboro",
    "GhostWhite",
    "Gold",
    "Gold1",
    "Gold2",
    "Gold3",
    "Gold4",
    "Goldenrod",
    "Goldenrod1",
    "Goldenrod2",
    "Goldenrod3",
    "Goldenrod4",
    "Gray",
    "Gray0",
    "Green",
    "Green0",
    "Green1",
    "Green2",
    "Green3",
    "Green4",
    "GreenYellow",
    "Grey",
    "Grey0",
    "Honeydew",
    "Honeydew1",
    "Honeydew2",
    "Honeydew3",
    "Honeydew4",
    "HotPink",
    "HotPink1",
    "HotPink2",
    "HotPink3",
    "HotPink4",
    "IndianRed",
    "IndianRed1",
    "IndianRed2",
    "IndianRed3",
    "IndianRed4",
    "Indigo",
    "Ivory",
    "Ivory1",
    "Ivory2",
    "Ivory3",
    "Ivory4",
    "JungleGreen",
    "Khaki",
    "Khaki1",
    "Khaki2",
    "Khaki3",
    "Khaki4",
    "Lavender",
    "LavenderBlush",
    "LavenderBlush1",
    "LavenderBlush2",
    "LavenderBlush3",
    "LavenderBlush4",
    "LawnGreen",
    "LemonChiffon",
    "LemonChiffon1",
    "LemonChiffon2",
    "LemonChiffon3",
    "LemonChiffon4",
    "LightBlue",
    "LightBlue1",
    "LightBlue2",
    "LightBlue3",
    "LightBlue4",
    "LightCoral",
    "LightCyan",
    "LightCyan1",
    "LightCyan2",
    "LightCyan3",
    "LightCyan4",
    "LightGoldenrod",
    "LightGoldenrod1",
    "LightGoldenrod2",
    "LightGoldenrod3",
    "LightGoldenrod4",
    "LightGoldenrodYellow",
    "LightGray",
    "LightGreen",
    "LightGrey",
    "LightPink",
    "LightPink1",
    "LightPink2",
    "LightPink3",
    "LightPink4",
    "LightSalmon",
    "LightSalmon1",
    "LightSalmon2",
    "LightSalmon3",
    "LightSalmon4",
    "LightSeaGreen",
    "LightSkyBlue",
    "LightSkyBlue1",
    "LightSkyBlue2",
    "LightSkyBlue3",
    "LightSkyBlue4",
    "LightSlateBlue",
    "LightSlateGray",
    "LightSlateGrey",
    "LightSteelBlue",
    "LightSteelBlue1",
    "LightSteelBlue2",
    "LightSteelBlue3",
    "LightSteelBlue4",
    "LightYellow",
    "LightYellow1",
    "LightYellow2",
    "LightYellow3",
    "LightYellow4",
    "Lime",
    "LimeGreen",
    "Linen",
    "Magenta",
    "Magenta1",
    "Magenta2",
    "Magenta3",
    "Magenta4",
    "Mahogany",
    "Maroon",
    "Maroon0",
    "Maroon1",
    "Maroon2",
    "Maroon3",
    "Maroon4",
    "MediumAquamarine",
    "MediumBlue",
    "MediumOrchid",
    "MediumOrchid1",
    "MediumOrchid2",
    "MediumOrchid3",
    "MediumOrchid4",
    "MediumPurple",
    "MediumPurple1",
    "MediumPurple2",
    "MediumPurple3",
    "MediumPurple4",
    "MediumSeaGreen",
    "MediumSlateBlue",
    "MediumSpringGreen",
    "MediumTurquoise",
    "MediumVioletRed",
    "Melon",
    "MidnightBlue",
    "MintCream",
    "MistyRose",
    "MistyRose1",
    "MistyRose2",
    "MistyRose3",
    "MistyRose4",
    "Moccasin",
    "Mulberry",
    "NavajoWhite",
    "NavajoWhite1",
    "NavajoWhite2",
    "NavajoWhite3",
    "NavajoWhite4",
    "Navy",
    "NavyBlue",
    "OldLace",
    "Olive",
    "OliveDrab",
    "OliveDrab1",
    "OliveDrab2",
    "OliveDrab3",
    "OliveDrab4",
    "OliveGreen",
    "Orange",
    "Orange1",
    "Orange2",
    "Orange3",
    "Orange4",
    "OrangeRed",
    "OrangeRed1",
    "OrangeRed2",
    "OrangeRed3",
    "OrangeRed4",
    "Orchid",
    "Orchid1",
    "Orchid2",
    "Orchid3",
    "Orchid4",
    "PaleGoldenrod",
    "PaleGreen",
    "PaleGreen1",
    "PaleGreen2",
    "PaleGreen3",
    "PaleGreen4",
    "PaleTurquoise",
    "PaleTurquoise1",
    "PaleTurquoise2",
    "PaleTurquoise3",
    "PaleTurquoise4",
    "PaleVioletRed",
    "PaleVioletRed1",
    "PaleVioletRed2",
    "PaleVioletRed3",
    "PaleVioletRed4",
    "PapayaWhip",
    "Peach",
    "PeachPuff",
    "PeachPuff1",
    "PeachPuff2",
    "PeachPuff3",
    "PeachPuff4",
    "Periwinkle",
    "Peru",
    "PineGreen",
    "Pink",
    "Pink1",
    "Pink2",
    "Pink3",
    "Pink4",
    "Plum",
    "Plum1",
    "Plum2",
    "Plum3",
    "Plum4",
    "PowderBlue",
    "ProcessBlue",
    "Purple",
    "Purple0",
    "Purple1",
    "Purple2",
    "Purple3",
    "Purple4",
    "RawSienna",
    "Red",
    "Red1",
    "Red2",
    "Red3",
    "Red4",
    "RedOrange",
    "RedViolet",
    "Rhodamine",
    "RosyBrown",
    "RosyBrown1",
    "RosyBrown2",
    "RosyBrown3",
    "RosyBrown4",
    "RoyalBlue",
    "RoyalBlue1",
    "RoyalBlue2",
    "RoyalBlue3",
    "RoyalBlue4",
    "RoyalPurple",
    "RubineRed",
    "SaddleBrown",
    "Salmon",
    "Salmon1",
    "Salmon2",
    "Salmon3",
    "Salmon4",
    "SandyBrown",
    "SeaGreen",
    "SeaGreen1",
    "SeaGreen2",
    "SeaGreen3",
    "SeaGreen4",
    "Seashell",
    "Seashell1",
    "Seashell2",
    "Seashell3",
    "Seashell4",
    "Sepia",
    "Sienna",
    "Sienna1",
    "Sienna2",
    "Sienna3",
    "Sienna4",
    "Silver",
    "SkyBlue",
    "SkyBlue1",
    "SkyBlue2",
    "SkyBlue3",
    "SkyBlue4",
    "SlateBlue",
    "SlateBlue1",
    "SlateBlue2",
    "SlateBlue3",
    "SlateBlue4",
    "SlateGray",
    "SlateGray1",
    "SlateGray2",
    "SlateGray3",
    "SlateGray4",
    "SlateGrey",
    "Snow",
    "Snow1",
    "Snow2",
    "Snow3",
    "Snow4",
    "SpringGreen",
    "SpringGreen1",
    "SpringGreen2",
    "SpringGreen3",
    "SpringGreen4",
    "SteelBlue",
    "SteelBlue1",
    "SteelBlue2",
    "SteelBlue3",
    "SteelBlue4",
    "Tan",
    "Tan1",
    "Tan2",
    "Tan3",
    "Tan4",
    "Teal",
    "TealBlue",
    "Thistle",
    "Thistle1",
    "Thistle2",
    "Thistle3",
    "Thistle4",
    "TikzColor",
    "Tomato",
    "Tomato1",
    "Tomato2",
    "Tomato3",
    "Tomato4",
    "Turquoise",
    "Turquoise1",
    "Turquoise2",
    "Turquoise3",
    "Turquoise4",
    "Violet",
    "VioletRed",
    "VioletRed1",
    "VioletRed2",
    "VioletRed3",
    "VioletRed4",
    "Wheat",
    "Wheat1",
    "Wheat2",
    "Wheat3",
    "Wheat4",
    "White",
    "WhiteSmoke",
    "WildStrawberry",
    "Yellow",
    "Yellow1",
    "Yellow2",
    "Yellow3",
    "Yellow4",
    "YellowGreen",
    "YellowOrange",
    "alice_blue",
    "antique_white",
    "antique_white1",
    "antique_white2",
    "antique_white3",
    "antique_white4",
    "apricot",
    "aqua",
    "aquamarine",
    "aquamarine1",
    "aquamarine2",
    "aquamarine3",
    "aquamarine4",
    "azure",
    "azure1",
    "azure2",
    "azure3",
    "azure4",
    "beige",
    "bisque",
    "bisque1",
    "bisque2",
    "bisque3",
    "bisque4",
    "bittersweet",
    "black",
    "blanched_almond",
    "blue",
    "blue1",
    "blue2",
    "blue3",
    "blue4",
    "blue_green",
    "blue_violet",
    "brick_red",
    "brown",
    "brown1",
    "brown2",
    "brown3",
    "brown4",
    "burly_wood",
    "burlywood1",
    "burlywood2",
    "burlywood3",
    "burlywood4",
    "burnt_orange",
    "cadet_blue",
    "cadet_blue1",
    "cadet_blue2",
    "cadet_blue3",
    "cadet_blue4",
    "carnation_pink",
    "cerulean",
    "chartreuse",
    "chartreuse1",
    "chartreuse2",
    "chartreuse3",
    "chartreuse4",
    "chocolate",
    "chocolate1",
    "chocolate2",
    "chocolate3",
    "chocolate4",
    "coral",
    "coral1",
    "coral2",
    "coral3",
    "coral4",
    "cornflower_blue",
    "cornsilk",
    "cornsilk1",
    "cornsilk2",
    "cornsilk3",
    "cornsilk4",
    "crimson",
    "cyan",
    "cyan1",
    "cyan2",
    "cyan3",
    "cyan4",
    "dandelion",
    "dark_blue",
    "dark_cyan",
    "dark_goldenrod",
    "dark_goldenrod1",
    "dark_goldenrod2",
    "dark_goldenrod3",
    "dark_goldenrod4",
    "dark_gray",
    "dark_green",
    "dark_grey",
    "dark_khaki",
    "dark_magenta",
    "dark_olive_green",
    "dark_olive_green1",
    "dark_olive_green2",
    "dark_olive_green3",
    "dark_olive_green4",
    "dark_orange",
    "dark_orange1",
    "dark_orange2",
    "dark_orange3",
    "dark_orange4",
    "dark_orchid",
    "dark_orchid1",
    "dark_orchid2",
    "dark_orchid3",
    "dark_orchid4",
    "dark_red",
    "dark_salmon",
    "dark_sea_green",
    "dark_sea_green1",
    "dark_sea_green2",
    "dark_sea_green3",
    "dark_sea_green4",
    "dark_slate_blue",
    "dark_slate_gray",
    "dark_slate_gray1",
    "dark_slate_gray2",
    "dark_slate_gray3",
    "dark_slate_gray4",
    "dark_slate_grey",
    "dark_turquoise",
    "dark_violet",
    "darkgray",
    "deep_pink",
    "deep_pink1",
    "deep_pink2",
    "deep_pink3",
    "deep_pink4",
    "deep_sky_blue",
    "deep_sky_blue1",
    "deep_sky_blue2",
    "deep_sky_blue3",
    "deep_sky_blue4",
    "dim_gray",
    "dim_grey",
    "dodger_blue",
    "dodger_blue1",
    "dodger_blue2",
    "dodger_blue3",
    "dodger_blue4",
    "emerald",
    "fire_brick",
    "firebrick1",
    "firebrick2",
    "firebrick3",
    "firebrick4",
    "floral_white",
    "forest_green",
    "fuchsia",
    "gainsboro",
    "ghost_white",
    "gold",
    "gold1",
    "gold2",
    "gold3",
    "gold4",
    "goldenrod",
    "goldenrod1",
    "goldenrod2",
    "goldenrod3",
    "goldenrod4",
    "gray",
    "gray0",
    "green",
    "green0",
    "green1",
    "green2",
    "green3",
    "green4",
    "green_yellow",
    "grey",
    "grey0",
    "honeydew",
    "honeydew1",
    "honeydew2",
    "honeydew3",
    "honeydew4",
    "hot_pink",
    "hot_pink1",
    "hot_pink2",
    "hot_pink3",
    "hot_pink4",
    "indian_red",
    "indian_red1",
    "indian_red2",
    "indian_red3",
    "indian_red4",
    "indigo",
    "ivory",
    "ivory1",
    "ivory2",
    "ivory3",
    "ivory4",
    "jungle_green",
    "khaki",
    "khaki1",
    "khaki2",
    "khaki3",
    "khaki4",
    "lavender",
    "lavender_blush",
    "lavender_blush1",
    "lavender_blush2",
    "lavender_blush3",
    "lavender_blush4",
    "lawn_green",
    "lemon_chiffon",
    "lemon_chiffon1",
    "lemon_chiffon2",
    "lemon_chiffon3",
    "lemon_chiffon4",
    "light_blue",
    "light_blue1",
    "light_blue2",
    "light_blue3",
    "light_blue4",
    "light_coral",
    "light_cyan",
    "light_cyan1",
    "light_cyan2",
    "light_cyan3",
    "light_cyan4",
    "light_goldenrod",
    "light_goldenrod1",
    "light_goldenrod2",
    "light_goldenrod3",
    "light_goldenrod4",
    "light_goldenrod_yellow",
    "light_gray",
    "light_green",
    "light_grey",
    "light_pink",
    "light_pink1",
    "light_pink2",
    "light_pink3",
    "light_pink4",
    "light_salmon",
    "light_salmon1",
    "light_salmon2",
    "light_salmon3",
    "light_salmon4",
    "light_sea_green",
    "light_sky_blue",
    "light_sky_blue1",
    "light_sky_blue2",
    "light_sky_blue3",
    "light_sky_blue4",
    "light_slate_blue",
    "light_slate_gray",
    "light_slate_grey",
    "light_steel_blue",
    "light_steel_blue1",
    "light_steel_blue2",
    "light_steel_blue3",
    "light_steel_blue4",
    "light_yellow",
    "light_yellow1",
    "light_yellow2",
    "light_yellow3",
    "light_yellow4",
    "lightgray",
    "lime",
    "lime_green",
    "linen",
    "magenta",
    "magenta1",
    "magenta2",
    "magenta3",
    "magenta4",
    "mahogany",
    "maroon",
    "maroon0",
    "maroon1",
    "maroon2",
    "maroon3",
    "maroon4",
    "medium_aquamarine",
    "medium_blue",
    "medium_orchid",
    "medium_orchid1",
    "medium_orchid2",
    "medium_orchid3",
    "medium_orchid4",
    "medium_purple",
    "medium_purple1",
    "medium_purple2",
    "medium_purple3",
    "medium_purple4",
    "medium_sea_green",
    "medium_slate_blue",
    "medium_spring_green",
    "medium_turquoise",
    "medium_violet_red",
    "melon",
    "midnight_blue",
    "mint_cream",
    "misty_rose",
    "misty_rose1",
    "misty_rose2",
    "misty_rose3",
    "misty_rose4",
    "moccasin",
    "mulberry",
    "navajo_white",
    "navajo_white1",
    "navajo_white2",
    "navajo_white3",
    "navajo_white4",
    "navy",
    "navy_blue",
    "old_lace",
    "olive",
    "olive_drab",
    "olive_drab1",
    "olive_drab2",
    "olive_drab3",
    "olive_drab4",
    "olive_green",
    "orange",
    "orange1",
    "orange2",
    "orange3",
    "orange4",
    "orange_red",
    "orange_red1",
    "orange_red2",
    "orange_red3",
    "orange_red4",
    "orchid",
    "orchid1",
    "orchid2",
    "orchid3",
    "orchid4",
    "pale_goldenrod",
    "pale_green",
    "pale_green1",
    "pale_green2",
    "pale_green3",
    "pale_green4",
    "pale_turquoise",
    "pale_turquoise1",
    "pale_turquoise2",
    "pale_turquoise3",
    "pale_turquoise4",
    "pale_violet_red",
    "pale_violet_red1",
    "pale_violet_red2",
    "pale_violet_red3",
    "pale_violet_red4",
    "papaya_whip",
    "peach",
    "peach_puff",
    "peach_puff1",
    "peach_puff2",
    "peach_puff3",
    "peach_puff4",
    "periwinkle",
    "peru",
    "pine_green",
    "pink",
    "pink1",
    "pink2",
    "pink3",
    "pink4",
    "plum",
    "plum1",
    "plum2",
    "plum3",
    "plum4",
    "powder_blue",
    "process_blue",
    "purple",
    "purple0",
    "purple1",
    "purple2",
    "purple3",
    "purple4",
    "raw_sienna",
    "red",
    "red1",
    "red2",
    "red3",
    "red4",
    "red_orange",
    "red_violet",
    "rhodamine",
    "rosy_brown",
    "rosy_brown1",
    "rosy_brown2",
    "rosy_brown3",
    "rosy_brown4",
    "royal_blue",
    "royal_blue1",
    "royal_blue2",
    "royal_blue3",
    "royal_blue4",
    "royal_purple",
    "rubine_red",
    "saddle_brown",
    "salmon",
    "salmon1",
    "salmon2",
    "salmon3",
    "salmon4",
    "sandy_brown",
    "sea_green",
    "sea_green1",
    "sea_green2",
    "sea_green3",
    "sea_green4",
    "seashell",
    "seashell1",
    "seashell2",
    "seashell3",
    "seashell4",
    "sepia",
    "sienna",
    "sienna1",
    "sienna2",
    "sienna3",
    "sienna4",
    "silver",
    "sky_blue",
    "sky_blue1",
    "sky_blue2",
    "sky_blue3",
    "sky_blue4",
    "slate_blue",
    "slate_blue1",
    "slate_blue2",
    "slate_blue3",
    "slate_blue4",
    "slate_gray",
    "slate_gray1",
    "slate_gray2",
    "slate_gray3",
    "slate_gray4",
    "slate_grey",
    "snow",
    "snow1",
    "snow2",
    "snow3",
    "snow4",
    "spring_green",
    "spring_green1",
    "spring_green2",
    "spring_green3",
    "spring_green4",
    "steel_blue",
    "steel_blue1",
    "steel_blue2",
    "steel_blue3",
    "steel_blue4",
    "tan",
    "tan1",
    "tan2",
    "tan3",
    "tan4",
    "teal",
    "teal_blue",
    "thistle",
    "thistle1",
    "thistle2",
    "thistle3",
    "thistle4",
    "tomato",
    "tomato1",
    "tomato2",
    "tomato3",
    "tomato4",
    "turquoise",
    "turquoise1",
    "turquoise2",
    "turquoise3",
    "turquoise4",
    "violet",
    "violet_red",
    "violet_red1",
    "violet_red2",
    "violet_red3",
    "violet_red4",
    "wheat",
    "wheat1",
    "wheat2",
    "wheat3",
    "wheat4",
    "white",
    "white_smoke",
    "wild_strawberry",
    "yellow",
    "yellow1",
    "yellow2",
    "yellow3",
    "yellow4",
    "yellow_green",
    "yellow_orange",
]
