import os
import re
import subprocess
import tempfile
from importlib.metadata import version

import fitz

from tikzpics.core.color import Color
from tikzpics.core.coordinate import TikzCoordinate
from tikzpics.core.layer import LayerCollection
from tikzpics.core.loop import Loop
from tikzpics.core.node import Node
from tikzpics.core.path import Path
from tikzpics.core.plot import Plot3D
from tikzpics.core.raw import RawTikz
from tikzpics.core.variable import Variable

line_length = 50
version_string = f"% Tikzfigure generated by tikzpics v{version('tikzpics')}"
version_string += " " * (line_length - len(version_string) - 2) + "%\n"
link_string = "% https://github.com/max-models/tikzpics"
link_string += " " * (line_length - len(link_string) - 2) + "%\n"
line_separator = "% " + "-" * (line_length - 5) + " %\n"
TIKZFIGURE_HEADER = line_separator + version_string + link_string + line_separator


class TikzFigure:
    def __init__(
        self,
        ndim: int = 2,
        label: str | None = None,
        grid: bool = False,
        tikz_code: str | None = None,
        extra_packages: list | None = None,
        document_setup: str | None = None,
        figure_setup: str | None = None,
        figsize: tuple[float, float] = (10, 6),
        caption: str | None = None,
        description: str | None = None,
    ):
        """Initialize the TikzFigure class for creating TikZ figures."""

        self._figsize = figsize
        self._caption = caption
        self._description = description
        self._label = label
        self._grid = grid
        self._tikz_code = tikz_code
        self._figure_setup = figure_setup
        self._extra_packages = extra_packages
        self._document_setup = document_setup
        # Initialize lists to hold Node and Path objects
        # TODO: nodes, paths, layers should have @property and @setter methods
        self._layers = LayerCollection()
        self._variables = []
        self._colors = []
        self._ndim = ndim

        # Counter for unnamed nodes
        self._node_counter = 0

        if self._tikz_code:
            lines = self._tikz_code.split("\n")
            lines = [line.lstrip().rstrip() for line in lines]
            lines = [line for line in lines if line not in ["", "\n"]]
            lines = [line for line in lines if not line[0] == "%"]

            assert lines[0] == "\\begin{tikzpicture}", f"Found: {lines[0]}"
            assert lines[-1] == "\\end{tikzpicture}", f"Found: {lines[-1]}"

            current_layer = 0
            for line in lines[1:-1]:
                # print(line)

                # Match \begin{pgfonlayer}{layer}
                match_pgfdeclarelayer = re.search(r"\\pgfdeclarelayer\{(\d+)\}", line)
                if match_pgfdeclarelayer:
                    layer = match_pgfdeclarelayer.group(1)
                    self.layers.add_layer(layer)
                    # print(f"Layer number: {layer}")

                # Match \begin{pgfonlayer}{layer}
                match_begin_pgfonlayer = re.search(
                    r"\\begin\{pgfonlayer\}\{(\d+)\}",
                    line,
                )
                if match_begin_pgfonlayer:
                    current_layer = match_begin_pgfonlayer.group(1)
                    # print(f'Current layer: {current_layer}')

                # Match \end{pgfonlayer}{layer}
                match_end_pgfonlayer = re.search(r"\\end\{pgfonlayer\}\{(\d+)\}", line)
                if match_end_pgfonlayer:
                    current_layer = 0
                    # print(f'Current layer: {current_layer}')

                # Match \node[attributes] at (x,y) {content};
                match_node = re.search(
                    r"\\node(?:\[([^\]]+)\])? \((\w+)\) at \(([^,]+, [^)]+)\) \{(.*)\};",
                    line,
                )
                if match_node:
                    attributes = match_node.group(1)
                    attributes = [
                        attribute.lstrip().rstrip()
                        for attribute in attributes.split(",")
                    ]
                    attributes = [
                        attribute for attribute in attributes if not attribute == ""
                    ]
                    attributes_dict = dict(attr.split("=") for attr in attributes)
                    node_name = match_node.group(2)
                    coordinates = match_node.group(3)
                    coordinates = [c for c in coordinates.split(",")]
                    coordinates = [c for c in coordinates]
                    coordinates = [c.lstrip().rstrip() for c in coordinates]
                    content = match_node.group(4)
                    # print(f"Attributes: {attributes_dict}")
                    # print(f"Node name: {node_name}")
                    # print(f"Coordinates: {coordinates}")
                    # print(f"Node text: '{node_text}'")
                    # print(coordinates.split(','))

                    self.add_node(
                        x=coordinates[0],
                        y=coordinates[1],
                        label=node_name,
                        layer=current_layer,
                        content=content,
                        **attributes_dict,
                    )

                # Match \draw[attributes] (node1.center) to (node2.center) to (node2.center)...;
                match_draw = re.search(
                    r"\\draw(?:\[([^\]]+)\])? ((?:\(\w+\.*\) to )+\(\w+\.*\));",
                    line,
                )
                if match_draw:
                    attributes = match_draw.group(1)
                    attributes = [
                        attribute.lstrip().rstrip()
                        for attribute in attributes.split(",")
                    ]
                    attributes = [
                        attribute for attribute in attributes if not attribute == ""
                    ]
                    path = match_draw.group(2)
                    nodes = re.findall(r"\((\w+)\.*\)", path)

                    # print(f"Attributes: {attributes}")
                    # print(f"Path: {path}")
                    # print(f"Nodes: {nodes}")
                    self._add_path(nodes, options=attributes, layer=current_layer)

    # ------------------------------------------------------------- #
    # Class methods

    @classmethod
    def from_tikz_code(cls, tikz_code: str, **kwargs):
        """Create a TikzFigure instance from existing TikZ code."""
        return cls(tikz_code=tikz_code, **kwargs)

    # ------------------------------------------------------------- #
    # Public methods

    def add(self, items: list | tuple | Node, layer=0, verbose: bool = False):
        """Add an item to the figure."""
        if not isinstance(items, list | tuple):
            items = [items]

        for item in items:
            if isinstance(item, Node):
                if item.label == "":
                    item._label = f"node{self._node_counter}"
                self._node_counter += 1
                self.layers.add_item(item=item, layer=layer, verbose=verbose)

    def colorlet(
        self,
        name,
        color_spec: str,
        layer: int = 0,
    ) -> Color:
        """Add a colorlet to the figure."""
        color = Color(color_spec=color_spec)

        self._colors.append((name, color))
        return color

    def add_node(
        self,
        x: float | int | str | None = None,
        y: float | int | str | None = None,
        z: float | int | str | None = None,
        label: str | None = None,
        content: str = "",
        layer: int = 0,
        comment: str | None = None,
        options: list | str | None = None,
        verbose: bool = False,
        **kwargs,
    ) -> Node:
        """
        Add a node to the TikZ figure.

        Parameters:
        - x (float): X-coordinate of the node.
        - y (float): Y-coordinate of the node.
        - label (str, optional): Label of the node. If None, a default label will be assigned.
        - content: (str, optional): Content of the node
        - comment: (str, optional): Comment to be added before the node
        - **kwargs: Additional TikZ node options (e.g., shape, color).

        Returns:
        - node (Node): The Node object that was added.
        """
        if options is None:
            options = []

        if isinstance(options, str):
            options = [options]

        if label is None:
            label = f"node{self._node_counter}"
        node = Node(
            x=x,
            y=y,
            z=z,
            label=label,
            layer=layer,
            content=content,
            comment=comment,
            options=options,
            **kwargs,
        )
        self._node_counter += 1
        self.layers.add_item(item=node, layer=layer, verbose=verbose)
        return node

    def add_variable(
        self,
        label: str,
        value: int | float,
        layer: int | None = 0,
        comment: str | None = None,
        verbose: bool = False,
    ):
        """Add a variable to the figure."""
        variable = Variable(
            label=label,
            value=value,
            layer=layer,
            comment=comment,
        )
        self._variables.append(variable)

        # TODO: Allow for special variables in each layer
        # self.layers.add_item(item=variable, layer=layer, verbose=verbose)
        return variable

    def add_raw(
        self,
        tikz_code: str,
        layer: int = 0,
        verbose: bool = False,
    ):
        """Add raw TikZ code to the figure."""
        raw_tikz = RawTikz(tikz_code=tikz_code)

        self.layers.add_item(
            item=raw_tikz,
            layer=layer,
            verbose=verbose,
        )
        return raw_tikz

    def filldraw(
        self,
        nodes: list,
        layer: int = 0,
        comment: str | None = None,
        center=False,
        **kwargs,
    ):
        """Add a filled line or path connecting multiple nodes."""
        path = self._add_path(
            nodes=nodes,
            layer=layer,
            comment=comment,
            center=center,
            tikz_command="filldraw",
            **kwargs,
        )
        return path

    def draw(
        self,
        nodes: list,
        layer: int = 0,
        comment: str | None = None,
        center=False,
        **kwargs,
    ):
        """Add a line or path connecting multiple nodes."""
        path = self._add_path(
            nodes=nodes,
            layer=layer,
            comment=comment,
            center=center,
            tikz_command="draw",
            **kwargs,
        )
        return path

    def plot3d(
        self,
        x: list,
        y: list,
        z: list,
        layer: int = 0,
        comment: str | None = None,
        center=False,
        verbose: bool = False,
        **kwargs,
    ):
        """Add a 3D plot to the figure."""
        plot = Plot3D(
            x=x,
            y=y,
            z=z,
            comment=comment,
            center=center,
            **kwargs,
        )

        self.layers.add_item(item=plot, layer=layer, verbose=verbose)
        return plot

    def add_loop(
        self,
        variable,
        values,
        layer=0,
        comment=None,
        verbose: bool = False,
    ):
        """Add a loop to the figure."""
        loop_obj = Loop(
            variable=variable,
            values=values,
            layer=layer,
            comment=comment,
        )

        self.layers.add_item(item=loop_obj, layer=layer, verbose=verbose)
        return loop_obj

    def generate_tikz(self, use_layers: bool = True, verbose: bool = False) -> str:
        """
        Generate the TikZ script for the figure.

        Returns:
        - tikz_script (str): The TikZ script as a string.
        """
        tikz_script = TIKZFIGURE_HEADER
        tikz_script += "\\begin{tikzpicture}\n"
        if self._figure_setup:
            tikz_script += f"[{self._figure_setup}]\n"

        # Add variables
        if len(self.variables) > 0:
            for variable in self.variables:
                tikz_script += (
                    f"\\pgfmathsetmacro{{\\{variable.label}}}{{{variable.value}}}\n"
                )

        # Add colors
        if len(self.colors) > 0:
            for name, color in self.colors:
                tikz_script += f"\\colorlet{{{name}}}{{{color.color_spec}}}\n"

        # Add 3D axis
        if self.ndim == 3:
            tikz_script += "\\begin{axis}[\n"
            tikz_script += "view={20}{30},\n"
            tikz_script += "axis lines=center,\n"
            tikz_script += "xlabel={$x$},\n"
            tikz_script += "ylabel={$y$},\n"
            tikz_script += "zlabel={$z$},\n"
            tikz_script += "grid=major\n"
            tikz_script += "    ]\n"

        if self.layers.num_layers <= 1:
            use_layers = False

        # TODO: self.layers.layers is a bit clunky
        layers = sorted([str(layer) for layer in self.layers.layers.keys()])
        if use_layers:
            tikz_script += "% Define the layers library\n"
            for layer in layers:
                tikz_script += f"\\pgfdeclarelayer{{{layer}}}\n"
            if len(layers) > 0:
                tikz_script += f"\\pgfsetlayers{{{','.join(layers)}}}\n"

        # Add grid if enabled
        # TODO: Create a Grid class
        if self._grid:
            tikz_script += (
                "    \\draw[step=1cm, gray, very thin] (-10,-10) grid (10,10);\n"
            )
        ordered_layers = []
        buffered_layers = set()

        for key, layer in self.layers.layers.items():
            # layer_order, buffered_layers = update_layer_order(layer, layer_order, buffered_layers)
            reqs = layer.get_reqs()
            if all([r == layer.label for r in reqs]):
                ordered_layers.append(layer)
            elif all([r in [layer.label for layer in ordered_layers] for r in reqs]):
                ordered_layers.append(layer)
            else:
                buffered_layers.add(layer)

            for buffered_layer in buffered_layers:
                buff_reqs = buffered_layer.get_reqs()
                if all(
                    [r in [layer.label for layer in ordered_layers] for r in buff_reqs],
                ):
                    # print("Move layer from buffer")
                    ordered_layers.append(key)
                    buffered_layers.remove(key)
        assert len(buffered_layers) == 0, (
            "Layer order is impossible for layer"
            + f"{[layer.label for layer in buffered_layers]}"
        )
        for layer in ordered_layers:
            tikz_script += layer.generate_tikz(use_layers=use_layers, verbose=verbose)

        if self.ndim == 3:
            tikz_script += "\\end{axis}\n"
        tikz_script += "\\end{tikzpicture}"

        # Wrap in figure environment if necessary
        if self._caption or self._description or self._label:
            figure_env = "\\begin{figure}\n" + tikz_script + "\n"
            if self._caption:
                figure_env += f"    \\caption{{{self._caption}}}\n"
            if self._label:
                figure_env += f"    \\label{{{self._label}}}\n"
            figure_env += "\\end{figure}"
            tikz_script = figure_env
        tikz_script = self._add_tabs(tikz_script)
        return tikz_script

    def generate_standalone(self, verbose: bool = False) -> str:
        """Generate a standalone LaTeX document containing the TikZ figure."""
        tikz_code = self.generate_tikz(verbose=verbose)

        # Create a minimal LaTeX document
        latex_document = (
            "\\documentclass[border=10pt]{standalone}\n"
            "\\usepackage{tikz}\n"
            "\\usepackage{pgfplots}\n"
            "\\pgfplotsset{compat=newest}\n"
            "\\usetikzlibrary{arrows.meta}\n"
        )
        if self._extra_packages:
            for pkg in self._extra_packages:
                latex_document += f"\\usepackage{{{pkg}}}\n"

        if self.document_setup:
            latex_document += f"% Custom document setup\n"
            latex_document += f"{self.document_setup}\n"

        latex_document += f"\\begin{{document}}\n{tikz_code}\n\\end{{document}}"
        return latex_document

    def compile_pdf(self, filename="output.pdf", verbose=False):
        """
        Compile the TikZ script into a PDF using pdflatex.

        Parameters:
        - filename (str): The name of the output PDF file (default is 'output.pdf').

        Notes:
        - Requires 'pdflatex' to be installed and accessible from the command line.
        """
        latex_document = self.generate_standalone()
        if verbose:
            print(latex_document)
        # Use a temporary directory to store the LaTeX files
        with tempfile.TemporaryDirectory() as tempdir:
            tex_file = os.path.join(tempdir, "figure.tex")
            with open(tex_file, "w") as f:
                f.write(latex_document)
            # Run pdflatex
            try:
                # Split the path
                head_tail = os.path.split(os.path.abspath(filename))
                output_directory = head_tail[0]
                jobname = head_tail[1].replace(".pdf", "")
                cmd = [
                    "pdflatex",
                    "-interaction=nonstopmode",
                    "-jobname",
                    f"{jobname}",
                    "-output-directory",
                    f"{output_directory}",
                    tex_file,
                ]
                if verbose:
                    print(f"{cmd =}")
                subprocess.run(
                    cmd,
                    cwd=tempdir,
                    check=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                # Remove .aux and .log files
                os.remove(os.path.abspath(filename).replace(".pdf", ".aux"))
                os.remove(os.path.abspath(filename).replace(".pdf", ".log"))
            except subprocess.CalledProcessError as e:
                print("An error occurred while compiling the LaTeX document:")
                print(e.stderr.decode())
                return

    def savefig(
        self,
        filename: str,
        dpi: int = 300,
        verbose: bool = False,
    ):
        """
        Save the TikZ figure to a file (PDF, PNG, JPG) using pure Python tools.
        """
        ext = os.path.splitext(filename)[1].lower()

        if ext == ".pdf":
            # Direct compile
            self.compile_pdf(filename=filename, verbose=verbose)
        elif ext == ".tikz":
            if verbose:
                print(f"Saving TikZ code to {filename}")
            tikz_code = self.generate_tikz()
            with open(filename, "w") as f:
                f.write(tikz_code)
        elif ext in [".png", ".jpg", ".jpeg"]:
            # Compile to a temporary PDF first
            with tempfile.TemporaryDirectory() as tempdir:
                temp_pdf = os.path.join(tempdir, "temp.pdf")

                if verbose:
                    print(f"Compiling TikZ to temporary PDF: {temp_pdf}")

                self.compile_pdf(filename=temp_pdf, verbose=verbose)

                if verbose:
                    print(f"Converting {temp_pdf} → {filename}")

                # Convert PDF → image
                doc = fitz.open(temp_pdf)
                page = doc[0]
                pix = page.get_pixmap(dpi=dpi)
                pix.save(filename)
                doc.close()
        else:
            raise ValueError(f"Unsupported file format: {ext}")

    def show(
        self,
        width: int | None = None,
        height: int | None = None,
        dpi: int = 300,
        verbose: bool = False,
        backend: str = "matplotlib",
    ):
        """
        Display the TikZ figure.

        In Jupyter notebooks, displays inline.
        In regular Python, opens according to the backend parameter.

        Parameters:
        -----------
        width : int, optional
            Display width in pixels (Jupyter only)
        height : int, optional
            Display height in pixels (Jupyter only)
        verbose : bool
            Print compilation details
        backend : str
            Display backend for non-Jupyter environments.
            Options: "matplotlib" (default), "system", "pillow"
            - "matplotlib": Opens in matplotlib window
            - "system": Opens with system default image viewer
            - "pillow": Opens with PIL/Pillow viewer
        """
        # Skip display in test/headless environments
        if os.environ.get("TIKZPICS_NO_SHOW") == "1" or os.environ.get(
            "PYTEST_CURRENT_TEST"
        ):
            if verbose:
                print("Display suppressed (test/headless mode).")
            return

        # Check if we're in a Jupyter/IPython environment
        try:
            from IPython import get_ipython

            if get_ipython() is not None and "IPKernelApp" in get_ipython().config:
                # We're in Jupyter - use IPython display
                from IPython.display import Image, display

                with tempfile.TemporaryDirectory() as tempdir:
                    temp_pdf = os.path.join(tempdir, "temp.png")
                    self.savefig(filename=temp_pdf, verbose=verbose)
                    display(Image(filename=temp_pdf, width=width, height=height))
                return
        except (ImportError, AttributeError):
            pass

        # Not in Jupyter - use specified backend
        if backend == "matplotlib":
            self._show_matplotlib(dpi=dpi, verbose=verbose)
        elif backend == "system":
            self._show_system(dpi=dpi, verbose=verbose)
        elif backend == "pillow":
            self._show_pillow(dpi=dpi, verbose=verbose)
        else:
            raise ValueError(
                f"Unknown backend '{backend}'. "
                "Options: 'matplotlib', 'system', 'pillow'"
            )

    def _show_matplotlib(self, dpi: int = 300, verbose: bool = False):
        """Show figure using matplotlib."""
        try:
            import matplotlib.image as mpimg
            import matplotlib.pyplot as plt
        except ImportError:
            raise ImportError(
                "matplotlib is required for this backend. "
                "Install with: pip install matplotlib\n"
                "Or use backend='system' or backend='pillow'"
            )

        if verbose:
            print("Using matplotlib backend for display.")

        with tempfile.TemporaryDirectory() as tempdir:
            temp_png = os.path.join(tempdir, "temp.png")
            self.savefig(filename=temp_png, dpi=dpi, verbose=verbose)

            img = mpimg.imread(temp_png)

            # Calculate figure size based on image dimensions
            height_width_ratio = img.shape[0] / img.shape[1]

            fig, ax = plt.subplots(figsize=(10, 10 * height_width_ratio))
            ax.imshow(img)
            ax.axis("off")
            plt.tight_layout(pad=0)
            plt.show()

    def _show_system(self, dpi: int = 300, verbose: bool = False):
        """Show figure using system default image viewer."""
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            temp_path = tmp.name

        try:
            self.savefig(filename=temp_path, dpi=dpi, verbose=verbose)

            # Open with system default viewer
            import platform

            system = platform.system()

            if system == "Darwin":  # macOS
                subprocess.run(["open", temp_path], check=True)
            elif system == "Linux":
                subprocess.run(["xdg-open", temp_path], check=True)
            elif system == "Windows":
                os.startfile(temp_path)
            else:
                print(f"Saved figure to: {temp_path}")
                print("Please open manually (unsupported platform for auto-display)")
        except Exception as e:
            print(f"Could not open figure automatically: {e}")
            print(f"Figure saved to: {temp_path}")

    def _show_pillow(self, dpi: int = 300, verbose: bool = False):
        """Show figure using PIL/Pillow."""
        try:
            from PIL import Image
        except ImportError:
            raise ImportError(
                "Pillow is required for this backend. "
                "Install with: pip install Pillow\n"
                "Or use backend='system' or backend='matplotlib'"
            )

        with tempfile.TemporaryDirectory() as tempdir:
            temp_png = os.path.join(tempdir, "temp.png")
            self.savefig(filename=temp_png, dpi=dpi, verbose=verbose)

            img = Image.open(temp_png)
            img.show()

    # ------------------------------------------------------------- #
    # Private methods

    def _add_path(
        self,
        nodes: list,
        layer: int = 0,
        comment: str | None = None,
        center=False,
        tikz_command="draw",
        verbose=False,
        **kwargs,
    ):
        """
        Add a line or path connecting multiple nodes.

        Parameters:
        - nodes (list of str): List of node names to connect OR list of coordinates
        - **kwargs: Additional TikZ path options (e.g., style, color).

        Examples:
        - add_path(['A', 'B', 'C'], color='blue')
          Connects nodes A -> B -> C with a blue line.
        """
        if not isinstance(nodes, list):
            raise ValueError("nodes parameter must be a list of node names.")

        nodes_cleaned = []

        for node in nodes:
            if isinstance(node, Node):
                nodes_cleaned.append(node)
            elif isinstance(node, str):
                # Find the node by its label
                nodes_cleaned.append(self.layers.get_node(node))
            elif isinstance(node, tuple) or isinstance(node, list):
                node = tuple(node)
                nodes_cleaned.append(TikzCoordinate(*node, layer=layer))
            else:
                raise NotImplementedError(
                    f"{node =}, {type(node) =} is not a valid node type!",
                )

        if verbose:
            print(f"Creating a path with the following nodes {nodes_cleaned}")

        path = Path(
            nodes=nodes_cleaned,
            comment=comment,
            center=center,
            tikz_command=tikz_command,
            **kwargs,
        )
        self.layers.add_item(item=path, layer=layer, verbose=verbose)
        return path

    def _add_tabs(self, tikz_script):
        """Add tabs to the TikZ script for better readability."""
        tikz_script_new = ""
        tab_str = "    "
        num_tabs = 0
        for line in tikz_script.split("\n"):
            if "\\end" in line or "end \\foreach" in line:
                num_tabs = max(num_tabs - 1, 0)
            tikz_script_new += f"{tab_str * num_tabs}{line}\n"
            if "\\begin" in line or "start \\foreach" in line:
                num_tabs += 1
        return tikz_script_new

    # ------------------------------------------------------------- #
    def __repr__(self):
        """Representation of the TikzFigure. Returns the TikZ code."""
        return self.generate_tikz()

    def __str__(self):
        """String representation of the TikzFigure. Returns the TikZ code."""
        return self.generate_tikz()

    # ---------------------------------------------------------------- #
    # Properties

    @property
    def document_setup(self) -> str | None:
        """Custom LaTeX document setup to be included in the preamble of the standalone document."""
        return self._document_setup

    @property
    def extra_packages(self) -> list | None:
        """List of extra LaTeX packages to be included in the preamble of the standalone document."""
        return self._extra_packages

    @property
    def ndim(self):
        """Number of dimensions of the figure."""
        return self._ndim

    @property
    def layers(self) -> LayerCollection:
        """The layers of the figure, stored as a LayerCollection object."""
        return self._layers

    @property
    def colors(self):
        """The colors used in the figure."""
        return self._colors

    @property
    def variables(self) -> list:
        """The variables used in the figure."""
        return self._variables
