"""Build :class:`~tikzfigure.TikzFigure` objects from TikZ source.

Every top-level statement is either *mapped* to a library object
(:class:`Node`, :class:`TikzPath`, :class:`Scope`, ...) or kept verbatim as
:class:`RawTikz`. A mapping is only accepted when the object renders back to
TikZ that is equivalent to the source (same options in the same order, same
coordinates and path operations, ignoring whitespace), so parsing never
silently changes a figure. Each decision is recorded as a
:class:`Diagnostic`, which makes the parse result usable as a coverage report
of what the library can represent.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Callable

from tikzfigure.core.circle import Circle
from tikzfigure.core.coordinate import Coordinate, TikzCoordinate
from tikzfigure.core.loop import Loop
from tikzfigure.core.node import Node
from tikzfigure.core.path import TikzPath
from tikzfigure.core.raw import RawTikz
from tikzfigure.core.rectangle import Rectangle
from tikzfigure.core.scope import Scope
from tikzfigure.parser.lexer import (
    Scanner,
    Statement,
    TikzParseError,
    _read_environment,
    dedent_lines,
    normalize_space,
    split_statements,
    split_top_level,
    strip_comments,
)
from tikzfigure.parser.syntax import (
    Coord,
    Option,
    PathToken,
    canonical_node,
    canonical_path,
    parse_command,
    parse_node_tokens,
    parse_options,
    unbrace_component,
)

if TYPE_CHECKING:
    from tikzfigure.core.figure import TikzFigure


#: Comment lines emitted by :meth:`TikzFigure.generate_tikz` itself.
_GENERATED_COMMENTS = re.compile(
    r"^\s*(Define the layers library|Layer \S+|\{\\end foreach\}|-+\s*%?"
    r"|Tikzfigure generated by .*|https://github\.com/max-models/tikzfigure.*)\s*$"
)
_DRAW_COMMANDS = frozenset(
    {"draw", "fill", "filldraw", "path", "clip", "shade", "shadedraw"}
)
_DEFAULT_PACKAGES = frozenset({"tikz", "pgfplots", "xcolor"})
_IGNORED_PREAMBLE = re.compile(
    r"^\\(documentclass|PassOptionsToPackage|pgfplotsset\{compat=|"
    r"usepgfplotslibrary\{groupplots\}|begin\{document\}|end\{document\})"
)

#: Rank of hoisted definitions in :meth:`TikzFigure.generate_tikz` output.
_HOIST_RANK = {"style": -1, "variable": 0, "function": 1, "color": 2, "layer": 3}


class Unsupported(Exception):
    """Raised by a handler when a statement cannot be mapped faithfully.

    Attributes:
        reason: Short, stable category used to aggregate diagnostics
            (e.g. ``"path operation 'edge'"``). Must not contain
            statement-specific values.
        detail: Optional specifics for humans.
    """

    def __init__(self, reason: str, detail: str | None = None) -> None:
        super().__init__(reason if detail is None else f"{reason}: {detail}")
        self.reason = reason
        self.detail = detail


@dataclass(frozen=True)
class Diagnostic:
    """Outcome of mapping one statement.

    Attributes:
        line: 1-based line of the statement in the parsed source.
        statement: Short identifier such as ``\\draw`` or ``\\begin{axis}``.
        status: ``"mapped"`` or ``"raw"``.
        object_type: Library class the statement became (``"Node"``,
            ``"TikzPath"``, ``"RawTikz"``, ...).
        reason: Why a statement was kept raw (``None`` when mapped).
        detail: Extra information about *reason*.
        source: Whitespace-normalised source text.
    """

    line: int
    statement: str
    status: str
    object_type: str
    reason: str | None = None
    detail: str | None = None
    source: str = ""

    @property
    def mapped(self) -> bool:
        return self.status == "mapped"

    def __str__(self) -> str:
        if self.mapped:
            return f"line {self.line}: {self.statement} -> {self.object_type}"
        why = self.reason if self.detail is None else f"{self.reason} ({self.detail})"
        return f"line {self.line}: {self.statement} kept as raw TikZ: {why}"


@dataclass
class ParseResult:
    """A parsed figure together with per-statement diagnostics."""

    figure: TikzFigure
    diagnostics: list[Diagnostic] = field(default_factory=list)

    @property
    def mapped(self) -> list[Diagnostic]:
        return [d for d in self.diagnostics if d.mapped]

    @property
    def raw(self) -> list[Diagnostic]:
        return [d for d in self.diagnostics if not d.mapped]

    @property
    def coverage(self) -> float:
        """Fraction of statements mapped to library objects (1.0 if empty)."""
        if not self.diagnostics:
            return 1.0
        return len(self.mapped) / len(self.diagnostics)

    def unsupported_reasons(self) -> Counter[str]:
        """Count of raw-fallback reasons, most common first."""
        return Counter(d.reason or "unknown" for d in self.raw)

    def summary(self) -> str:
        lines = [
            f"{len(self.mapped)}/{len(self.diagnostics)} statements mapped "
            f"({self.coverage:.0%})"
        ]
        lines.extend(f"  {d}" for d in self.raw)
        return "\n".join(lines)


# ---------------------------------------------------------------------- #
# Helpers


def to_number(text: str) -> int | float | str:
    """Convert *text* to ``int``/``float`` only if it round-trips exactly."""
    if re.fullmatch(r"-?\d+", text) and str(int(text)) == text:
        return int(text)
    if re.fullmatch(r"-?\d+\.\d+", text) and repr(float(text)) == text:
        return float(text)
    return text


def _component(text: str, keep_complex_braces: bool) -> int | float | str:
    inner = unbrace_component(text)
    if (
        keep_complex_braces
        and inner != text.strip()
        and re.search(r"[,()\[\]:]", inner)
    ):
        return text.strip()
    return to_number(inner)


def _cartesian(coord: Coord, keep_complex_braces: bool) -> tuple[Any, ...]:
    if coord.prefix:
        raise Unsupported("relative coordinate", f"{coord.prefix}({coord.inner})")
    kind = coord.kind
    if kind != "cartesian":
        raise Unsupported(f"{kind} coordinate", coord.inner)
    return tuple(_component(p, keep_complex_braces) for p in coord.components)


def split_options(
    options: list[Option] | tuple[Option, ...],
    reserved: frozenset[str] = frozenset(),
    structured: bool = True,
) -> tuple[list[str], dict[str, Any]]:
    """Split parsed options into ``options=[...]`` and keyword arguments.

    Keyword arguments are only used when rendering them keeps the original
    order (all flags first, then unique ``key=value`` pairs whose keys map
    cleanly to Python identifiers-with-spaces). Otherwise every option is
    returned verbatim as a flag string, which always renders identically.
    """
    raw = [o.raw for o in options]
    if not structured:
        return raw, {}
    flags: list[str] = []
    kwargs: dict[str, Any] = {}
    seen_key = False
    for option in options:
        if option.key is None:
            if seen_key:
                return raw, {}
            flags.append(option.raw)
            continue
        seen_key = True
        key = option.key.replace(" ", "_")
        if (
            "_" in option.key
            or key in reserved
            or key in kwargs
            or not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", key)
        ):
            return raw, {}
        kwargs[key] = option.value or ""
    return flags, kwargs


class _Sink:
    """Where mapped objects go: a figure layer or a Scope/Loop body."""

    def __init__(
        self,
        figure: TikzFigure,
        container: Scope | Loop | None = None,
        layer: int = 0,
    ) -> None:
        self.figure = figure
        self.container = container
        self.layer = layer

    @property
    def top_level(self) -> bool:
        return self.container is None

    def resolve(self, label: str) -> Node | Coordinate:
        if self.container is not None:
            return self.container.get_node(label)
        return self.figure.layers.get_node(label)

    def add(self, item: Any) -> None:
        if self.container is not None:
            self.container.items.append(item)
        else:
            self.figure.layers.add_item(item=item, layer=self.layer)

    def add_node(self, node: Node) -> None:
        if self.container is not None:
            self.container.add_node(node)
        else:
            self.figure.add_node(node)


def _rendered_statement(item: Any) -> Statement:
    statements = [s for s in split_statements(item.to_tikz()) if s.kind != "comment"]
    if len(statements) != 1:
        raise Unsupported("lossy mapping", "rendered to multiple statements")
    return statements[0]


# ---------------------------------------------------------------------- #
# Builder


class TikzBuilder:
    """Populate a :class:`TikzFigure` from TikZ source."""

    def __init__(self, figure: TikzFigure) -> None:
        self.figure = figure
        self.diagnostics: list[Diagnostic] = []
        self._hoist_rank = -1
        self._hoisting = True
        self._declared_layers: list[int] = []

    # -------------------------------------------------------------- #
    # Entry point

    def load(self, source: str) -> ParseResult:
        masked = _mask_comments(source)
        begin = re.search(r"\\begin\s*\{tikzpicture\}", masked)
        if begin is None:
            raise TikzParseError("no \\begin{tikzpicture} environment found")

        preamble = source[: begin.start()]
        if "\\documentclass" in masked[: begin.start()]:
            self._load_preamble(preamble)

        scanner = Scanner(source, pos=begin.end())
        after_begin = scanner.pos
        scanner.skip_whitespace()
        picture_options: str | None = None
        if scanner.peek() == "[":
            picture_options = scanner.read_group("[")
        else:
            scanner.pos = after_begin
        body_start = scanner.pos
        _read_environment(scanner, "tikzpicture")
        end_match = list(
            re.finditer(r"\\end\s*\{tikzpicture\}", source[body_start : scanner.pos])
        )[-1]
        body = source[body_start : body_start + end_match.start()]
        trailer = masked[scanner.pos :]

        if picture_options is not None:
            self._load_picture_options(picture_options)

        label = re.search(r"\\label\s*\{([^}]*)\}", trailer)
        if label and self.figure._label is None and "\\begin{figure" in masked:
            self.figure._label = label.group(1)

        self._reserve_auto_labels(body)
        line_offset = source.count("\n", 0, body_start)
        self._build(split_statements(body, line_offset=line_offset), _Sink(self.figure))
        for declared in self._declared_layers:
            # Declared but never used: keep the layer so it is declared again.
            self.figure.layers.add_layer(declared)

        extra = re.search(r"\\begin\s*\{tikzpicture\}", trailer)
        if extra:
            self.diagnostics.append(
                Diagnostic(
                    line=source.count("\n", 0, scanner.pos + extra.start()) + 1,
                    statement="\\begin{tikzpicture}",
                    status="raw",
                    object_type="ignored",
                    reason="additional tikzpicture ignored",
                )
            )
        return ParseResult(self.figure, self.diagnostics)

    # -------------------------------------------------------------- #
    # Document-level pieces

    def _load_preamble(self, preamble: str) -> None:
        extra_setup: list[str] = []
        preamble = strip_comments(preamble)
        begin_document = re.search(r"\\begin\s*\{document\}", preamble)
        if begin_document is not None:
            preamble = preamble[: begin_document.start()]
        for statement in split_statements(preamble):
            text = normalize_space(statement.text)
            if statement.kind == "comment" or not text:
                continue
            if _IGNORED_PREAMBLE.match(text):
                continue
            libs = re.fullmatch(r"\\usetikzlibrary\s*\{([^}]*)\}", text)
            if libs:
                names = [n.strip() for n in libs.group(1).split(",") if n.strip()]
                self.figure.usetikzlibrary(*names)
                continue
            pkg = re.fullmatch(r"\\usepackage\s*\{([^}]*)\}", text)
            if pkg:
                for name in (n.strip() for n in pkg.group(1).split(",")):
                    if name and name not in _DEFAULT_PACKAGES:
                        self.figure.add_package(name)
                continue
            extra_setup.append(dedent_lines(statement.text))
        if extra_setup:
            existing = self.figure._document_setup
            setup = "\n".join(extra_setup)
            self.figure._document_setup = f"{existing}\n{setup}" if existing else setup

    def _load_picture_options(self, inner: str) -> None:
        """Map ``name/.style={...}`` picture options to named styles.

        tikzfigure renders ``figure_setup`` before named styles, so styles are
        only extracted when they already come last; everything else stays in
        ``figure_setup`` verbatim.
        """
        figure = self.figure
        options = parse_options(inner)
        raw = [o.raw for o in options]
        styles = [_style_definition(o) for o in options]
        first = next((i for i, s in enumerate(styles) if s is not None), len(options))
        mappable = (
            first < len(options)
            and all(s is not None for s in styles[first:])
            and not figure._figure_setup
            and not figure._named_styles
        )
        if not mappable:
            figure._append_figure_setup_items(raw)
            return
        figure._append_figure_setup_items(raw[:first])
        for style in styles[first:]:
            assert style is not None
            name, flags, kwargs = style
            figure.add_style(name, options=flags or None, **kwargs)
        rendered = figure._render_figure_option_block().strip()[1:-1]
        if [o.canonical for o in parse_options(rendered)] != [
            o.canonical for o in options
        ]:
            figure._figure_setup = None
            figure._named_styles = []
            figure._append_figure_setup_items(raw)

    def _reserve_auto_labels(self, body: str) -> None:
        """Keep auto-generated ``node<N>`` labels clear of labels in *body*."""
        for match in re.finditer(r"\(\s*node(\d+)\s*[.)]", body):
            self.figure._sync_node_counter_from_label(f"node{match.group(1)}")

    # -------------------------------------------------------------- #
    # Statement dispatch

    def _build(self, statements: list[Statement], sink: _Sink) -> None:
        for statement in statements:
            if statement.kind == "comment":
                comment = statement.text[1:]
                if not _GENERATED_COMMENTS.match(comment):
                    sink.add(RawTikz(statement.text.rstrip()))
                continue
            comments = [
                c for c in statement.comments if not _GENERATED_COMMENTS.match(c)
            ]
            self._build_statement(statement, sink, comments)

    def _handler(self, statement: Statement) -> Callable[..., str] | None:
        if statement.kind == "environment":
            return {
                "scope": self._build_scope,
                "pgfonlayer": self._build_pgfonlayer,
            }.get(statement.name)
        if statement.kind == "foreach":
            return self._build_foreach
        if statement.kind != "command":
            return None
        if statement.name in _DRAW_COMMANDS:
            return self._build_path
        return {
            "node": self._build_node,
            "coordinate": self._build_coordinate,
            "pgfmathsetmacro": self._build_variable,
            "colorlet": self._build_colorlet,
            "pgfkeys": self._build_function,
            "tikzset": self._build_tikzset,
            "pgfdeclarelayer": self._build_layer_declaration,
            "pgfsetlayers": self._build_layer_order,
        }.get(statement.name)

    def _build_statement(
        self, statement: Statement, sink: _Sink, comments: list[str]
    ) -> None:
        handler = self._handler(statement)
        # Only the comment line touching a statement becomes its comment.
        leading, comment = (
            (comments[:-1], comments[-1].strip()) if comments else ([], None)
        )
        for extra in leading:
            sink.add(RawTikz(f"%{extra}"))
        try:
            if handler is None:
                if statement.kind == "environment":
                    raise Unsupported(f"environment '{statement.name}'")
                if statement.kind == "command":
                    raise Unsupported(f"command '\\{statement.name}'")
                raise Unsupported("unrecognised text")
            object_type = handler(statement, sink, comment)
        except Unsupported as exc:
            self._hoisting = False
            code = dedent_lines(statement.text)
            prefix = f"%{comments[-1]}\n" if comments else ""
            sink.add(RawTikz(prefix + code))
            self._record(statement, "raw", "RawTikz", exc.reason, exc.detail)
            return
        if object_type != "PgfOnLayer":
            self._record(statement, "mapped", object_type)

    def _record(
        self,
        statement: Statement,
        status: str,
        object_type: str,
        reason: str | None = None,
        detail: str | None = None,
    ) -> None:
        self.diagnostics.append(
            Diagnostic(
                line=statement.line,
                statement=statement.label,
                status=status,
                object_type=object_type,
                reason=reason,
                detail=detail,
                source=normalize_space(strip_comments(statement.text)),
            )
        )

    def _hoist(self, kind: str, sink: _Sink) -> None:
        """Allow a definition that the generator emits before the body."""
        if not sink.top_level:
            raise Unsupported(f"{kind} definition inside scope or loop")
        rank = _HOIST_RANK[kind]
        if not self._hoisting or rank < self._hoist_rank:
            raise Unsupported(
                f"{kind} definition would be reordered",
                "tikzfigure emits it before earlier statements",
            )
        self._hoist_rank = max(self._hoist_rank, rank)

    def _placed(self) -> None:
        """Mark that body content was emitted; later definitions stay raw."""
        self._hoisting = False

    # -------------------------------------------------------------- #
    # Paths, nodes, coordinates

    def _structured_attempts(
        self, build: Callable[[bool], Any], expected: Any, render: Callable[[Any], Any]
    ) -> Any:
        """Build with keyword options, falling back to verbatim options."""
        for structured in (True, False):
            try:
                item = build(structured)
            except (TypeError, ValueError) as exc:
                if structured:
                    continue
                raise Unsupported("rejected by library", str(exc)) from exc
            if render(item) == expected:
                return item
        raise Unsupported("lossy mapping")

    def _build_path(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        syntax = parse_command(statement.text)
        tokens = syntax.tokens
        options: list[Option] = []
        i = 0
        while i < len(tokens) and tokens[i].kind == "options":
            options.extend(tokens[i].options)
            i += 1
        body = tokens[i:]
        expected = canonical_path(
            ([PathToken("options", options=tuple(options))] if options else []) + body
        )

        def render(item: Any) -> Any:
            rendered = parse_command(_rendered_statement(item).text)
            if rendered.name != syntax.name:
                return None
            return canonical_path(rendered.tokens)

        shape = _simple_shape(body)
        if shape is not None:
            kind, coords = shape
            cls: Any = Circle if kind == "circle" else Rectangle

            def build_shape(structured: bool) -> Any:
                flags, kwargs = split_options(options, _SHAPE_RESERVED, structured)
                if kind == "circle":
                    radius = to_number(coords[1].inner)
                    positional: dict[str, Any] = {
                        "center": _cartesian(coords[0], False),
                        "radius": radius,
                    }
                else:
                    # TikzCoordinate.to_tikz() wraps components in braces.
                    positional = {
                        "corner1": _cartesian(coords[0], False),
                        "corner2": _cartesian(coords[1], False),
                    }
                return cls(
                    **positional,
                    comment=comment,
                    layer=sink.layer,
                    options=flags,
                    tikz_command=syntax.name,
                    **kwargs,
                )

            item = self._structured_attempts(build_shape, expected, render)
            sink.add(item)
            self._placed()
            return str(cls.__name__)

        waypoints, anchors, segments, cycle = self._path_waypoints(body, sink)

        def build(structured: bool) -> TikzPath:
            flags, kwargs = split_options(options, _PATH_RESERVED, structured)
            return TikzPath(
                nodes=waypoints,
                cycle=cycle,
                comment=comment,
                # Mirror TikzFigure._add_path, which leaves the path's own
                # layer at 0 and records the layer through LayerCollection.
                layer=sink.layer if sink.container is not None else 0,
                node_anchors=anchors if any(a is not None for a in anchors) else None,
                segment_options=(
                    segments if any(s is not None for s in segments) else None
                ),
                options=flags,
                tikz_command=syntax.name,
                **kwargs,
            )

        path = self._structured_attempts(build, expected, render)
        sink.add(path)
        self._placed()
        return "TikzPath"

    def _waypoint(self, token: PathToken, sink: _Sink) -> tuple[Any, str | None]:
        if token.kind != "coord":
            raise Unsupported("path element", token.text or token.kind)
        coord = token.coord
        assert coord is not None
        if coord.kind == "named" and not coord.prefix and coord.inner:
            try:
                return sink.resolve(coord.name), coord.anchor
            except ValueError as exc:
                raise Unsupported("reference to undefined node", coord.name) from exc
        values = _cartesian(coord, keep_complex_braces=True)
        return TikzCoordinate(values, layer=sink.layer), None

    def _path_waypoints(
        self, tokens: list[PathToken], sink: _Sink
    ) -> tuple[list[Any], list[str | None], list[Any], bool]:
        if not tokens:
            raise Unsupported("empty path")
        first, anchor = self._waypoint(tokens[0], sink)
        waypoints, anchors = [first], [anchor]
        segments: list[Any] = []
        cycle = False
        i = 1
        n = len(tokens)
        while i < n:
            token = tokens[i]
            segment: dict[str, Any] = {}
            consumes_target = True
            if token.kind == "op" and token.text in ("--", "|-", "-|"):
                if token.text == "--" and i + 1 < n and tokens[i + 1].is_word("cycle"):
                    if i + 2 != n:
                        raise Unsupported("path continues after cycle")
                    cycle = True
                    break
                segment["connector"] = token.text
                i += 1
            elif token.is_word("sin", "cos"):
                segment["connector"] = token.text
                i += 1
            elif token.is_word("to"):
                i += 1
                if i < n and tokens[i].kind == "options":
                    segment["options"] = [o.raw for o in tokens[i].options]
                    i += 1
            elif token.is_word("arc"):
                i += 1
                if i >= n or tokens[i].kind != "options":
                    raise Unsupported("arc without option syntax")
                segment["connector"] = "arc"
                segment["options"] = [o.raw for o in tokens[i].options]
                consumes_target = False
                i += 1
            elif token.kind in ("word", "op"):
                raise Unsupported(f"path operation '{token.text}'")
            elif token.kind == "options":
                raise Unsupported("options in the middle of a path")
            else:
                raise Unsupported("path element", token.text or token.kind)

            if i < n and tokens[i].is_word("node"):
                i += 1
                node_options: list[str] = []
                while i < n and tokens[i].kind == "options":
                    node_options.extend(o.raw for o in tokens[i].options)
                    i += 1
                if i >= n or tokens[i].kind != "group":
                    raise Unsupported("named or positioned inline node")
                node_spec: dict[str, Any] = {"content": tokens[i].text}
                if node_options:
                    node_spec["options"] = node_options
                segment["node"] = node_spec
                i += 1

            if consumes_target:
                if i >= n:
                    raise Unsupported("path ends with an operation")
                waypoint, anchor = self._waypoint(tokens[i], sink)
                waypoints.append(waypoint)
                anchors.append(anchor)
                i += 1
            segments.append(segment or None)
        return waypoints, anchors, segments, cycle

    def _build_node(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        syntax = parse_command(statement.text)
        node_syntax = parse_node_tokens(syntax.tokens)
        if node_syntax is None:
            raise Unsupported(
                "node syntax", "expected [options] (name) at (x, y) {text}"
            )
        if node_syntax.rest:
            raise Unsupported(
                f"operation after node text '{node_syntax.rest[0].text or node_syntax.rest[0].kind}'"
            )
        if node_syntax.name and "." in node_syntax.name:
            raise Unsupported("node name with anchor")
        position: tuple[Any, ...] = ()
        if node_syntax.at is not None:
            position = _cartesian(node_syntax.at, keep_complex_braces=False)
            if len(position) != 2:
                raise Unsupported("3-D node position")
        has_name = bool(node_syntax.name)
        expected = canonical_node(node_syntax, include_name=has_name)

        def render(item: Node) -> Any:
            rendered = parse_command(_rendered_statement(item).text)
            parsed = parse_node_tokens(rendered.tokens)
            return None if parsed is None else canonical_node(parsed, has_name)

        def build(structured: bool) -> Node:
            flags, kwargs = split_options(
                node_syntax.options, _NODE_RESERVED, structured
            )
            return Node(
                position or None,
                label=node_syntax.name or "",
                content=node_syntax.content,
                comment=comment,
                layer=sink.layer,
                options=flags,
                **kwargs,
            )

        node = self._structured_attempts(build, expected, render)
        # Unnamed top-level nodes get an auto ``node<N>`` label from the figure.
        sink.add_node(node)
        self._placed()
        return "Node"

    def _build_coordinate(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        tokens = parse_command(statement.text).tokens
        if (
            len(tokens) != 3
            or tokens[0].kind != "coord"
            or not tokens[1].is_word("at")
            or tokens[2].kind != "coord"
        ):
            raise Unsupported("coordinate syntax", "expected (name) at (position)")
        name_coord, at = tokens[0].coord, tokens[2].coord
        assert name_coord is not None and at is not None
        if name_coord.kind != "named" or not name_coord.inner or name_coord.anchor:
            raise Unsupported("coordinate syntax", "invalid coordinate name")
        if at.prefix:
            raise Unsupported("relative coordinate", at.inner)
        if at.kind == "cartesian" and len(at.components) == 2:
            x, y = _cartesian(at, keep_complex_braces=False)
            item = Coordinate(
                label=name_coord.inner, x=x, y=y, layer=sink.layer, comment=comment
            )
        else:
            item = Coordinate(
                label=name_coord.inner, at=at.inner, layer=sink.layer, comment=comment
            )
        rendered = parse_command(_rendered_statement(item).text).tokens
        if canonical_path(rendered) != canonical_path(tokens):
            raise Unsupported("lossy mapping")
        sink.add(item)
        self._placed()
        return "Coordinate"

    # -------------------------------------------------------------- #
    # Definitions emitted before the body

    def _macro_arguments(self, statement: Statement) -> list[str]:
        scanner = Scanner(strip_comments(statement.text).strip())
        scanner.read_control_word()
        args: list[str] = []
        while True:
            scanner.skip_whitespace()
            if scanner.eof():
                return args
            if scanner.peek() != "{":
                raise Unsupported(f"optional arguments to '\\{statement.name}'")
            args.append(scanner.read_group("{").strip())

    def _build_variable(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        args = self._macro_arguments(statement)
        if len(args) != 2 or not re.fullmatch(r"\\[A-Za-z]+", args[0]):
            raise Unsupported("variable syntax")
        if comment is not None:
            raise Unsupported("comment on variable definition")
        self._hoist("variable", sink)
        self.figure.add_variable(args[0][1:], to_number(normalize_space(args[1])))
        return "Variable"

    def _build_colorlet(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        args = self._macro_arguments(statement)
        if len(args) != 2 or not args[0]:
            raise Unsupported("colorlet syntax")
        if comment is not None:
            raise Unsupported("comment on color definition")
        self._hoist("color", sink)
        self.figure.colorlet(args[0], normalize_space(args[1]))
        return "Color"

    def _build_function(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        args = self._macro_arguments(statement)
        match = (
            re.fullmatch(
                r"/pgf/declare function\s*=\s*\{\s*([A-Za-z][A-Za-z0-9]*)\s*"
                r"\(([^)]*)\)\s*=\s*(.+?);\s*\}",
                normalize_space(args[0]),
            )
            if len(args) == 1
            else None
        )
        if match is None:
            raise Unsupported("pgfkeys usage other than a single declare function")
        params = [p.strip() for p in match.group(2).split(",") if p.strip()]
        if not all(re.fullmatch(r"\\[A-Za-z]+", p) for p in params):
            raise Unsupported("declare function syntax")
        self._hoist("function", sink)
        self.figure.declare_function(
            match.group(1), params, match.group(3).strip(), comment=comment
        )
        return "DeclaredFunction"

    def _build_tikzset(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        args = self._macro_arguments(statement)
        if len(args) != 1:
            raise Unsupported("tikzset syntax")
        styles = [_style_definition(o) for o in parse_options(args[0])]
        existing = {s["name"] for s in self.figure._named_styles}
        if not styles or any(s is None for s in styles):
            raise Unsupported("tikzset with keys other than /.style")
        if comment is not None:
            raise Unsupported("comment on style definition")
        if any(s[0] in existing for s in styles if s) or self.figure._figure_setup:
            raise Unsupported("style would change position relative to picture options")
        self._hoist("style", sink)
        for style in styles:
            assert style is not None
            name, flags, kwargs = style
            self.figure.add_style(name, options=flags or None, **kwargs)
        return "TikzStyle"

    def _build_layer_declaration(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        args = self._macro_arguments(statement)
        if len(args) != 1 or not re.fullmatch(r"-?\d+", args[0]):
            raise Unsupported("named pgf layer")
        self._hoist("layer", sink)
        # Created on first use instead of here: layer creation order decides
        # the order of the generated pgfonlayer blocks, so creating layers
        # now would reorder them by declaration.
        self._declared_layers.append(int(args[0]))
        return "PgfLayer"

    def _build_layer_order(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        args = self._macro_arguments(statement)
        names = [n.strip() for n in args[0].split(",")] if len(args) == 1 else []
        if not names or not all(re.fullmatch(r"-?\d+", n) for n in names):
            raise Unsupported("named pgf layer")
        if names != sorted(names):
            raise Unsupported("custom pgf layer order")
        self._hoist("layer", sink)
        return "PgfLayer"

    # -------------------------------------------------------------- #
    # Containers

    def _environment_parts(self, statement: Statement) -> tuple[str | None, str, int]:
        """Return ``(options, body, body_line_offset)`` for an environment."""
        text = statement.text
        scanner = Scanner(text)
        scanner.read_control_word()
        scanner.skip_whitespace()
        scanner.read_group("{")
        args_end = scanner.pos
        scanner.skip_whitespace()
        options = None
        if scanner.peek() == "[":
            options = scanner.read_group("[")
        else:
            scanner.pos = args_end
        end = list(
            re.finditer(r"\\end\s*\{" + re.escape(statement.name) + r"\}", text)
        )[-1]
        body = text[scanner.pos : end.start()]
        return options, body, statement.line - 1 + text.count("\n", 0, scanner.pos)

    def _build_scope(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        options_text, body, offset = self._environment_parts(statement)
        options = parse_options(options_text or "")
        expected = [o.canonical for o in options]

        def build(structured: bool) -> Scope:
            flags, kwargs = split_options(options, _SCOPE_RESERVED, structured)
            return Scope(
                comment=comment,
                layer=sink.layer,
                options=flags,
                node_resolver=sink.resolve,
                library_loader=self.figure.usetikzlibrary,
                **kwargs,
            )

        scope = self._structured_attempts(
            build,
            expected,
            lambda s: [o.canonical for o in parse_options(s.tikz_options())],
        )
        self._attach(scope, sink)
        self._placed()
        self._build(
            split_statements(body, line_offset=offset),
            _Sink(self.figure, scope, sink.layer),
        )
        return "Scope"

    def _build_foreach(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        text = statement.text
        scanner = Scanner(text)
        scanner.read_control_word()
        scanner.skip_space_and_comments()
        variable = scanner.read_control_word()
        scanner.skip_space_and_comments()
        if (
            variable is None
            or not re.fullmatch(r"[A-Za-z]+", variable)
            or not re.match(r"in\b", text[scanner.pos :])
        ):
            raise Unsupported("foreach with options or multiple variables")
        scanner.pos += 2
        scanner.skip_space_and_comments()
        if scanner.peek() != "{":
            raise Unsupported("foreach over a macro list")
        values_text = strip_comments(scanner.read_group("{"))
        scanner.skip_space_and_comments()
        if scanner.peek() != "{":
            raise Unsupported("foreach without braced body")
        body_start = scanner.pos + 1
        body = scanner.read_group("{")
        scanner.skip_space_and_comments()
        if not scanner.eof():
            raise Unsupported("foreach syntax")

        values = [
            to_number(normalize_space(v)) for v in split_top_level(values_text, ",")
        ]
        values = [v for v in values if v != ""]
        loop = Loop(
            variable=variable,
            values=values,
            layer=sink.layer,
            comment=comment,
            node_resolver=sink.resolve,
            library_loader=self.figure.usetikzlibrary,
        )
        rendered_values = [
            normalize_space(v) for v in split_top_level(loop._render_values(), ",")
        ]
        if rendered_values != [str(v) for v in values]:
            raise Unsupported("lossy mapping")
        self._attach(loop, sink)
        self._placed()
        offset = statement.line - 1 + text.count("\n", 0, body_start)
        self._build(
            split_statements(body, line_offset=offset),
            _Sink(self.figure, loop, sink.layer),
        )
        return "Loop"

    def _attach(self, container: Scope | Loop, sink: _Sink) -> None:
        if sink.container is None:
            self.figure._attach_container_callbacks(container)
        else:
            container._enter_callback = sink.container._enter_callback
            container._exit_callback = sink.container._exit_callback
        sink.add(container)

    def _build_pgfonlayer(
        self, statement: Statement, sink: _Sink, comment: str | None
    ) -> str:
        if not sink.top_level:
            raise Unsupported("pgfonlayer inside scope or loop")
        text = statement.text
        name = re.match(r"\\begin\s*\{pgfonlayer\}\s*\{([^}]*)\}", text)
        if name is None or not re.fullmatch(r"-?\d+", name.group(1).strip()):
            raise Unsupported("named pgf layer")
        body_start = name.end()
        end = list(re.finditer(r"\\end\s*\{pgfonlayer\}", text))[-1]
        body = text[body_start : end.start()]
        offset = statement.line - 1 + text.count("\n", 0, body_start)
        layer = int(name.group(1))
        self.figure.layers.add_layer(layer)
        if comment is not None:
            self.figure.layers.add_item(RawTikz(f"% {comment}"), layer=layer)
        self._placed()
        self._build(
            split_statements(body, line_offset=offset), _Sink(self.figure, layer=layer)
        )
        return "PgfOnLayer"


_NODE_RESERVED = frozenset(
    {"x", "y", "z", "label", "content", "comment", "layer", "options", "kwargs", "self"}
)
_PATH_RESERVED = frozenset(
    {
        "nodes",
        "cycle",
        "label",
        "comment",
        "layer",
        "center",
        "node_anchors",
        "segment_options",
        "options",
        "tikz_command",
        "self",
    }
)
_SHAPE_RESERVED = frozenset(
    {
        "center",
        "radius",
        "corner1",
        "corner2",
        "label",
        "comment",
        "layer",
        "options",
        "tikz_command",
        "self",
    }
)
_SCOPE_RESERVED = frozenset(
    {"label", "comment", "layer", "options", "node_resolver", "library_loader", "self"}
)


def _style_definition(option: Option) -> tuple[str, list[str], dict[str, str]] | None:
    """Return ``(name, flags, kwargs)`` for a ``name/.style={...}`` option."""
    if option.key is None or not option.key.endswith("/.style"):
        return None
    value = (option.value or "").strip()
    if not (value.startswith("{") and value.endswith("}")):
        return None
    name = option.key[: -len("/.style")].strip()
    if not name or "/" in name:
        return None
    inner = parse_options(value[1:-1])
    flags, kwargs = split_options(inner)
    rendered = [f"{k.replace('_', ' ')}={v}" for k, v in kwargs.items()]
    if [normalize_space(x) for x in flags + rendered] != [o.canonical for o in inner]:
        return None
    return name, flags, kwargs


def _simple_shape(tokens: list[PathToken]) -> tuple[str, list[Coord]] | None:
    """Detect ``(c) circle (r)`` and ``(a) rectangle (b)`` paths."""
    if (
        len(tokens) == 3
        and tokens[0].kind == "coord"
        and tokens[2].kind == "coord"
        and tokens[1].is_word("circle", "rectangle")
    ):
        first, second = tokens[0].coord, tokens[2].coord
        assert first is not None and second is not None
        if first.kind != "cartesian" or first.prefix or second.prefix:
            return None
        if tokens[1].text == "rectangle" and second.kind != "cartesian":
            return None
        if tokens[1].text == "circle" and second.kind == "cartesian":
            return None
        return tokens[1].text, [first, second]
    return None


def _mask_comments(text: str) -> str:
    """Replace comment text with spaces, keeping offsets and newlines."""
    out = list(text)
    i = 0
    while i < len(text):
        if text[i] == "\\":
            i += 2
            continue
        if text[i] == "%":
            end = text.find("\n", i)
            end = len(text) if end == -1 else end
            for j in range(i, end):
                out[j] = " "
            i = end
            continue
        i += 1
    return "".join(out)


def load_tikz(figure: TikzFigure, source: str, strict: bool = False) -> ParseResult:
    """Parse *source* into *figure* and return the :class:`ParseResult`.

    Args:
        figure: Figure to populate.
        source: TikZ code containing a ``tikzpicture`` environment, optionally
            inside a ``figure`` environment or a full LaTeX document.
        strict: If ``True``, raise :class:`TikzParseError` when any statement
            could not be mapped to a library object.

    Raises:
        TikzParseError: If *source* is malformed, or in strict mode if some
            statements were kept as raw TikZ.
    """
    result = TikzBuilder(figure).load(source)
    if strict and result.raw:
        details = "\n".join(f"  {d}" for d in result.raw)
        raise TikzParseError(
            f"{len(result.raw)} statement(s) could not be mapped to tikzfigure "
            f"objects:\n{details}"
        )
    return result
