from __future__ import annotations

from importlib.metadata import version
from typing import Any

from tikzfigure.core.axis import Axis2D
from tikzfigure.core.constants import TAB

line_length = 50
version_string = f"% Tikzfigure generated by tikzfigure v{version('tikzfigure')}"
version_string += " " * (line_length - len(version_string) - 2) + "%\n"
link_string = "% https://github.com/max-models/tikzfigure"
link_string += " " * (line_length - len(link_string) - 2) + "%\n"
line_separator = "% " + "-" * (line_length - 5) + " %\n"
TIKZFIGURE_HEADER = line_separator + version_string + link_string + line_separator


class FigureRenderMixin:
    _extra_packages: list[str] | None
    _tikz_libraries: list[str]
    _named_styles: list[dict[str, Any]]
    _figure_setup: str | None
    _show_axes: bool
    _grid: bool
    _subfigure_axes: list[tuple[Axis2D, float]]
    _subfigure_grid: dict[tuple[int, int], tuple[Any, float] | tuple[Any, float, str]]
    _subfigure_rows: int | None
    _subfigure_cols: int | None
    _description: str | None
    _label: str | None

    @property
    def axes(self) -> list[Axis2D]:
        raise NotImplementedError

    @property
    def layers(self) -> Any:
        raise NotImplementedError

    @property
    def variables(self) -> list[Any]:
        raise NotImplementedError

    @property
    def declared_functions(self) -> list[Any]:
        raise NotImplementedError

    def add_package(self, package: str) -> None:
        raise NotImplementedError

    @property
    def named_styles(self) -> list[dict[str, Any]]:
        raise NotImplementedError

    @staticmethod
    def _format_tikz_value(value: object, output_unit: str | None = None) -> str:
        from tikzfigure.arrows import TikzArrow
        from tikzfigure.colors import TikzColor
        from tikzfigure.styles import TikzStyle
        from tikzfigure.units import TikzDimension

        if isinstance(value, TikzDimension):
            return str(value.to(output_unit)) if output_unit is not None else str(value)
        if isinstance(value, (TikzArrow, TikzColor, TikzStyle)):
            return str(value)
        return str(value)

    def _render_named_style(
        self,
        style_def: dict[str, Any],
        output_unit: str | None = None,
    ) -> str:
        parts = [
            self._format_tikz_value(option, output_unit)
            for option in style_def["options"]
        ]
        parts.extend(
            f"{key.replace('_', ' ')}={self._format_tikz_value(value, output_unit)}"
            for key, value in style_def["kwargs"].items()
        )
        return f"{style_def['name']}/.style={{{', '.join(parts)}}}"

    def _render_figure_option_block(self, output_unit: str | None = None) -> str:
        items: list[str] = []
        if self._figure_setup:
            items.append(self._figure_setup)
        items.extend(
            self._render_named_style(style_def, output_unit)
            for style_def in self._named_styles
        )
        if not items:
            return ""
        if (
            len(items) == 1
            and not self._named_styles
            and self._figure_setup is not None
        ):
            return f"[{items[0]}]"
        return "[\n" + ",\n".join(f"{TAB}{item}" for item in items) + "\n]"

    def _tikzpicture_opening(self, output_unit: str | None = None) -> str:
        return (
            f"\\begin{{tikzpicture}}{self._render_figure_option_block(output_unit)}\n"
        )

    @property
    def colors(self) -> list[tuple[str, Any]]:
        raise NotImplementedError

    @property
    def ndim(self) -> int:
        raise NotImplementedError

    @property
    def document_setup(self) -> str | None:
        raise NotImplementedError

    def _render_axis_in_groupplot(self, axis: Axis2D) -> str:
        raise NotImplementedError

    def _render_groupplot_grid(self, num_rows: int, num_cols: int) -> str:
        raise NotImplementedError

    def _render_mixed_grid(self, num_rows: int, num_cols: int) -> str:
        raise NotImplementedError

    def _add_tabs(self, tikz_script: str) -> str:
        tikz_script_new = ""
        num_tabs = 0
        for line in tikz_script.split("\n"):
            if "\\end" in line or "end \\foreach" in line:
                num_tabs = max(num_tabs - 1, 0)
            tikz_script_new += f"{TAB * num_tabs}{line}".rstrip() + "\n"
            if "\\begin" in line or "start \\foreach" in line:
                num_tabs += 1
            if "\\foreach" in line and "in" in line and "{" in line:
                num_tabs += 1
        return tikz_script_new

    def generate_tikz(
        self,
        use_layers: bool = True,
        skip_header: bool = False,
        verbose: bool = False,
        output_unit: str | None = None,
    ) -> str:
        if self.axes and "pgfplots" not in (self._extra_packages or []):
            self.add_package("pgfplots")

        tikz_script = ""
        if not skip_header:
            tikz_script += TIKZFIGURE_HEADER
        tikz_script += self._tikzpicture_opening(output_unit)

        if len(self.variables) > 0:
            for variable in self.variables:
                tikz_script += (
                    f"\\pgfmathsetmacro{{\\{variable.label}}}{{{variable.value}}}\n"
                )

        if len(self.declared_functions) > 0:
            for function in self.declared_functions:
                tikz_script += function.to_tikz(output_unit)

        if len(self.colors) > 0:
            for name, color in self.colors:
                tikz_script += f"\\colorlet{{{name}}}{{{color.color_spec}}}\n"

        if self.ndim == 3:
            tikz_script += "\\begin{axis}[\n"
            tikz_script += "view={20}{30},\n"
            if self._show_axes:
                tikz_script += "axis lines=center,\n"
                tikz_script += "xlabel={$x$},\n"
                tikz_script += "ylabel={$y$},\n"
                tikz_script += "zlabel={$z$},\n"
                tikz_script += "grid=major\n"
            else:
                tikz_script += "hide axis\n"
            tikz_script += f"{TAB}]\n"

        all_layer_keys = set(self.layers.layers.keys())
        for axis in self.axes:
            axis_layer = axis.layer if axis.layer is not None else 0
            all_layer_keys.add(axis_layer)

        if len(all_layer_keys) <= 1:
            use_layers = False

        layers = sorted([str(lyr) for lyr in all_layer_keys])
        if use_layers:
            tikz_script += "% Define the layers library\n"
            for lyr_str in layers:
                tikz_script += f"\\pgfdeclarelayer{{{lyr_str}}}\n"
            if len(layers) > 0:
                tikz_script += f"\\pgfsetlayers{{{','.join(layers)}}}\n"

        if self._grid:
            tikz_script += (
                f"{TAB}\\draw[step=1cm, gray, very thin] (-10,-10) grid (10,10);\n"
            )
        ordered_layers = []
        buffered_layers = set()

        for key, layer in self.layers.layers.items():
            reqs = layer.get_reqs()
            if all([r == layer.label for r in reqs]):
                ordered_layers.append(layer)
            elif all([r in [layer.label for layer in ordered_layers] for r in reqs]):
                ordered_layers.append(layer)
            else:
                buffered_layers.add(layer)

            for buffered_layer in list(buffered_layers):
                buff_reqs = buffered_layer.get_reqs()
                if all(
                    [r in [layer.label for layer in ordered_layers] for r in buff_reqs],
                ):
                    ordered_layers.append(buffered_layer)
                    buffered_layers.remove(buffered_layer)
        assert len(buffered_layers) == 0, (
            "Layer order is impossible for layer"
            + f"{[layer.label for layer in buffered_layers]}"
        )
        axes_by_layer: dict[int, list[Axis2D]] = {}
        for axis in self.axes:
            layer_key = axis.layer if axis.layer is not None else 0
            if layer_key not in axes_by_layer:
                axes_by_layer[layer_key] = []
            axes_by_layer[layer_key].append(axis)

        for layer in ordered_layers:
            tikz_script += layer.generate_tikz(
                use_layers=use_layers,
                verbose=verbose,
                output_unit=output_unit,
            )
            if isinstance(layer.label, int) and layer.label in axes_by_layer:
                for axis in axes_by_layer[layer.label]:
                    tikz_script += axis.to_tikz(output_unit)

        rendered_layers = {layer.label for layer in ordered_layers}
        for layer_key in sorted(axes_by_layer.keys()):
            if layer_key not in rendered_layers:
                for axis in axes_by_layer[layer_key]:
                    if use_layers:
                        tikz_script += f"\n% Layer {layer_key}\n"
                        tikz_script += f"\\begin{{pgfonlayer}}{{{layer_key}}}\n"
                        tikz_script += axis.to_tikz(output_unit)
                        tikz_script += f"\\end{{pgfonlayer}}{{{layer_key}}}\n"
                    else:
                        tikz_script += axis.to_tikz(output_unit)

        if self.ndim == 3:
            tikz_script += "\\end{axis}\n"
        tikz_script += "\\end{tikzpicture}"

        if self._subfigure_axes or self._subfigure_grid:
            subfig_tikz = self._tikzpicture_opening(output_unit)

            for variable in self.variables:
                subfig_tikz += (
                    f"\\pgfmathsetmacro{{\\{variable.label}}}{{{variable.value}}}\n"
                )
            for function in self.declared_functions:
                subfig_tikz += function.to_tikz(output_unit)
            for name, color in self.colors:
                subfig_tikz += f"\\colorlet{{{name}}}{{{color.color_spec}}}\n"

            if self._subfigure_rows is not None:
                num_cols = self._subfigure_cols
                assert num_cols is not None
                num_rows = self._subfigure_rows

                from tikzfigure.core.figure import TikzFigure

                has_bare_subfigures = any(
                    isinstance(item_data[0], TikzFigure)
                    for item_data in self._subfigure_grid.values()
                )

                if has_bare_subfigures:
                    subfig_tikz += self._render_mixed_grid(num_rows, num_cols)
                else:
                    subfig_tikz += self._render_groupplot_grid(num_rows, num_cols)
            else:
                num_axes = len(self._subfigure_axes)
                group_opts = (
                    f"group style={{group size={num_axes} by 1, horizontal sep=1.5cm}}"
                )
                subfig_tikz += f"\\begin{{groupplot}}[{group_opts}]\n"
                for item_tuple in self._subfigure_axes:
                    item, width = item_tuple
                    subfig_tikz += self._render_axis_in_groupplot(item)
                subfig_tikz += "\\end{groupplot}\n"

            subfig_tikz += "\\end{tikzpicture}"
            tikz_script = subfig_tikz
        elif self._description or self._label:
            figure_env = "\\begin{figure}\n" + tikz_script + "\n"
            if self._label:
                figure_env += f"{TAB}\\label{{{self._label}}}\n"
            figure_env += "\\end{figure}"
            tikz_script = figure_env
        tikz_script = self._add_tabs(tikz_script)
        tikz_script = tikz_script.replace(r"% {\end foreach}", "")
        return tikz_script

    def generate_standalone(
        self,
        skip_header: bool = False,
        verbose: bool = False,
        output_unit: str | None = None,
    ) -> str:
        tikz_code = self.generate_tikz(
            skip_header=skip_header,
            verbose=verbose,
            output_unit=output_unit,
        )

        latex_document = (
            "\\documentclass[border=10pt]{standalone}\n"
            "\\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}\n"
            "\\usepackage{tikz}\n"
            "\\usepackage{pgfplots}\n"
            "\\pgfplotsset{compat=newest}\n"
            "\\usepgfplotslibrary{groupplots}\n"
        )
        tikz_libraries = list(dict.fromkeys(["arrows.meta", *self._tikz_libraries]))
        latex_document += f"\\usetikzlibrary{{{','.join(tikz_libraries)}}}\n"
        if self._extra_packages:
            for pkg in self._extra_packages:
                latex_document += f"\\usepackage{{{pkg}}}\n"

        if self.document_setup:
            latex_document += "% Custom document setup\n"
            latex_document += f"{self.document_setup}\n"

        latex_document += f"\\begin{{document}}\n{tikz_code}\n\\end{{document}}"
        return latex_document
