import os
import re
import subprocess
import tempfile
from importlib.metadata import version
from pathlib import Path
from typing import Any

import fitz

from tikzfigure.core.base import TikzObject
from tikzfigure.core.color import Color
from tikzfigure.core.coordinate import TikzCoordinate
from tikzfigure.core.layer import LayerCollection
from tikzfigure.core.loop import Loop
from tikzfigure.core.node import Node
from tikzfigure.core.path import TikzPath
from tikzfigure.core.plot import Plot3D
from tikzfigure.core.raw import RawTikz
from tikzfigure.core.types import (
    _Align,
    _Anchor,
    _Decoration,
    _LineCap,
    _LineJoin,
    _Mark,
    _Pattern,
    _Shading,
    _Shape,
)
from tikzfigure.core.variable import Variable

line_length = 50
version_string = f"% Tikzfigure generated by tikzfigure v{version('tikzfigure')}"
version_string += " " * (line_length - len(version_string) - 2) + "%\n"
link_string = "% https://github.com/max-models/tikzfigure"
link_string += " " * (line_length - len(link_string) - 2) + "%\n"
line_separator = "% " + "-" * (line_length - 5) + " %\n"
TIKZFIGURE_HEADER = line_separator + version_string + link_string + line_separator


class TikzFigure:
    """Main entry point for building TikZ figures programmatically.

    Holds layers, variables, colors, and all TikZ primitives.  Call
    :meth:`generate_tikz` to obtain the LaTeX source, :meth:`compile_pdf`
    to compile it, and :meth:`savefig` / :meth:`show` to export or display
    the result.

    Attributes:
        layers: The :class:`LayerCollection` holding all drawing layers.
        variables: List of :class:`Variable` objects defined in this figure.
        colors: List of ``(name, Color)`` pairs defined with
            :meth:`colorlet`.
        ndim: Number of spatial dimensions (``2`` or ``3``).
        document_setup: Custom LaTeX preamble inserted before
            ``\\begin{document}``.
        extra_packages: Extra LaTeX packages to include in the preamble.
    """

    # ------------------------------------------------------------- #
    # Private methods

    def _add_path(
        self,
        nodes: list[Any],
        layer: int = 0,
        comment: str | None = None,
        center: bool = False,
        tikz_command: str = "draw",
        verbose: bool = False,
        options: list | str | None = None,
        cycle: bool = False,
        **kwargs: Any,
    ) -> TikzPath:
        """Internal helper that creates and registers a :class:`TikzPath`.

        Resolves node labels to :class:`Node` objects and coordinate tuples
        to :class:`TikzCoordinate` objects before constructing the path.

        Args:
            nodes: Items to connect. Each element may be a :class:`Node`,
                a node label string, or an ``(x, y)`` / ``(x, y, z)``
                coordinate tuple.
            layer: Target layer index. Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            center: If ``True``, connect through ``.center`` anchors.
            tikz_command: TikZ drawing command (``"draw"`` or
                ``"filldraw"``). Defaults to ``"draw"``.
            verbose: If ``True``, print the resolved node list.
            options: Flag-style TikZ options (string or list).
            cycle: If ``True``, close the path with ``-- cycle``.
            **kwargs: Keyword-style TikZ path options.

        Returns:
            The newly created :class:`TikzPath`.

        Raises:
            ValueError: If *nodes* is not a list.
            NotImplementedError: If an element of *nodes* has an
                unrecognised type.
        """
        if not isinstance(nodes, list):
            raise ValueError("nodes parameter must be a list of node names.")

        nodes_cleaned: list[Node | TikzCoordinate] = []

        for node in nodes:
            if isinstance(node, Node):
                nodes_cleaned.append(node)
            elif isinstance(node, str):
                # Find the node by its label
                nodes_cleaned.append(self.layers.get_node(node))
            elif isinstance(node, tuple) or isinstance(node, list):
                coords = tuple(node)
                nodes_cleaned.append(TikzCoordinate(*coords, layer=layer))  # type: ignore[misc]
            else:
                raise NotImplementedError(
                    f"{node =}, {type(node) =} is not a valid node type!",
                )

        if verbose:
            print(f"Creating a path with the following nodes {nodes_cleaned}")

        if isinstance(options, str):
            options = [options]

        path = TikzPath(
            nodes=nodes_cleaned,
            comment=comment,
            center=center,
            tikz_command=tikz_command,
            options=options,
            cycle=cycle,
            **kwargs,
        )
        self.layers.add_item(item=path, layer=layer, verbose=verbose)
        return path

    def __init__(
        self,
        ndim: int = 2,
        label: str | None = None,
        grid: bool = False,
        tikz_code: str | None = None,
        extra_packages: list | None = None,
        document_setup: str | None = None,
        figure_setup: str | None = None,
        figsize: tuple[float, float] = (10, 6),
        caption: str | None = None,
        description: str | None = None,
        show_axes: bool = False,
    ) -> None:
        """Initialize a TikzFigure.

        Args:
            ndim: Number of spatial dimensions. Use ``2`` for standard
                figures and ``3`` for pgfplots 3-D axis figures.
                Defaults to ``2``.
            label: LaTeX ``\\label`` for the surrounding ``figure``
                environment. When set, the figure is wrapped in a
                ``figure`` environment.
            grid: If ``True``, draw a background grid. Defaults to
                ``False``.
            tikz_code: Existing TikZ code to parse and import. When
                provided, nodes and paths are reconstructed from the
                source. Defaults to ``None``.
            extra_packages: Additional LaTeX packages to include in the
                standalone preamble (e.g. ``["amsmath"]``).
            document_setup: Raw LaTeX to insert in the preamble after
                the standard packages.
            figure_setup: TikZ options string placed inside the opening
                ``\\begin{tikzpicture}[…]`` bracket.
            figsize: ``(width, height)`` in centimetres used as a hint
                for display backends. Defaults to ``(10, 6)``.
            caption: ``\\caption`` text for the ``figure`` environment.
            description: Long description stored for documentation
                purposes (not emitted in TikZ output).
            show_axes: For 3-D figures, if ``True`` render the pgfplots
                axis lines and labels. Defaults to ``False``.
        """

        self._figsize: tuple[float, float] = figsize
        self._caption: str | None = caption
        self._description: str | None = description
        self._label: str | None = label
        self._grid: bool = grid
        self._show_axes: bool = show_axes
        self._tikz_code: str | None = tikz_code
        self._figure_setup: str | None = figure_setup
        self._extra_packages: list | None = extra_packages
        self._document_setup: str | None = document_setup
        # Initialize lists to hold Node and Path objects
        # TODO: nodes, paths, layers should have @property and @setter methods
        self._layers: LayerCollection = LayerCollection()
        self._variables: list[Variable] = []
        self._colors: list[tuple[str, Color]] = []
        self._ndim: int = ndim

        # Counter for unnamed nodes
        self._node_counter: int = 0

        if self._tikz_code:
            lines = self._tikz_code.split("\n")
            lines = [line.lstrip().rstrip() for line in lines]
            lines = [line for line in lines if line not in ["", "\n"]]
            lines = [line for line in lines if not line[0] == "%"]

            assert lines[0] == "\\begin{tikzpicture}", f"Found: {lines[0]}"
            assert lines[-1] == "\\end{tikzpicture}", f"Found: {lines[-1]}"

            current_layer = 0
            for line in lines[1:-1]:
                # Collapse multiple spaces to a single space for robust parsing
                line = re.sub(r" +", " ", line)
                # print(line)

                # Match \begin{pgfonlayer}{layer}
                match_pgfdeclarelayer = re.search(r"\\pgfdeclarelayer\{(\d+)\}", line)
                if match_pgfdeclarelayer:
                    layer = int(match_pgfdeclarelayer.group(1))
                    self.layers.add_layer(layer)
                    # print(f"Layer number: {layer}")

                # Match \begin{pgfonlayer}{layer}
                match_begin_pgfonlayer = re.search(
                    r"\\begin\{pgfonlayer\}\{(\d+)\}",
                    line,
                )
                if match_begin_pgfonlayer:
                    current_layer = int(match_begin_pgfonlayer.group(1))
                    # print(f'Current layer: {current_layer}')

                # Match \end{pgfonlayer}{layer}
                match_end_pgfonlayer = re.search(r"\\end\{pgfonlayer\}\{(\d+)\}", line)
                if match_end_pgfonlayer:
                    current_layer = 0
                    # print(f'Current layer: {current_layer}')

                # Match \node[attributes] at (x,y) {content};
                match_node = re.search(
                    r"\\node(?:\[([^\]]+)\])? \((\w+)\) at \(([^,]+, [^)]+)\) \{(.*)\};",
                    line,
                )
                if match_node:
                    attributes = match_node.group(1)
                    attributes = [
                        attribute.lstrip().rstrip()
                        for attribute in attributes.split(",")
                    ]
                    attributes = [
                        attribute for attribute in attributes if not attribute == ""
                    ]
                    attributes_dict = dict(attr.split("=") for attr in attributes)
                    node_name = match_node.group(2)
                    coordinates = match_node.group(3)
                    coordinates = [c.strip() for c in coordinates.split(",")]
                    coordinates = [
                        int(c) if "." not in c else float(c) for c in coordinates
                    ]
                    content = match_node.group(4)
                    # print(f"Attributes: {attributes_dict}")
                    # print(f"Node name: {node_name}")
                    # print(f"Coordinates: {coordinates}")
                    # print(f"Node text: '{node_text}'")
                    # print(coordinates.split(','))

                    self.add_node(
                        x=coordinates[0],
                        y=coordinates[1],
                        label=node_name,
                        layer=current_layer,
                        content=content,
                        **attributes_dict,
                    )

                # Match \draw[attributes] (node1.center) to (node2.center) to (node2.center)...;
                match_draw = re.search(
                    r"\\draw(?:\[([^\]]+)\])? ((?:\(\w+\.*\) to )+\(\w+\.*\));",
                    line,
                )
                if match_draw:
                    attributes = match_draw.group(1)
                    attributes = [
                        attribute.lstrip().rstrip()
                        for attribute in attributes.split(",")
                    ]
                    attributes = [
                        attribute for attribute in attributes if not attribute == ""
                    ]
                    path = match_draw.group(2)
                    nodes = re.findall(r"\((\w+)\.*\)", path)

                    # print(f"Attributes: {attributes}")
                    # print(f"Path: {path}")
                    # print(f"Nodes: {nodes}")
                    attrs_kwargs = {}
                    attrs_options = []
                    for attr in attributes:
                        if "=" in attr:
                            k, v = attr.split("=", 1)
                            attrs_kwargs[k.strip().replace(" ", "_")] = v.strip()
                        else:
                            attrs_options.append(attr)
                    self._add_path(
                        nodes,
                        options=attrs_options or None,
                        layer=current_layer,
                        **attrs_kwargs,
                    )

    # ------------------------------------------------------------- #
    # Class methods

    @classmethod
    def from_tikz_code(cls, tikz_code: str, **kwargs: Any) -> "TikzFigure":
        """Create a TikzFigure by parsing existing TikZ source code.

        Args:
            tikz_code: A string containing a ``tikzpicture`` environment.
            **kwargs: Additional keyword arguments forwarded to
                :meth:`__init__`.

        Returns:
            A new :class:`TikzFigure` with nodes and paths reconstructed
            from *tikz_code*.
        """
        return cls(tikz_code=tikz_code, **kwargs)

    def to_dict(self) -> dict[str, Any]:
        """Serialize this figure to a plain dictionary.

        Returns:
            A dictionary capturing all figure settings, layers, variables,
            and colors, suitable for round-tripping via :meth:`from_dict`.
        """
        layers_dict: dict[Any, list[dict[str, Any]]] = {}
        for layer_label, layer in self._layers.layers.items():
            layers_dict[layer_label] = [item.to_dict() for item in layer.items]
        return {
            "type": "TikzFigure",
            "ndim": self._ndim,
            "label": self._label,
            "grid": self._grid,
            "show_axes": self._show_axes,
            "extra_packages": (
                list(self._extra_packages) if self._extra_packages else None
            ),
            "document_setup": self._document_setup,
            "figure_setup": self._figure_setup,
            "figsize": list(self._figsize),
            "caption": self._caption,
            "description": self._description,
            "layers": layers_dict,
            "variables": [v.to_dict() for v in self._variables],
            "colors": [
                {"name": name, **color.to_dict()} for name, color in self._colors
            ],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "TikzFigure":
        """Reconstruct a TikzFigure from a dictionary.

        Args:
            d: Dictionary as produced by :meth:`to_dict`.

        Returns:
            A fully restored :class:`TikzFigure` instance.
        """
        fig = cls(
            ndim=d.get("ndim", 2),
            label=d.get("label"),
            grid=d.get("grid", False),
            extra_packages=d.get("extra_packages"),
            document_setup=d.get("document_setup"),
            figure_setup=d.get("figure_setup"),
            figsize=tuple(d.get("figsize", [10, 6])),
            caption=d.get("caption"),
            description=d.get("description"),
            show_axes=d.get("show_axes", False),
        )

        for var_dict in d.get("variables", []):
            fig._variables.append(Variable.from_dict(var_dict))

        for color_entry in d.get("colors", []):
            fig._colors.append((color_entry["name"], Color.from_dict(color_entry)))

        # Build node lookup across all layers for path deserialization
        layers_data: dict[Any, list[dict[str, Any]]] = d.get("layers", {})
        node_lookup: dict[str, Node] = {}
        for items_data in layers_data.values():
            for item_data in items_data:
                if item_data.get("type") == "Node":
                    node = Node.from_dict(item_data)
                    if node.label is not None:
                        node_lookup[node.label] = node

        # Reconstruct layers in order
        for layer_label, items_data in layers_data.items():
            for item_data in items_data:
                item_type = item_data.get("type")
                if item_type == "Node":
                    fig.layers.add_item(
                        node_lookup[item_data["label"]], layer=layer_label
                    )
                elif item_type == "Path":
                    fig.layers.add_item(
                        TikzPath.from_dict(item_data, node_lookup=node_lookup),
                        layer=layer_label,
                    )
                elif item_type == "Plot3D":
                    fig.layers.add_item(Plot3D.from_dict(item_data), layer=layer_label)
                elif item_type == "Loop":
                    fig.layers.add_item(Loop.from_dict(item_data), layer=layer_label)
                elif item_type == "RawTikz":
                    fig.layers.add_item(RawTikz.from_dict(item_data), layer=layer_label)

        # Keep node counter consistent with restored nodes
        max_auto = -1
        for label in node_lookup:
            if label.startswith("node"):
                try:
                    max_auto = max(max_auto, int(label[4:]))
                except ValueError:
                    pass
        if max_auto >= 0:
            fig._node_counter = max_auto + 1

        return fig

    # ------------------------------------------------------------- #
    # Public methods

    def add(
        self, items: list | tuple | Node, layer: int = 0, verbose: bool = False
    ) -> None:
        """Add one or more pre-built items to the figure.

        Args:
            items: A single :class:`Node` or a list/tuple of items to add.
            layer: Target layer index. Defaults to ``0``.
            verbose: If ``True``, print a debug message for each insertion.
        """
        if not isinstance(items, list | tuple):
            items = [items]

        for item in items:
            if isinstance(item, Node):
                if item.label == "":
                    item._label = f"node{self._node_counter}"
                self._node_counter += 1
                self.layers.add_item(item=item, layer=layer, verbose=verbose)

    def colorlet(
        self,
        name: str,
        color_spec: str,
        layer: int = 0,
    ) -> Color:
        """Define a named color with ``\\colorlet``.

        Args:
            name: The name to assign to the color in LaTeX.
            color_spec: A TikZ color specification (e.g. ``"blue!20"``).
            layer: Layer index (currently unused). Defaults to ``0``.

        Returns:
            The :class:`Color` object that was registered.
        """
        color = Color(color_spec=color_spec)

        self._colors.append((name, color))
        return color

    def add_node(
        self,
        x: float | int | str | None = None,
        y: float | int | str | None = None,
        z: float | int | str | None = None,
        label: str | None = None,
        content: str = "",
        layer: int = 0,
        comment: str | None = None,
        options: list | str | None = None,
        verbose: bool = False,
        # Shape
        shape: _Shape = None,
        # Color
        color: str | None = None,
        fill: str | None = None,
        draw: str | None = None,
        text: str | None = None,
        # Opacity
        opacity: float | None = None,
        fill_opacity: float | None = None,
        draw_opacity: float | None = None,
        text_opacity: float | None = None,
        # Size
        minimum_width: str | None = None,
        minimum_height: str | None = None,
        minimum_size: str | None = None,
        # Separation
        inner_sep: str | None = None,
        inner_xsep: str | None = None,
        inner_ysep: str | None = None,
        outer_sep: str | None = None,
        outer_xsep: str | None = None,
        outer_ysep: str | None = None,
        # Line
        line_width: str | None = None,
        # Text
        font: str | None = None,
        text_width: str | None = None,
        text_height: str | None = None,
        text_depth: str | None = None,
        align: _Align = None,
        # Anchor
        anchor: _Anchor = None,
        # Positioning (relative)
        above: str | None = None,
        below: str | None = None,
        left: str | None = None,
        right: str | None = None,
        above_left: str | None = None,
        above_right: str | None = None,
        below_left: str | None = None,
        below_right: str | None = None,
        above_of: str | None = None,
        below_of: str | None = None,
        left_of: str | None = None,
        right_of: str | None = None,
        node_distance: str | None = None,
        # Transformations
        rotate: float | None = None,
        xshift: str | None = None,
        yshift: str | None = None,
        scale: float | None = None,
        xscale: float | None = None,
        yscale: float | None = None,
        xslant: float | None = None,
        yslant: float | None = None,
        # Border
        rounded_corners: str | None = None,
        double: str | None = None,
        double_distance: str | None = None,
        dash_pattern: str | None = None,
        dash_phase: str | None = None,
        # Pattern / shading
        pattern: _Pattern = None,
        pattern_color: str | None = None,
        shading: _Shading = None,
        shading_angle: float | None = None,
        left_color: str | None = None,
        right_color: str | None = None,
        top_color: str | None = None,
        bottom_color: str | None = None,
        inner_color: str | None = None,
        outer_color: str | None = None,
        ball_color: str | None = None,
        # Shape-specific
        regular_polygon_sides: int | None = None,
        star_points: int | None = None,
        star_point_ratio: float | None = None,
        star_point_height: str | None = None,
        # Shadow
        shadow_xshift: str | None = None,
        shadow_yshift: str | None = None,
        shadow_color: str | None = None,
        shadow_opacity: float | None = None,
        shadow_scale: float | None = None,
        # Pin / label on node
        pin: str | None = None,
        # Catch-all for unlisted TikZ options
        **kwargs: Any,
    ) -> Node:
        """Add a node to the TikZ figure.

        Args:
            x: X-coordinate. Use ``None`` for relatively positioned nodes.
            y: Y-coordinate. Use ``None`` for relatively positioned nodes.
            z: Z-coordinate for 3-D figures.
            label: Internal TikZ name. Auto-assigned when ``None``.
            content: Text or LaTeX content displayed inside the node.
            layer: Target layer index. Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            options: Flag-style TikZ options
                (e.g. ``["draw", "thick"]``).
            verbose: If ``True``, print a debug message.
            shape: Node shape
                (e.g. ``"circle"``, ``"rectangle"``, ``"diamond"``).
            color: Text color (e.g. ``"red"``, ``"blue!50"``).
            fill: Fill color.
            draw: Border/stroke color. Use ``"none"`` to hide the border.
            text: Alias for text color.
            opacity: Overall opacity (0–1).
            fill_opacity: Fill opacity (0–1).
            draw_opacity: Border opacity (0–1).
            text_opacity: Text opacity (0–1).
            minimum_width: Minimum node width (e.g. ``"2cm"``).
            minimum_height: Minimum node height.
            minimum_size: Minimum size in both dimensions.
            inner_sep: Inner separation between content and border.
            inner_xsep: Horizontal inner separation.
            inner_ysep: Vertical inner separation.
            outer_sep: Outer separation between border and anchors.
            outer_xsep: Horizontal outer separation.
            outer_ysep: Vertical outer separation.
            line_width: Border line width (e.g. ``"1pt"``).
            font: Font specification (e.g. ``"\\\\tiny"``).
            text_width: Text width for automatic line wrapping.
            text_height: Explicit text height.
            text_depth: Explicit text depth.
            align: Text alignment (``"left"``, ``"center"``, ``"right"``).
            anchor: Anchor point
                (e.g. ``"center"``, ``"north"``, ``"south west"``).
            above: Place above, with optional offset (e.g. ``"5pt"``).
            below: Place below.
            left: Place left.
            right: Place right.
            above_left: Place above-left.
            above_right: Place above-right.
            below_left: Place below-left.
            below_right: Place below-right.
            above_of: Place above a named node.
            below_of: Place below a named node.
            left_of: Place left of a named node.
            right_of: Place right of a named node.
            node_distance: Distance for relative positioning
                (e.g. ``"1cm"``).
            rotate: Rotation angle in degrees.
            xshift: Horizontal shift (e.g. ``"1cm"``).
            yshift: Vertical shift.
            scale: Uniform scaling factor.
            xscale: Horizontal scaling factor.
            yscale: Vertical scaling factor.
            xslant: Horizontal slant factor.
            yslant: Vertical slant factor.
            rounded_corners: Corner rounding radius (e.g. ``"3pt"``).
            double: Inner color for double borders.
            double_distance: Distance between double borders.
            dash_pattern: Custom dash pattern (e.g. ``"on 2pt off 3pt"``).
            dash_phase: Dash pattern starting offset.
            pattern: Fill pattern (e.g. ``"north east lines"``).
            pattern_color: Color for the fill pattern.
            shading: Shading type
                (``"axis"``, ``"radial"``, or ``"ball"``).
            shading_angle: Angle for axis shading.
            left_color: Left color for axis shading.
            right_color: Right color for axis shading.
            top_color: Top color for axis shading.
            bottom_color: Bottom color for axis shading.
            inner_color: Inner color for radial shading.
            outer_color: Outer color for radial shading.
            ball_color: Ball color for ball shading.
            regular_polygon_sides: Number of sides for
                ``shape="regular polygon"``.
            star_points: Number of points for ``shape="star"``.
            star_point_ratio: Inner-to-outer radius ratio for stars.
            star_point_height: Height of star points.
            shadow_xshift: Horizontal shadow shift.
            shadow_yshift: Vertical shadow shift.
            shadow_color: Shadow color.
            shadow_opacity: Shadow opacity (0–1).
            shadow_scale: Shadow scale factor.
            pin: Pin label specification (e.g. ``"above:text"``).
            **kwargs: Additional TikZ options. Underscores in keys become
                spaces (e.g. ``signal_from`` → ``signal from``).

        Returns:
            The :class:`Node` object that was added.
        """
        _params = locals().copy()
        _non_tikz = {
            "self",
            "x",
            "y",
            "z",
            "label",
            "content",
            "layer",
            "comment",
            "options",
            "verbose",
            "kwargs",
            "__class__",
        }

        tikz_kwargs = dict(kwargs)
        tikz_kwargs.update(
            {k: v for k, v in _params.items() if k not in _non_tikz and v is not None}
        )

        if options is None:
            options = []

        if isinstance(options, str):
            options = [options]

        if label is None:
            label = f"node{self._node_counter}"
        node = Node(
            x=x,
            y=y,
            z=z,
            label=label,
            layer=layer,
            content=content,
            comment=comment,
            options=options,
            **tikz_kwargs,
        )
        self._node_counter += 1
        self.layers.add_item(item=node, layer=layer, verbose=verbose)
        return node

    def midpoint(
        self,
        node1: "Node | str",
        node2: "Node | str",
        label: str | None = None,
        layer: int = 0,
        content: str = "",
        **kwargs: Any,
    ) -> Node:
        """Add a node at the midpoint between two existing nodes.

        Args:
            node1: First node object or its label string.
            node2: Second node object or its label string.
            label: Label for the new midpoint node. Auto-assigned when
                ``None``.
            layer: Target layer index. Defaults to ``0``.
            content: Text content for the midpoint node.
            **kwargs: Additional options forwarded to :meth:`add_node`.

        Returns:
            The new :class:`Node` placed at the computed midpoint.

        Raises:
            ValueError: If either node lacks explicit numeric coordinates.
        """
        if isinstance(node1, str):
            node1 = self.layers.get_node(node1)
        if isinstance(node2, str):
            node2 = self.layers.get_node(node2)

        if node1.x is None or node1.y is None:
            raise ValueError(
                f"Node '{node1.label}' does not have explicit coordinates."
            )
        if node2.x is None or node2.y is None:
            raise ValueError(
                f"Node '{node2.label}' does not have explicit coordinates."
            )

        mid_x = (node1.x + node2.x) / 2  # type: ignore[operator]
        mid_y = (node1.y + node2.y) / 2  # type: ignore[operator]

        if node1.ndim == 3 and node2.ndim == 3:
            mid_z = (node1.z + node2.z) / 2  # type: ignore[operator]
        else:
            mid_z = None

        return self.add_node(
            x=mid_x,
            y=mid_y,
            z=mid_z,
            label=label,
            layer=layer,
            content=content,
            **kwargs,
        )

    def add_variable(
        self,
        label: str,
        value: int | float,
        layer: int | None = 0,
        comment: str | None = None,
        verbose: bool = False,
    ) -> Variable:
        """Add a pgfmath variable (``\\pgfmathsetmacro``) to the figure.

        Variables are emitted at the top of the ``tikzpicture`` environment
        so they can be referenced anywhere in the figure.

        Args:
            label: Variable name (without the leading backslash).
            value: Numeric value to assign.
            layer: Layer index (currently unused). Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            verbose: Unused; reserved for future debug output.

        Returns:
            The :class:`Variable` object that was added.
        """
        variable = Variable(
            label=label,
            value=value,
            layer=layer,
            comment=comment,
        )
        self._variables.append(variable)

        # TODO: Allow for special variables in each layer
        # self.layers.add_item(item=variable, layer=layer, verbose=verbose)
        return variable

    def add_raw(
        self,
        tikz_code: str,
        layer: int = 0,
        verbose: bool = False,
    ) -> RawTikz:
        """Insert a verbatim TikZ code block into the figure.

        Args:
            tikz_code: Raw TikZ source to include verbatim.
            layer: Target layer index. Defaults to ``0``.
            verbose: If ``True``, print a debug message after insertion.

        Returns:
            The :class:`RawTikz` object that was added.
        """
        raw_tikz = RawTikz(tikz_code=tikz_code)

        self.layers.add_item(
            item=raw_tikz,
            layer=layer,
            verbose=verbose,
        )
        return raw_tikz

    def filldraw(
        self,
        nodes: list,
        layer: int = 0,
        comment: str | None = None,
        center: bool = False,
        verbose: bool = False,
        # Path structure
        options: list | str | None = None,
        cycle: bool = False,
        # Color
        color: str | None = None,
        fill: str | None = None,
        draw: str | None = None,
        text: str | None = None,
        # Opacity
        opacity: float | None = None,
        draw_opacity: float | None = None,
        fill_opacity: float | None = None,
        text_opacity: float | None = None,
        # Line width
        line_width: str | None = None,
        # Line style
        line_cap: _LineCap = None,
        line_join: _LineJoin = None,
        miter_limit: float | None = None,
        # Dash
        dash_pattern: str | None = None,
        dash_phase: str | None = None,
        # Double lines
        double: str | None = None,
        double_distance: str | None = None,
        # Corners
        rounded_corners: str | None = None,
        # Transformations
        rotate: float | None = None,
        xshift: str | None = None,
        yshift: str | None = None,
        scale: float | None = None,
        xscale: float | None = None,
        yscale: float | None = None,
        xslant: float | None = None,
        yslant: float | None = None,
        # Path bending
        bend_left: float | None = None,
        bend_right: float | None = None,
        in_angle: float | None = None,
        out_angle: float | None = None,
        looseness: float | None = None,
        in_looseness: float | None = None,
        out_looseness: float | None = None,
        min_distance: str | None = None,
        max_distance: str | None = None,
        # Smooth curves
        tension: float | None = None,
        # Pattern fills
        pattern: _Pattern = None,
        pattern_color: str | None = None,
        # Shading
        shading: _Shading = None,
        shading_angle: float | None = None,
        left_color: str | None = None,
        right_color: str | None = None,
        top_color: str | None = None,
        bottom_color: str | None = None,
        middle_color: str | None = None,
        inner_color: str | None = None,
        outer_color: str | None = None,
        ball_color: str | None = None,
        # Decoration
        decoration: _Decoration = None,
        # Grid
        step: str | None = None,
        # Positioning
        pos: float | None = None,
        # Arrow specification
        arrows: str | None = None,
        # Font
        font: str | None = None,
        # Path naming
        name_path: str | None = None,
        # Custom to-path
        to_path: str | None = None,
        # Plot
        domain: str | None = None,
        samples: int | None = None,
        # Marks
        mark: _Mark = None,
        mark_size: str | None = None,
        # Catch-all for unlisted TikZ options
        **kwargs: Any,
    ) -> TikzPath:
        """Add a filled path connecting multiple nodes with ``\\filldraw``.

        Accepts the same options as :meth:`draw`. See that method for the
        full parameter reference.

        Args:
            nodes: List of nodes, node label strings, or coordinate tuples
                to connect.
            layer: Target layer index. Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            center: If ``True``, connect through ``.center`` anchors.
            verbose: If ``True``, print a debug message.
            options: Flag-style TikZ options (e.g. ``["thick"]``).
            cycle: If ``True``, close the path with ``-- cycle``.
            **kwargs: Any keyword option accepted by :meth:`draw`.

        Returns:
            The :class:`TikzPath` object that was added.
        """
        _params = locals().copy()
        _non_tikz = {
            "self",
            "nodes",
            "layer",
            "comment",
            "center",
            "verbose",
            "options",
            "cycle",
            "kwargs",
            "in_angle",
            "out_angle",
            "__class__",
        }
        tikz_kwargs = dict(kwargs)
        tikz_kwargs.update(
            {k: v for k, v in _params.items() if k not in _non_tikz and v is not None}
        )
        if in_angle is not None:
            tikz_kwargs["in"] = in_angle
        if out_angle is not None:
            tikz_kwargs["out"] = out_angle

        path = self._add_path(
            nodes=nodes,
            layer=layer,
            comment=comment,
            center=center,
            tikz_command="filldraw",
            verbose=verbose,
            options=options,
            cycle=cycle,
            **tikz_kwargs,
        )
        return path

    def draw(
        self,
        nodes: list,
        layer: int = 0,
        comment: str | None = None,
        center: bool = False,
        verbose: bool = False,
        # Path structure
        options: list | str | None = None,
        cycle: bool = False,
        # Color
        color: str | None = None,
        fill: str | None = None,
        draw: str | None = None,
        text: str | None = None,
        # Opacity
        opacity: float | None = None,
        draw_opacity: float | None = None,
        fill_opacity: float | None = None,
        text_opacity: float | None = None,
        # Line width
        line_width: str | int | float | None = None,
        # Line style
        line_cap: _LineCap = None,
        line_join: _LineJoin = None,
        miter_limit: float | None = None,
        # Dash
        dash_pattern: str | None = None,
        dash_phase: str | None = None,
        # Double lines
        double: str | None = None,
        double_distance: str | None = None,
        # Corners
        rounded_corners: str | None = None,
        # Transformations
        rotate: float | None = None,
        xshift: str | None = None,
        yshift: str | None = None,
        scale: float | None = None,
        xscale: float | None = None,
        yscale: float | None = None,
        xslant: float | None = None,
        yslant: float | None = None,
        # Path bending
        bend_left: float | None = None,
        bend_right: float | None = None,
        in_angle: float | None = None,
        out_angle: float | None = None,
        looseness: float | None = None,
        in_looseness: float | None = None,
        out_looseness: float | None = None,
        min_distance: str | None = None,
        max_distance: str | None = None,
        # Smooth curves
        tension: float | None = None,
        # Pattern fills
        pattern: _Pattern = None,
        pattern_color: str | None = None,
        # Shading
        shading: _Shading = None,
        shading_angle: float | None = None,
        left_color: str | None = None,
        right_color: str | None = None,
        top_color: str | None = None,
        bottom_color: str | None = None,
        middle_color: str | None = None,
        inner_color: str | None = None,
        outer_color: str | None = None,
        ball_color: str | None = None,
        # Decoration
        decoration: _Decoration = None,
        # Grid
        step: str | None = None,
        # Positioning
        pos: float | None = None,
        # Arrow specification
        arrows: str | None = None,
        # Font
        font: str | None = None,
        # Path naming
        name_path: str | None = None,
        # Custom to-path
        to_path: str | None = None,
        # Plot
        domain: str | None = None,
        samples: int | None = None,
        # Marks
        mark: _Mark = None,
        mark_size: str | None = None,
        # Catch-all for unlisted TikZ options
        **kwargs: Any,
    ) -> TikzPath:
        """Add a path connecting multiple nodes with ``\\draw``.

        Args:
            nodes: List of :class:`Node` objects, node label strings, or
                ``(x, y)`` / ``(x, y, z)`` coordinate tuples to connect.
            layer: Target layer index. Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            center: If ``True``, connect through ``.center`` anchors.
            verbose: If ``True``, print a debug message.
            options: Flag-style TikZ options without values
                (e.g. ``["->", "thick", "dashed"]``).
            cycle: If ``True``, close the path with ``-- cycle``.
            color: Line color (e.g. ``"red"``, ``"blue!50"``).
            fill: Fill color for the enclosed area.
            draw: Stroke color when different from *color*.
            text: Text color for path labels.
            opacity: Overall opacity (0–1).
            draw_opacity: Stroke opacity (0–1).
            fill_opacity: Fill opacity (0–1).
            text_opacity: Text opacity (0–1).
            line_width: Line width (e.g. ``"1pt"``). For named widths use
                *options* (``"thin"``, ``"thick"``, …).
            line_cap: Line cap style: ``"butt"``, ``"rect"``, or
                ``"round"``.
            line_join: Line join style: ``"miter"``, ``"bevel"``, or
                ``"round"``.
            miter_limit: Miter limit factor for miter joins.
            dash_pattern: Custom dash pattern (e.g. ``"on 2pt off 3pt"``).
            dash_phase: Dash pattern starting offset (e.g. ``"2pt"``).
            double: Inner line color for double lines (e.g. ``"white"``).
            double_distance: Distance between double lines (e.g. ``"2pt"``).
            rounded_corners: Corner rounding radius (e.g. ``"5pt"``).
            rotate: Rotation angle in degrees.
            xshift: Horizontal shift (e.g. ``"1cm"``).
            yshift: Vertical shift (e.g. ``"1cm"``).
            scale: Uniform scaling factor.
            xscale: Horizontal scaling factor.
            yscale: Vertical scaling factor.
            xslant: Horizontal slant factor.
            yslant: Vertical slant factor.
            bend_left: Bend the path left by the given angle.
            bend_right: Bend the path right by the given angle.
            in_angle: Incoming angle for curved paths (TikZ ``in`` key).
            out_angle: Outgoing angle for curved paths (TikZ ``out`` key).
            looseness: Looseness of curved paths. Defaults to 1.
            in_looseness: Incoming looseness for curved paths.
            out_looseness: Outgoing looseness for curved paths.
            min_distance: Minimum distance for curved paths.
            max_distance: Maximum distance for curved paths.
            tension: Tension for smooth curves.
            pattern: Fill pattern name
                (e.g. ``"north east lines"``, ``"dots"``).
            pattern_color: Color for the fill pattern.
            shading: Shading type
                (``"axis"``, ``"radial"``, or ``"ball"``).
            shading_angle: Angle for axis shading.
            left_color: Left color for axis shading.
            right_color: Right color for axis shading.
            top_color: Top color for axis shading.
            bottom_color: Bottom color for axis shading.
            middle_color: Middle color for axis shading.
            inner_color: Inner color for radial shading.
            outer_color: Outer color for radial shading.
            ball_color: Ball color for ball shading.
            decoration: Decoration name
                (e.g. ``"zigzag"``). Use with ``options=["decorate"]``.
            step: Step size for grid patterns (e.g. ``"1cm"``).
            pos: Position along the path for labels (0–1).
            arrows: Arrow tip specification
                (e.g. ``"-Stealth"``, ``"Latex-Latex"``).
            font: Font specification (e.g. ``"\\\\tiny"``).
            name_path: Name for path intersection calculations.
            to_path: Custom to-path specification.
            domain: Domain for plot paths (e.g. ``"0:360"``).
            samples: Number of samples for plot paths.
            mark: Mark type for plot paths
                (e.g. ``"*"``, ``"o"``, ``"x"``).
            mark_size: Size of plot marks (e.g. ``"2pt"``).
            **kwargs: Additional TikZ options. Underscores in keys become
                spaces (e.g. ``near_start`` → ``near start``).

        Returns:
            The :class:`TikzPath` object that was added.
        """
        # Snapshot explicit params before creating any locals
        _params = locals().copy()

        # Keys that are not TikZ drawing options
        _non_tikz = {
            "self",
            "nodes",
            "layer",
            "comment",
            "center",
            "verbose",
            "options",
            "cycle",
            "kwargs",
            "in_angle",
            "out_angle",
            "__class__",
        }

        # Start with catch-all kwargs, then overlay explicit params
        tikz_kwargs = dict(kwargs)
        tikz_kwargs.update(
            {k: v for k, v in _params.items() if k not in _non_tikz and v is not None}
        )

        # Map Python-safe names to TikZ key names
        if in_angle is not None:
            tikz_kwargs["in"] = in_angle
        if out_angle is not None:
            tikz_kwargs["out"] = out_angle

        path = self._add_path(
            nodes=nodes,
            layer=layer,
            comment=comment,
            center=center,
            tikz_command="draw",
            verbose=verbose,
            options=options,
            cycle=cycle,
            **tikz_kwargs,
        )
        return path

    def plot3d(
        self,
        x: list[float],
        y: list[float],
        z: list[float],
        layer: int = 0,
        comment: str | None = None,
        center: bool = False,
        verbose: bool = False,
        **kwargs: Any,
    ) -> Plot3D:
        """Add a 3-D data plot with ``\\addplot3``.

        Args:
            x: List of x-coordinate values.
            y: List of y-coordinate values.
            z: List of z-coordinate values.
            layer: Target layer index. Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            center: If ``True``, connect through ``.center`` anchors.
            verbose: If ``True``, print a debug message.
            **kwargs: Additional pgfplots options (e.g. ``mark="*"``).

        Returns:
            The :class:`Plot3D` object that was added.
        """
        plot = Plot3D(
            x=x,
            y=y,
            z=z,
            comment=comment,
            center=center,
            **kwargs,
        )

        self.layers.add_item(item=plot, layer=layer, verbose=verbose)
        return plot

    def add_loop(
        self,
        variable: str,
        values: list[Any],
        layer: int = 0,
        comment: str | None = None,
        verbose: bool = False,
    ) -> Loop:
        """Add a ``\\foreach`` loop to the figure.

        Args:
            variable: Loop variable name (without the leading backslash),
                e.g. ``"i"`` produces ``\\foreach \\i in {...}``.
            values: Sequence of values to iterate over.
            layer: Target layer index. Defaults to ``0``.
            comment: Optional comment prepended in the TikZ output.
            verbose: If ``True``, print a debug message.

        Returns:
            The :class:`Loop` context manager. Add nodes and paths inside a
            ``with`` block or by calling methods on the returned object.
        """
        loop_obj = Loop(
            variable=variable,
            values=values,
            layer=layer,
            comment=comment,
        )

        self.layers.add_item(item=loop_obj, layer=layer, verbose=verbose)
        return loop_obj

    def _add_tabs(self, tikz_script: str) -> str:
        """Indent a TikZ script for improved readability.

        Increases indentation after ``\\begin`` commands and decreases it
        before ``\\end`` commands.

        Args:
            tikz_script: Raw TikZ source string.

        Returns:
            The same source with each line indented by four spaces per
            nesting level.
        """
        tikz_script_new = ""
        tab_str = "    "
        num_tabs = 0
        for line in tikz_script.split("\n"):
            if "\\end" in line or "end \\foreach" in line:
                num_tabs = max(num_tabs - 1, 0)
            tikz_script_new += f"{tab_str * num_tabs}{line}\n"
            if "\\begin" in line or "start \\foreach" in line:
                num_tabs += 1
        return tikz_script_new

    def generate_tikz(self, use_layers: bool = True, verbose: bool = False) -> str:
        """Generate the complete TikZ source for this figure.

        Args:
            use_layers: If ``True`` and the figure has more than one layer,
                wrap each layer in a ``pgfonlayer`` environment. Defaults
                to ``True``.
            verbose: If ``True``, print debug information during generation.

        Returns:
            A string containing the full TikZ source, starting with
            ``\\begin{tikzpicture}`` and ending with
            ``\\end{tikzpicture}``. Wrapped in a ``figure`` environment
            when a caption or label is set.
        """
        tikz_script = TIKZFIGURE_HEADER
        tikz_script += "\\begin{tikzpicture}\n"
        if self._figure_setup:
            tikz_script += f"[{self._figure_setup}]\n"

        # Add variables
        if len(self.variables) > 0:
            for variable in self.variables:
                tikz_script += (
                    f"\\pgfmathsetmacro{{\\{variable.label}}}{{{variable.value}}}\n"
                )

        # Add colors
        if len(self.colors) > 0:
            for name, color in self.colors:
                tikz_script += f"\\colorlet{{{name}}}{{{color.color_spec}}}\n"

        # Add 3D axis
        if self.ndim == 3:
            tikz_script += "\\begin{axis}[\n"
            tikz_script += "view={20}{30},\n"
            if self._show_axes:
                tikz_script += "axis lines=center,\n"
                tikz_script += "xlabel={$x$},\n"
                tikz_script += "ylabel={$y$},\n"
                tikz_script += "zlabel={$z$},\n"
                tikz_script += "grid=major\n"
            else:
                tikz_script += "hide axis\n"
            tikz_script += "    ]\n"

        if self.layers.num_layers <= 1:
            use_layers = False

        # TODO: self.layers.layers is a bit clunky
        layers = sorted([str(lyr) for lyr in self.layers.layers.keys()])
        if use_layers:
            tikz_script += "% Define the layers library\n"
            for lyr_str in layers:
                tikz_script += f"\\pgfdeclarelayer{{{lyr_str}}}\n"
            if len(layers) > 0:
                tikz_script += f"\\pgfsetlayers{{{','.join(layers)}}}\n"

        # Add grid if enabled
        # TODO: Create a Grid class
        if self._grid:
            tikz_script += (
                "    \\draw[step=1cm, gray, very thin] (-10,-10) grid (10,10);\n"
            )
        ordered_layers = []
        buffered_layers = set()

        for key, layer in self.layers.layers.items():
            # layer_order, buffered_layers = update_layer_order(layer, layer_order, buffered_layers)
            reqs = layer.get_reqs()
            if all([r == layer.label for r in reqs]):
                ordered_layers.append(layer)
            elif all([r in [layer.label for layer in ordered_layers] for r in reqs]):
                ordered_layers.append(layer)
            else:
                buffered_layers.add(layer)

            for buffered_layer in list(buffered_layers):
                buff_reqs = buffered_layer.get_reqs()
                if all(
                    [r in [layer.label for layer in ordered_layers] for r in buff_reqs],
                ):
                    # print("Move layer from buffer")
                    ordered_layers.append(buffered_layer)
                    buffered_layers.remove(buffered_layer)
        assert len(buffered_layers) == 0, (
            "Layer order is impossible for layer"
            + f"{[layer.label for layer in buffered_layers]}"
        )
        for layer in ordered_layers:
            tikz_script += layer.generate_tikz(use_layers=use_layers, verbose=verbose)

        if self.ndim == 3:
            tikz_script += "\\end{axis}\n"
        tikz_script += "\\end{tikzpicture}"

        # Wrap in figure environment if necessary
        if self._caption or self._description or self._label:
            figure_env = "\\begin{figure}\n" + tikz_script + "\n"
            if self._caption:
                figure_env += f"    \\caption{{{self._caption}}}\n"
            if self._label:
                figure_env += f"    \\label{{{self._label}}}\n"
            figure_env += "\\end{figure}"
            tikz_script = figure_env
        tikz_script = self._add_tabs(tikz_script)
        return tikz_script

    def generate_standalone(self, verbose: bool = False) -> str:
        """Generate a complete standalone LaTeX document for this figure.

        Args:
            verbose: Passed through to :meth:`generate_tikz`.

        Returns:
            A full LaTeX document string (``documentclass`` … ``document``)
            that can be compiled directly with ``pdflatex``.
        """
        tikz_code = self.generate_tikz(verbose=verbose)

        # Create a minimal LaTeX document
        latex_document = (
            "\\documentclass[border=10pt]{standalone}\n"
            "\\usepackage{tikz}\n"
            "\\usepackage{pgfplots}\n"
            "\\pgfplotsset{compat=newest}\n"
            "\\usetikzlibrary{arrows.meta}\n"
        )
        if self._extra_packages:
            for pkg in self._extra_packages:
                latex_document += f"\\usepackage{{{pkg}}}\n"

        if self.document_setup:
            latex_document += "% Custom document setup\n"
            latex_document += f"{self.document_setup}\n"

        latex_document += f"\\begin{{document}}\n{tikz_code}\n\\end{{document}}"
        return latex_document

    def compile_pdf(
        self, filename: Path | str = Path("output.pdf"), verbose: bool = False
    ) -> None:
        """Compile the figure to a PDF file using ``pdflatex``.

        Requires ``pdflatex`` to be installed and accessible from the
        command line.

        Args:
            filename: Output PDF path. Defaults to ``"output.pdf"``.
            verbose: If ``True``, print the LaTeX source and the
                ``pdflatex`` command before running.
        """
        if isinstance(filename, str):
            filename = Path(filename)

        latex_document = self.generate_standalone()
        if verbose:
            print(latex_document)
        # Use a temporary directory to store the LaTeX files
        with tempfile.TemporaryDirectory() as tempdir:
            # print(f"{type(tempdir) = } {tempdir = }")
            # tempdir = Path(tempdir)
            # tex_file = tempdir / "figure.tex"
            tex_file = Path(tempdir) / "figure.tex"
            with open(tex_file, "w") as f:
                f.write(latex_document)
            # Run pdflatex
            try:
                # Split the path
                head_tail = (str(filename.parent), filename.name)

                output_directory = head_tail[0]
                jobname = head_tail[1].replace(".pdf", "")
                cmd = [
                    "pdflatex",
                    "-interaction=nonstopmode",
                    "-jobname",
                    f"{jobname}",
                    "-output-directory",
                    f"{output_directory}",
                    str(tex_file),
                ]
                if verbose:
                    print(f"{cmd =}")
                subprocess.run(
                    cmd,
                    cwd=tempdir,
                    check=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                # Remove .aux and .log files
                os.remove(filename.with_suffix(".aux"))
                os.remove(filename.with_suffix(".log"))
            except subprocess.CalledProcessError as e:
                print("An error occurred while compiling the LaTeX document:")
                print(e.stderr.decode())
                return

    def savefig(
        self,
        filename: Path | str,
        dpi: int = 300,
        verbose: bool = False,
        transparent: bool = True,
    ) -> None:
        """Save the figure to a file.

        Supported formats: ``.pdf``, ``.tikz``, ``.png``, ``.jpg``,
        ``.jpeg``.  PNG/JPG output first compiles to a temporary PDF and
        then converts via *pymupdf*.

        Args:
            filename: Destination path, including extension.
            dpi: Resolution for raster output (PNG/JPG).
                Defaults to ``300``.
            verbose: If ``True``, print progress messages.
            transparent: If ``True``, render PNG output with a transparent
                background instead of white.  Only supported for ``.png``;
                ignored for other formats.

        Raises:
            ValueError: If the file extension is not supported.
        """
        if isinstance(filename, str):
            filename = Path(filename)

        ext = filename.suffix.lower()

        if ext == ".pdf":
            # Direct compile
            self.compile_pdf(filename=filename, verbose=verbose)
        elif ext == ".tikz":
            if verbose:
                print(f"Saving TikZ code to {filename}")
            tikz_code = self.generate_tikz()
            with open(filename, "w") as f:
                f.write(tikz_code)
        elif ext in [".png", ".jpg", ".jpeg"]:
            # Compile to a temporary PDF first
            with tempfile.TemporaryDirectory() as tempdir:
                temp_pdf = Path(tempdir) / "temp.pdf"

                if verbose:
                    print(f"Compiling TikZ to temporary PDF: {temp_pdf}")

                self.compile_pdf(filename=temp_pdf, verbose=verbose)

                if verbose:
                    print(f"Converting {temp_pdf} → {filename}")

                # Convert PDF → image
                doc = fitz.open(temp_pdf)
                page = doc[0]
                use_alpha = transparent and ext == ".png"
                pix = page.get_pixmap(dpi=dpi, alpha=use_alpha)
                pix.save(filename)
                doc.close()
        else:
            raise ValueError(f"Unsupported file format: {ext}")

    def _show_matplotlib(
        self, dpi: int = 300, verbose: bool = False, transparent: bool = True
    ) -> None:
        """Display the figure in a Matplotlib window.

        Args:
            dpi: Resolution for the intermediate PNG. Defaults to ``300``.
            verbose: If ``True``, print a status message.
            transparent: If ``True``, make the background transparent.

        Raises:
            ImportError: If ``matplotlib`` is not installed.
        """
        try:
            import matplotlib.image as mpimg
            import matplotlib.pyplot as plt
        except ImportError:
            raise ImportError(
                "matplotlib is required for this backend. "
                "Install with: pip install matplotlib\n"
                "Or use backend='system' or backend='pillow'"
            )

        if verbose:
            print("Using matplotlib backend for display.")

        with tempfile.TemporaryDirectory() as tempdir:
            temp_png = Path(tempdir) / "temp.png"
            self.savefig(filename=temp_png, dpi=dpi, verbose=verbose)

            img = mpimg.imread(temp_png)

            # Calculate figure size based on image dimensions
            height_width_ratio = img.shape[0] / img.shape[1]

            fig, ax = plt.subplots(figsize=(10, 10 * height_width_ratio))
            ax.imshow(img)
            ax.axis("off")
            plt.tight_layout(pad=0)
            plt.show()

    def _show_system(
        self, dpi: int = 300, transparent: bool = True, verbose: bool = False
    ) -> None:
        """Display the figure using the OS default image viewer.

        Args:
            dpi: Resolution for the intermediate PNG. Defaults to ``300``.
            verbose: Unused; reserved for future debug output.
            transparent: If ``True``, make the background transparent.
        """
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            temp_path = tmp.name

        try:
            self.savefig(
                filename=temp_path, dpi=dpi, transparent=transparent, verbose=verbose
            )

            # Open with system default viewer
            import platform

            system = platform.system()

            if system == "Darwin":  # macOS
                subprocess.run(["open", temp_path], check=True)
            elif system == "Linux":
                subprocess.run(["xdg-open", temp_path], check=True)
            elif system == "Windows":
                os.startfile(temp_path)  # type: ignore[attr-defined]
            else:
                print(f"Saved figure to: {temp_path}")
                print("Please open manually (unsupported platform for auto-display)")
        except Exception as e:
            print(f"Could not open figure automatically: {e}")
            print(f"Figure saved to: {temp_path}")

    def _show_pillow(
        self, dpi: int = 300, verbose: bool = False, transparent: bool = True
    ) -> None:
        """Display the figure using PIL/Pillow's built-in image viewer.

        Args:
            dpi: Resolution for the intermediate PNG. Defaults to ``300``.
            verbose: Unused; reserved for future debug output.
            transparent: If ``True``, make the background transparent.

        Raises:
            ImportError: If ``Pillow`` is not installed.
        """
        try:
            from PIL import Image
        except ImportError:
            raise ImportError(
                "Pillow is required for this backend. "
                "Install with: pip install Pillow\n"
                "Or use backend='system' or backend='matplotlib'"
            )

        with tempfile.TemporaryDirectory() as tempdir:
            temp_png = Path(tempdir) / "temp.png"
            self.savefig(
                filename=temp_png, dpi=dpi, transparent=transparent, verbose=verbose
            )

            img = Image.open(temp_png)
            img.show()

    def show(
        self,
        width: int | None = None,
        height: int | None = None,
        dpi: int = 300,
        verbose: bool = False,
        backend: str = "matplotlib",
        transparent: bool = True,
    ) -> None:
        """Display the figure interactively.

        In Jupyter notebooks the figure is shown inline via IPython's
        ``display``.  In regular Python sessions it is opened using the
        selected *backend*.  Display is suppressed automatically when
        running under pytest or when the ``tikzfigure_NO_SHOW=1``
        environment variable is set.

        Args:
            width: Display width in pixels (Jupyter only).
            height: Display height in pixels (Jupyter only).
            dpi: Resolution used when rendering to a raster image.
                Defaults to ``300``.
            verbose: If ``True``, print compilation details.
            backend: Display backend for non-Jupyter environments.
                One of:

                - ``"matplotlib"`` *(default)* – open in a Matplotlib
                  window.
                - ``"system"`` – open with the OS default image viewer.
                - ``"pillow"`` – open with PIL/Pillow.

        Raises:
            ValueError: If *backend* is not one of the supported values.
        """
        # Skip display in test/headless environments
        if os.environ.get("tikzfigure_NO_SHOW") == "1" or os.environ.get(
            "PYTEST_CURRENT_TEST"
        ):
            if verbose:
                print("Display suppressed (test/headless mode).")
            return

        # Check if we're in a Jupyter/IPython environment
        try:
            from IPython import get_ipython

            if get_ipython() is not None and "IPKernelApp" in get_ipython().config:
                # We're in Jupyter - use IPython display
                from IPython.display import Image, display

                with tempfile.TemporaryDirectory() as tempdir:
                    temp_pdf = Path(tempdir) / "temp.png"
                    self.savefig(
                        filename=temp_pdf, transparent=transparent, verbose=verbose
                    )
                    display(Image(filename=temp_pdf, width=width, height=height))
                return
        except (ImportError, AttributeError):
            pass

        # Not in Jupyter - use specified backend
        if backend == "matplotlib":
            self._show_matplotlib(dpi=dpi, verbose=verbose, transparent=transparent)
        elif backend == "system":
            self._show_system(dpi=dpi, verbose=verbose, transparent=transparent)
        elif backend == "pillow":
            self._show_pillow(dpi=dpi, verbose=verbose, transparent=transparent)
        else:
            raise ValueError(
                f"Unknown backend '{backend}'. "
                "Options: 'matplotlib', 'system', 'pillow'"
            )

    # ---------------------------------------------------------------- #
    # Properties

    @property
    def document_setup(self) -> str | None:
        """Raw LaTeX inserted in the preamble before ``\\begin{document}``."""
        return self._document_setup

    @property
    def extra_packages(self) -> list | None:
        """Extra LaTeX packages included in the standalone preamble."""
        return self._extra_packages

    @property
    def ndim(self) -> int:
        """Number of spatial dimensions (``2`` or ``3``)."""
        return self._ndim

    @property
    def layers(self) -> LayerCollection:
        """The :class:`LayerCollection` holding all drawing layers."""
        return self._layers

    @property
    def colors(self) -> list[tuple[str, Color]]:
        """List of ``(name, Color)`` pairs defined with :meth:`colorlet`."""
        return self._colors

    @property
    def variables(self) -> list:
        """List of :class:`Variable` objects defined in this figure."""
        return self._variables

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, TikzFigure):
            return NotImplemented
        return self.to_dict() == other.to_dict()

    # ------------------------------------------------------------- #
    def __repr__(self) -> str:
        """Return the generated TikZ source as the object representation."""
        return self.generate_tikz()

    def __str__(self) -> str:
        """Return the generated TikZ source as a string."""
        return self.generate_tikz()
